### ISSUE TITLE
Dockerfile default to Python 3

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1004]
Default the Dockerfile to Python 3. 

CTFd will support Python 2 until the 3.0 release but we should start defaulting to Python 3 in the Dockerfile.

**Comment by hugoprudente** [comment]
@ColdHeat are you thinking on using alpine or alpine 3.8 as I have a Dockerfile with Docker 3 that I can PR.

**Comment by ColdHeat** [comment]
@hugoprudente, what do you mean about alpine vs alpine 3.8? Doesn't that mean alpine? Or do you mean Python 3.8?

**Comment by ColdHeat** [comment]
Re-opened b/c commit was reverted.

**Comment by frankli0324** [comment]
why revert? I've been using python3 for several (2 or 3) activities, and I didn't encounter any issues with it.

**Comment by ColdHeat** [comment]
Closed in #1111
