### ISSUE TITLE
Feature Request: Require flags to unhide challenges

### ISSUE THREAD

**Issue by frohoff** [CTFd/CTFd#1009]
Ideally the scoreboard would prevent challenges from being made visible until they have at least one flag added since they can't be solved prior to that. This would prevent mistakes caused by rushed challenge entry (tangentially related to #1008 as it makes it easier to miss a step)

**Comment by ColdHeat** [comment]
I like this idea. 

Related to #926

**Comment by ColdHeat** [comment]
Closed in #1147

![image](https://user-images.githubusercontent.com/166333/67172636-0f586b00-f38a-11e9-9b7c-b13dd99dc7f6.png)
