### ISSUE TITLE
What value should I enter for --azure-file-volume-mount-path

### ISSUE THREAD

**Issue by RezaRahmati** [CTFd/CTFd#1010]
Hello

I tried to host ctfd from docker image in docker hub on Azure Container Instance, which is working perfect and no issue, until I restart the container, then all data is gone.

I followed this tutorial to keep state of container in file share
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files

Everything is ok unless I don't know what value should I enter for --azure-file-volume-mount-path

Since I am newbie in docker I appreciate any help

**Comment by ColdHeat** [comment]
I don't use Azure so I don't really know but you can look at how `docker-compose.yml` works to see what it mounts externally into to the container. You should consider using other external services to store your data for persistency.
