### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Stealth5hadow** [CTFd/CTFd#1024]
**Environment**:

  - CTFd Version/Commit: 2.1.2
  - Operating System: Ubuntu Linux 18.04
  - Web Browser and Version: Firefox 67.0.1

**What happened?**

The ctfd software does not properly load the zip file I exported.  It will usually stay on the upload bar and will not show any signs of it making any actual progress.  The only way the bar goes away is if I click off of it.  If I do that then whenever I try to go to another of the other tabs, like challenges, then it gives me the error "500 An Internal Server Error has occurred".  It is probably also important to note that I have the Ubuntu Linux OS set as a server to run the program while I connect to it from a Windows 10 OS from the Firefox browser.

**What did you expect to happen?**

I expected the exported file to properly upload and have everything setup for the instance I had already made.

**How to reproduce your issue**

Try uploading a file and then waiting for it to upload completely (mine doesn't ever finish loading). Try to click off that and then go to the challenges tab.  Should give an internal server error at this point.

**Comment by ColdHeat** [comment]
Hi @Stealth5hadow, when did you create the export? Old 1.x exports can't be imported into 2.x. I've recently been able to export/import across CTFd instances so it should be working but older exports could be difficult.

**Comment by Stealth5hadow** [comment]
Hi @ColdHeat, I made the export fairly recently.  I had recently started working with the CTFD software this week so all the exports I have made have been on the latest version of CTFD that is out.  So it shouldn't be an issue with it being an old export.

**Comment by ColdHeat** [comment]
Does the `import.py` script work or give you any errors?

**Comment by Stealth5hadow** [comment]
Hi @ColdHeat, it seems that I just didn't completely install everything completely.  I removed everything and started over and followed all the directions through again.  It is now working properly.  Thanks for trying to help me though!
