### ISSUE TITLE
Issue with MariaDB

### ISSUE THREAD

**Issue by DL02926** [CTFd/CTFd#1026]
**Environment**:

  - CTFd Version/Commit: 2.1.2 / 2019-05-13
  - Operating System: Ubuntu Server 18.04.02
  - Web Browser and Version: Google Chrome v74.0.3729.169
  - MariaDB Version: 10.1.40
  - Deployment Method: uWSGI & NGINX
  - Server Hosting: AWS EC2 Instance

**What happened?**
I received an internal server error after attempting to use MariaDB as my database. When using SQLite, everything works fine; I can access it from my domain with no difficulty. I am attempting to switch to MariaDB so I can handle a larger load and have more control.

**What did you expect to happen?**
For the website to load without any issues.

**How to reproduce your issue**
Attempt to use MariaDB v10.1.40 to house your database.

**Any associated stack traces or error logs**
The following was pulled from my uwsgi.log file:

>   File "/home/ubuntu/CTFd/app/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/CTFd/app/venv/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/ubuntu/CTFd/app/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/CTFd/app/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON, \n\tPRIMARY KEY (id)\n)' at line 10")
[SQL:
CREATE TABLE challenges (
        id INTEGER NOT NULL AUTO_INCREMENT,
        name VARCHAR(80),
        description TEXT,
        max_attempts INTEGER,
        value INTEGER,
        category VARCHAR(80),
        type VARCHAR(80),
        state VARCHAR(80) NOT NULL,
        requirements JSON,
        PRIMARY KEY (id)
)
]
(Background on this error at: http://sqlalche.me/e/f405)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
--- no python application found, check your startup logs for errors ---
[pid: 16432|app: -1|req: -1/1] 141.165.50.206 () {46 vars in 832 bytes} [Mon Jun 17 17:50:19 2019] GET /ctf/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)

Could this possibly have something to do with me using MariaDB 10.1.x as opposed to 10.3.x? 

This is my first ever issue on github, apologies if anything is formatted incorrectly.

**Comment by ColdHeat** [comment]
The docs discuss that the database needs to support the JSON type. http://docs.ctfd.io/en/latest/deployment.html#database-server. 

MariaDB doesn't support JSON up until 10.2.7 as discussed here: https://mariadb.com/kb/en/library/json-data-type/.

**Comment by davidhcefx** [comment]
Same here.
MariaDB install from latest package manager, and it just wasn't compatible.
```
mariadb  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
