### ISSUE TITLE
Start time / End time form is breaky

### ISSUE THREAD

**Issue by dwendt** [CTFd/CTFd#103]
The times here are sort of ambiguous and scary, which sucks because they're an important part of every CTF. Getting timezones accurate and correct is very important.

Additionally, no clue if it's just my fork/deployment, submission of the times when the form is submitted is broken. It'd often save an incorrect time or just leave end time blank. I've no idea what would cause this, as we've only changed CSS in relation to forms.

I'd suggest some countdown in the panel or elsewhere that would allow an administrator to confirm the time is accurate (as if it says 8 hrs and you know it's not 8 hrs until your ctftime time of XX:XX UTC, something's broken).

I'd also suggest the time be displayed as a unix timestamp (UTC) or other equally verifiable raw format.

**Comment by ColdHeat** [comment]
There is actually a hidden unix timestamp input form that is populated as each dropdown changes. 

I'll look into this later today.

**Comment by ColdHeat** [comment]
Also timezones are normalized to your localtime via moment js

**Comment by edenecho** [comment]
It seems like the Start time in the config page is still broken. I noticed that setting it to 0900 hrs does not get saved in the config instead giving wrong UTC. I have my OS time synced to timezone, but still getting wrong UTC time in CTFd. It scares me.

**Comment by ColdHeat** [comment]
Not sure why this scares you. 

Can you give me a screenshot of what you are seeing? 

I believe this is an issue with not displaying the timezone to the user and instead being opinionated and automatically choosing it. This will be fixed in a later update.

**Comment by edenecho** [comment]
![ctfdstartendtime](https://cloud.githubusercontent.com/assets/21356313/18463118/7c59239a-79ba-11e6-83b5-9e3ab23ce03b.png)

Attached is the screenshot after I set it to September 18 2016 9:00hrs, showing UTC of 1474128000 which converts to (September 18 2016 00:00:00) when I run a simple python script:

from datetime import datetime

print datetime.fromtimestamp(1474128000)

**Comment by ColdHeat** [comment]
Thanks for the report, just squashed that bug.

**Comment by ColdHeat** [comment]
![image](https://cloud.githubusercontent.com/assets/166333/20698046/0d3ae9e6-b5cc-11e6-9d09-3d285802e773.png)

The time form has received some overhauls to more precisely represent data. Internally times are still stored as UTC timestamps.

**Comment by ColdHeat** [comment]
Haven't heard of any issues regarding this lately so I was ABOUT to close it. But this functionality should be tested.

**Comment by ColdHeat** [comment]
There are now tests for the ctftime behavior. 

The admin panel shows you what values it will use before submitting to the server so there is less likely to be an issue from the client side.
