### ISSUE TITLE
Exporting always downloads the same zip

### ISSUE THREAD

**Issue by AngelOnFira** [CTFd/CTFd#1032]
**Environment**:

  - CTFd Version/Commit: 2.1.2
  - Operating System: Standard docker-compose launch on Linux
  - Web Browser and Version: Firefox 67.0.3

**What happened?**

When exporting the challenges from `/admin/config#backup`, the same zip downloads as the first export. It only contains the one challenge that was there when the backup was made, although there are around 30 challenges.

**What did you expect to happen?**

The export should download a zip file with all of the current challenges.

**How to reproduce your issue**

Export multiple times with different numbers of challenges.

**Comment by dcode** [comment]
I ran into this too. I worked around it by disabling caching in my browser using developer tools. Ideally the cache header sent to the browser would have a very short TTL.
