### ISSUE TITLE
majorleaguecyber official icon not working correctly 

### ISSUE THREAD

**Issue by Lumineo** [CTFd/CTFd#1038]
**Environment**:

  - CTFd Version/Commit: 2.1.3
  - Operating System: ubuntu 16.04
  - Web Browser and Version: Opera 60.0.3255.170

**What happened?**
Clicked Official user "official" button and it redirected to https://majorleaguecyber.org/u/username

**What did you expect to happen?**
it would redirect to  https://majorleaguecyber.org/username

**Comment by ColdHeat** [comment]
Thanks for reporting this and sorry it took so long to respond here. CTFd implements the correct behavior and it's actually some changes in MLC that broke this. It should be fixed now.
