### ISSUE TITLE
Notifications through https can not work

### ISSUE THREAD

**Issue by akkayin** [CTFd/CTFd#1040]
**Environment**:

  - CTFd Version/Commit: 2.1.2
  - Operating System: docker-compose
  - Web Browser and Version: chrome latest

**What happened?**
Notification XSS alert does not work if I use a NGINX to proxy at the fronted by https.
My proxy is like this 
client -> NGINX(https) -> gunicorn(http)
And I try if I do not use https protocols, it works. So I think it is because the CORS.
**What did you expect to happen?**
Send Notification to everyone when admin submits some notifications/
**How to reproduce your issue**

**Any associated stack traces or error logs**
Chrome does not give me any error logs and just redirect.

**Comment by ColdHeat** [comment]
CORS and HTTPS aren't exactly related. It sounds to me like you have an issue with your nginx configuration.

**Comment by akkayin** [comment]
> CORS and HTTPS aren't exactly related. It sounds to me like you have an issue with your nginx configuration.

Yeah, your are right.
the "/events" endpoint has to be set at the "keep alive" status in nginx configuration.
And I solved it.
