### ISSUE TITLE
import will crash ctfd

### ISSUE THREAD

**Issue by Lumineo** [CTFd/CTFd#1041]
**Environment**:

  - CTFd Version/Commit: 2.1.3
  - Operating System: ubuntu 18.04
  - Web Browser and Version: Opera 60.0.3255.170

**What happened?**
trying to import db (zip file)
**What did you expect to happen?**
it would import db (zip file)
**How to reproduce your issue**

**Any associated stack traces or error logs**
Failed to disable foreign key checks. Continuing.
Error: No support for ALTER of constraints in SQLite dialect

I believe it's Alembic fault

**Comment by ColdHeat** [comment]
Can you provide an export that reproduces this behavior or some kind of stack trace? Imports are tested for this kind of scenario so it's not really clear what you're seeing.

**Comment by sokoide** [comment]
I had the same import crash. If you use mark-2.1.3 docker image, you'll get the "Failed to disable foreign key checks..." message. If you use 2.1.2 or latest docker image as below, it only crashes and the DB is broken.

Steps:
1. docker run -p 8000:8000 -it ctfd/ctfd (or ctfd/ctfd:mark-2.1.3)
2. http://localhost:8000 -> create user "admin" with a password
3. login as admin
4. go to Admin Panel -> back up -> export (zip file downloaded)
5. Admin Panel -> import -> give the downloaded zip file -> [import]

Result:
DB is broken. The following http requests all returns HTTP 50x.

**Comment by sokoide** [comment]
I confirmed docker image 'ctfd/ctfd:2.0.6' doesn't have the problem. It looks the import feature was broken after 2.0.6.

**Comment by ColdHeat** [comment]
Are you using SQLite for your database backend?

**Comment by ColdHeat** [comment]
I've reproduced this. Fix should be available shortly.

**Comment by ColdHeat** [comment]
This should be closed. Let me know if the latest commit doesn't resolve this issue.

**Comment by sokoide** [comment]
Thank you very much for your prompt fix! I confirmed my problem was fixed. I hope it's fine for the original Lumineo's issue, too.
