### ISSUE TITLE
Score of a challenge should be recalculated whenever scoring parameters are changed.

### ISSUE THREAD

**Issue by pedromigueladao** [CTFd/CTFd#1043]
**Environment**:

  - CTFd Version/Commit: 2.1.3
  - Operating System: Linux
  - Web Browser and Version: any

**What happened?**
When the decay limit is updated, current value should be updated to accommodate the new values.

**How to reproduce your issue**
1) Create a challenge
2) submit a correct answer
3) update the decay limit (similarly for max and min values)

**Comment by ColdHeat** [comment]
Can you clarify? The code already handles updating of the challenge value if the decay changes. 
https://github.com/CTFd/CTFd/blob/master/CTFd/plugins/dynamic_challenges/__init__.py#L121-L133

Do you mean the scoreboard value should change or the challenge value should change?

**Comment by ColdHeat** [comment]
I'm closing this because I need a little more information here. Feel free to update with more information and re-open in the future.

**Comment by ColdHeat** [comment]
This should now be fixed in the 2.2.0-dev branch which is due out soon.

**Comment by pedromigueladao** [comment]
Hi @ColdHeat thank you. I missed this one. Just to add some context the issue is: suppose challenge X is worth 500, and users A, B, and C solve it.
If you then update the decay limit, the scoring of users A, B and C are not updated accordingly. Only whenever a new used D solves the challenge. I hope it is clearer now.
