### ISSUE TITLE
Using javascript in pages

### ISSUE THREAD

**Issue by redwiz666** [CTFd/CTFd#1068]
I tried creating a new page and adding a js file but it will not run the code. I looked in the filesystwm and got the path after uploading the js file but none of the functions will run.

I tested the code on and stand alone web server and it runs fine.

Is it not coded to run js from web pages?

**Comment by ColdHeat** [comment]
You should be able to just run `<script src="file.js"></script>` or add your script inline? You can't copy directly from the path though. You would need to upload the file and then serve it from the `/files` handler.
