### ISSUE TITLE
help for password

### ISSUE THREAD

**Issue by muhammadhendro** [CTFd/CTFd#1073]
sorry for my bad
iam forgot my password for admin :v
thx ctfd

**Comment by frankli0324** [comment]
I think there's something called `mysql-client` you may want to look into

**Comment by muhammadhendro** [comment]
Ok thanks man

Pada tanggal 2 Agt 2019 10.11, "Frank" <notifications@github.com> menulis:

**Comment by frankli0324** [comment]
...... I was just bullshitting, I just want to say it's pointless to issue this here...
a quick hack could be commenting out the `verify_password` step in the login function

https://github.com/CTFd/CTFd/blob/3453eafcab250e50b46a3aede384890a75641925/CTFd/auth.py#L266

and then uncomment it after you have control of the admin account where you can reset your own password at /admin/users

the password is stored in bcrypt_sha256, so playing with the database may not be a wise way to do... you CAN generate some hashed value and put it into the database though... theoretically

**Comment by frankli0324** [comment]
if you are already there with the database route, following script generates something that you can put into the database
```python
from passlib.hash import bcrypt_sha256
def hash_password(plaintext):
    return bcrypt_sha256.hash(str(plaintext))
```

**Comment by ColdHeat** [comment]
You can simply create a new user and then change it's type to admin in the database.

**Comment by frankli0324** [comment]
..🤷‍♂️
