### ISSUE TITLE
style of problem "Message" affects original page

### ISSUE THREAD

**Issue by frankli0324** [CTFd/CTFd#1074]
**What did you expect to happen?**
the stylesheet should only affect the problem description itself
**How to reproduce your issue**
create a problem with description:
```html
<style>
h1{font-size:0;}
</style>
```
emmm... all the titles are no where to be seen!

**recommendations...maybe?**
iframing the problem description is ..kinda reasonable? I think?

I don't know is this a bug report or a feature request.. maybe both?

**Comment by frankli0324** [comment]
by the way, I encountered this problem when I'm trying to add math equations to the problem description which the current markdown renderer doesn't support, so I exported the md file to html document, then pasted it into the description.

so maybe, switching the core theme's markdown renderer to something that supports math equations? feature request?

**Comment by ColdHeat** [comment]
Challenges allow for raw html. If you add in a style tag it will obviously affect the entire page. This will be entirely disallowed in a future version but not sure why you would expect your expected behavior.

**Comment by frankli0324** [comment]
what does "This" refer to?
style? or raw html?
what i expect is an iframe..

**Comment by ColdHeat** [comment]
Raw HTML will be entirely disallowed in a future version of CTFd.

An iframe makes very little sense to me but if you want an iframe, you are free to implement it as an iframe with a custom plugin.

**Comment by frankli0324** [comment]
okay, got it. thanks
