### ISSUE TITLE
Idea : Reset Challenge button

### ISSUE THREAD

**Issue by sachinkamath** [CTFd/CTFd#1084]
Right now, resetting a challenge is not possible. Some reasons the CTF admins would want to reset a challenge : 

1. Challenge attachment was wrong or there was an error in the design. This might have lead to a false flag being given to the participants. The CTF admins would want to fix it and reset the challenge to remove all wrong solves from it for better statistics.

2. There was an unintended solution to obtain the flag. After the race condition, the admins usually change the flag and fixes the unintended way. An admin may now want to reset and remove all correct solves from the challenge.

This is very hard to fix in current  CTFd deployment through the GUI because the points degraded for a dynamic challenge is not reset after solves are removed. So if a challenge was solved in an unintentional way and all solves were removed, the point will not jump back to the original value. The current solution is to delete the challenge altogether and upload it again (which is kind of tedious)

A "Reset Challenge" button should ideally do the following things : 

1. Remove all solves for the challenge. This will reflect in scoreboard was well.
2. Change the Dynamic Score of the challenge to the initial value (if it's a dynamic points CTF)
3. Maybe add a tooltip above each challenge indicating it was edited?

@ColdHeat What do you think? Does it make sense to implement this?

**Comment by ColdHeat** [comment]
I'm not sure this is better than just deleting and re-adding the challenge. Which admittedly needs to be streamlined. 

However, if you update the challenge manually after having deleted solves the dynamic valuation will be re-calculated.

**Comment by sachinkamath** [comment]
@ColdHeat, so something like a "Clone challenge" button then? Does that make sense?

**Comment by frankli0324** [comment]
sounds problematic when it comes to database
