### ISSUE TITLE
ImportError: No module named 'marshmallow.compat'

### ISSUE THREAD

**Issue by non-one** [CTFd/CTFd#1088]
today , I try to build the ctfd myself, But when I Run python3 server.py,something is wrong
```
Traceback (most recent call last):
  File "serve.py", line 1, in <module>
    from CTFd import create_app
  File "/home/ettercap/CTFd/CTFd/__init__.py", line 13, in <module>
    from CTFd import utils
  File "/home/ettercap/CTFd/CTFd/utils/__init__.py", line 62, in <module>
    from CTFd.models import db, Configs  # noqa: E402
  File "/home/ettercap/CTFd/CTFd/models/__init__.py", line 2, in <module>
    from flask_marshmallow import Marshmallow
  File "/usr/local/lib/python3.5/dist-packages/flask_marshmallow/__init__.py", line 19, in <module>
    from . import fields
  File "/usr/local/lib/python3.5/dist-packages/flask_marshmallow/fields.py", line 15, in <module>
    from marshmallow.compat import iteritems
ImportError: No module named 'marshmallow.compat'
```
but I do exec 
```
pip install -r requirements.txt
```
and import marshmallow is ok!

someone can help me?

**Comment by bradley-evans** [comment]
Getting this error, too, when I do `flask run` in the `CTFd` directory. Seems to be related to versions of packages used, see [issue on marshmallow's GitHub page](https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/208).

**Comment by non-one** [comment]
@bradley-evans , I try that way and check the version of marshmallow.
As
```
pip3 install --no-cache-dir --upgrade marshmallow
Requirement already up-to-date: marshmallow in /usr/local/lib/python3.5/dist-packages (3.0.0)

```
and
```
Installing collected packages: marshmallow-sqlalchemy
  Found existing installation: marshmallow-sqlalchemy 0.16.3
    Uninstalling marshmallow-sqlalchemy-0.16.3:
      Successfully uninstalled marshmallow-sqlalchemy-0.16.3
Successfully installed marshmallow-sqlalchemy-0.17.0
```
But it does't work,I am crazy  about that!

**Comment by ddxmaaa** [comment]
i try to use marshmallow==3.0.0b20(the last version after marshmallow-sqlalchemy 0.15.0
release) . use this verison can start ctfd . but it also has a problem .when edit pages will have 500 error .

**Comment by ddxmaaa** [comment]
use marshmallow  2.16.2 can fix sql

**Comment by ColdHeat** [comment]
I've been running CTFd locally for awhile but I haven't installed dependencies for awhile. 

```
flask-marshmallow                  0.9.0
marshmallow                        2.20.0
marshmallow-sqlalchemy             0.15.0
```

These are the marshmallow related dependencies that I have. Can someone confirm that one of them fixes the issue? I can pin the required package afterwards.

**Comment by non-one** [comment]
@ColdHeat  thanks alot, it works!!

**Comment by MartinJM** [comment]
Just a heads-up that this is currently also affecting TravisCI builds, and thus checks.
