### ISSUE TITLE
Import challenges from Markdown

### ISSUE THREAD

**Issue by flexd** [CTFd/CTFd#109]
We are in the process of making a lot of challenges, and would be hosting the same CTF in different locations. One option is to add all the challenges to an instance, and then clone/backup the database before use.

However, it would be cool to be able to import challenges from Markdown files. In my opinion it makes more sense to keep the challenges in a `challenges` directory as markdown files (so we can use Git to manage them). 

YAML frontmatter would be a good option, as you could write the challenge text in markdown, and then have a YAML section on top with title, slug, value, flags/flagRegex and such. The only problem would be to add files.. But I guess having a "Import from markdown" button on the New Challenge page would work to prefill things from the markdown file, and then add the files you want yourself. [1]

[1] https://github.com/eyeseast/python-frontmatter

Does that sound like a good idea?

**Comment by JamieH** [comment]
I like the idea of using a challenges directory and then having a challenge for each folder which holds the contents for that challenge, including flags, description. I'd suggest using a JSON file for the challenges rather then YAML since the challenges already use JSON to store the flags

**Comment by ColdHeat** [comment]
Really the question to ask when you're making decisions like this is "what is your database". The filesystem makes for a fine database but I'm not sure it makes the most sense with web applications. 

Well for files you can have it wget files specified in URLs in the markdown or YAML or JSON or have the files serialized to base64 and saved in the JSON/YAML. It's not really hard to support both. Honestly security issues pop out to me more than implementation issues. 

I think the best takeaway from this is having a way to mass import challenges. I'm not sure changing the entire database setup makes a lot of sense since we'd still be using the database in the alternative setup, it would just have some other things that are not in the database.

**Comment by flexd** [comment]
As the system is designed today, I never intended replacing the database with files. But it makes sense to store challenges in git, so that it's not relying on having a database backup between instances/CTF challenges.

In the scenario where challenges were loaded from disk and not a database, I would have had the challenges loaded from disk on start/reload, and not on each visit. That is probably what I would do if I was making a system from scratch. But since the database is already in use, it makes more sense to import them into the database.

What security issues do you see with this approach?

I believe YAML frontmatter with markdown files is a better approach than JSON, because it's so much easier to read and edit. Barely any syntax to deal with.

**Comment by nategraf** [comment]
I am working with a team in the beginning stages of hosting a CTF, and we are writing our problems now. This is something we are looking for as well and I plan on implementing a utility to take all of the challenges in the database and dump the to YAML and load them again in a similar manner. 

I will begin working on this utility after soon, and would like this to be something usable by everyone. @ColdHeat do you have any guidelines on how you would like to see this done? If not I will write a python script which uses them already implemented models for sqlalchemy and add an encoder/decoder script to dump and load the database.

**Comment by ColdHeat** [comment]
@nategraf A python script that tries to follow PEP 8 and uses the SQLAlchemy models sounds perfectly fine to me. 

I would like to see it export to both JSON and YAML but whatever suits your needs first will be useful. I can jump in and change some things as well once you feel like submitting a PR or pushing the code somewhere. 

This does raise some additional questions about having a CONTRIBUTING.md file.

**Comment by ColdHeat** [comment]
It also probably makes sense to have an auto-import feature in CTFd to assist in the deployment of a more "canned" CTF. 

Could assist in CTFs having a sort of deployable instance that they can release after the fact.

**Comment by bkimminich** [comment]
Having an easy way to import a list of challenges would be awesome. Personally don't really care if it is `JSON`, `MD` or `YML`. Anything that get rid of the need to a) enter challenges through the Web UI or b) insert them into the MySQL directly is a highly appreciated improvement to make my <https://www.npmjs.com/package/juice-shop-ctf-cli> tool even more convenient!

**Comment by nategraf** [comment]
I actually recently fished a couple scripts to do just this. It currently supports YAML import and export. They are a part of my teams WIP [fork of CTFd, TAMUctf](https://github.com/tamuctf/CTFd/tree/tamuctf). 

To use these script go ahead and download, [import-chal.py](https://github.com/tamuctf/CTFd/blob/tamuctf/import-chal.py) and [export-chal.py](https://github.com/tamuctf/CTFd/blob/tamuctf/export-chal.py) and put them in the base of your CTFd repo. (They work elsewhere, but are preconfigured to work there without passing in any args)

Call `./export-chal.py` to take all the challeneges and files from your DB and put it into a YAML file and directory. Call `./import-chal.py` to put all those challeneges back. The YAML file follows the [this spec](https://docs.google.com/a/tamu.edu/document/d/1SNkYFIEP9hcaVtHc9XbbJ4DjAZJX2pF8QKOvWp8g0iw/edit?usp=sharing).

I'd appreciate any feedback or issues you find with the script, and I'm on the CTFd.io slack channel if your ever want to chat!

**Comment by reenberg** [comment]
@nategraf that is awesome, just what i have been looking for.  However I am not able to browse your tamuctf branch (getting 404) which also means that i can't grab your two scripts.

**Comment by nategraf** [comment]
Sorry for the late response!

It's been moved to here! https://github.com/tamuctf/ctfd-portable-challenges-plugin

Let me know if it's not immediately obvious how to use them. The aim is to have them be usable by anyone, so if you can't figure it out I want to fix them!

**Comment by ColdHeat** [comment]
Ideas like this are officially supported via https://github.com/CTFd/ctfcli and the challenge.yml specification there.
