### ISSUE TITLE
How to run multiple instances on same system ??

### ISSUE THREAD

**Issue by donregent** [CTFd/CTFd#1090]
In our class environment we would like to run multiple CTFd servers (challenges) on the same linux host. We haven't quite got this yet, looking for advice. We've found that there are multiple directories referenced in the "docker-compose.yml" file. It looks like we can create unique directory names that reference the TCP port like "/var/uploads.8006" and add the port number to the database url. Aside from these changes - file paths, database references - what else do we need to change to provide collission free environments? For example, the REDIS_URL? (I don't know enough about REDIS to ask a question). 

If we can't run multiple isolated instances, thats OK - I can just create multiple VMs and run two at a time with different IP addresses / names.  

Thanks in Advance for advice. 

**Environment**:
  - CTFd Version/Commit: 2.1.2
  - Operating System: Ubuntu 18.04 LTS
  - Web Browser and Version: (recent firefox, maybe 4-5 mo old)

**Comment by ColdHeat** [comment]
You can change the port used by CTFd and then reverse proxy between them? Or use two checkouts of the repo?
