### ISSUE TITLE
I have a problem when I use it.Feedback.

### ISSUE THREAD

**Issue by Gu-f** [CTFd/CTFd#1098]
**Environment**:

  - CTFd Version/Commit:version 2.1.4
  - Operating System:Ubuntu16.04.6LTS server
  - Web Browser and Version:chrome

**What happened?**
Unable to create challenge.
The browser didn't respond when I clicked the Create button.
Then........
Server responded with 403 error.
"POST /api/v1/challenges HTTP/1.1" 403 -

At first I thought it was a permission issue, so I gave all project files 777 permissions, but it was the same problem.
**What did you expect to happen?**

**How to reproduce your issue**
I am having this problem after a normal installation.
The installation directory is in /root/ctfd.
Execute with root privileges.
**Any associated stack traces or error logs**
"POST /api/v1/challenges HTTP/1.1" 403 -
"POST /api/v1/challenges HTTP/1.1" 403 -

**Comment by ColdHeat** [comment]
Creating challenges should be a tested behavior. This 403 is likely due to your browser. I have seen issues with Chrome failing to send cookies for some reason if devtools are open. Perhaps that is an issue here.
