### ISSUE TITLE
Admin Panel doesn't work

### ISSUE THREAD

**Issue by PierreCdb** [CTFd/CTFd#1102]
Hello, 
I use CTFd stable 2.1.3 but when I tring to enter the admin panel I got this error. 
The admin panel worked 2 weeks ago and nothing has changed in the configuration
Can you help me to reslove it ?
Thank you

ctfd_1   | [09/06/2019 21:13:54] 185.246.211.98 - admin logged in
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:13:54 +0000] "POST /login?next=%2Fadmin%2Fstatistics%3F HTTP/1.1" 302 243 "https://xxxxxxxxxxxx/login?next=%2Fadmin%2Fstatistics%3F" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
ctfd_1   | 172.26.0.5 - - [06/Sep/2019:21:13:54 +0000] "POST /login?next=%2Fadmin%2Fstatistics%3F HTTP/1.0" 302 243 "https://xxxxxxxxxxxx/login?next=%2Fadmin%2Fstatistics%3F" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:13:57 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:00 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:03 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:06 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:09 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:12 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:15 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:18 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:22 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
nginx_1  | 185.246.211.98 - - [06/Sep/2019:21:14:25 +0000] "GET /admin/statistics HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"

**Comment by ColdHeat** [comment]
499 status codes appears to be specific to your setup? Are you able to access the CTFd server by hitting it directly? Probably on `http://localhost:8000`?
