### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by myxss** [CTFd/CTFd#1105]
![image](https://user-images.githubusercontent.com/33475775/64524189-9a2c5b80-d330-11e9-9f1e-a7528ca9f3dc.png)

**Comment by ColdHeat** [comment]
There's a lot of factors that could apply here. I have no way of testing this for you without more information. For me locally it loads in 200 ms. 

![image](https://user-images.githubusercontent.com/166333/64590084-b520bf00-d374-11e9-88f6-0ca1fa329907.png)
