### ISSUE TITLE
Verification during setup phase

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1112]
There isn't any verification done on setup which sometimes leads people to enter in impossible information. We should verify data.

**Comment by jimender2** [comment]
What data were you hoping to verify?

**Comment by ColdHeat** [comment]
@jimender2 pretty simple things. 

- username isn't taken
- email isn't already registered
- password is reasonably complex

**Comment by jimender2** [comment]
That sounds pretty simple. I can attempt to work on that.

**Comment by jimender2** [comment]
So it appears the first two things on your list are already taken care of in the registering page (when we first set up the CTFd instance, it should be a blank slate and should not matter).

Another thought that I had that I wanted to know your opinion on is if we increase the complexity of the password, should we have the user type it in twice to confirm the password is what they wanted it to be?

**Comment by ColdHeat** [comment]
@jimender2, this is for the setup page not the registration page. I don't believe there's any verification during the setup phase. 

User password confirmation isn't really a big deal imo. I've never seen it be an issue during setup. What's more common is people leave in a blank password unintentionally.

**Comment by jimender2** [comment]
I have verification done for all of the requirements above except for the database search. I keep getting an error constructing the query and have no idea why.
