### ISSUE TITLE
Additional notification delivery methods

### ISSUE THREAD

**Issue by grant-h** [CTFd/CTFd#1118]
Allow to choose between receiving notification as:
- Modal - Increment counter but remove on tab focus
- Toast - Increment counter. Remove on notification page load
- Choose if notification comes with sound or no sound. 

For SwampCTF 2019 we extended the notifications interface to be choose between poping up a message or just incrementing the notification count:

![image](https://user-images.githubusercontent.com/3030665/65163521-0da52b80-da09-11e9-8140-a034f824c3fa.png) 

I added a checkbox on the admin view to enable popups when sending notifications. Otherwise a notification counter is incremented and stored in a cookie. HTML local storage could be used instead to persist across refreshes. Technically this could be stored on the server as well, but that's a lot of book keeping, more requests, and teams that share accounts will have their notification count cleared when one user visits the notification page.

Here is a RFC patch to enable this feature: https://gist.github.com/grant-h/5ae1c41bf242aa170dedad4849e0497c

![image](https://user-images.githubusercontent.com/3030665/65163534-13027600-da09-11e9-88db-66ba6370f57b.png)

**Comment by ColdHeat** [comment]
I like this idea. I think the count can be stored in a cookie or localStorage and then cleared when checking the notification.

**Comment by ColdHeat** [comment]
Closed in #1154
