### ISSUE TITLE
If challenges have the same name, they also have the same anchor/slug

### ISSUE THREAD

**Issue by ianklatzco** [CTFd/CTFd#1120]
**Environment**:

  - CTFd Version/Commit: 7a7595cf033b9198045a9daed79944d2992f4f49
  - Operating System: Linux
  - Web Browser and Version: Chrome

**What happened?**

I made two challenges (in different categories) with the same name. The both produce the same slug/anchor: [https://ctf.sigpwny.com/challenges#old-oaken-bucket](https://ctf.sigpwny.com/challenges#old-oaken-bucket). Re-opening the link goes to the most-recently created challenge.

**What did you expect to happen?**
I would except different slugs for the different challenges, so that you can link to them directly.

I believe this was a relatively recent change (<1y) -- iirc they used to have slugs by challenge number.

Most ctf's probably aren't going to have duplicate challenge names, so this probably isn't a problem. Still, wanted to file an issue so there's a record of the bug.

**Comment by ColdHeat** [comment]
To be frank, I don't really like the solution to this problem but I suppose I have also run into it at least once so it's probably worth a fix. The URLs without specific IDs just look a lot better than with them.

**Comment by ColdHeat** [comment]
Closed in #1522
