### ISSUE TITLE
Forbidden | finish install ctfd but can't setup CTFd platform

### ISSUE THREAD

**Issue by muhammadhendro** [CTFd/CTFd#1131]
[https://i.imgur.com/l3SsK4A.png](https://i.imgur.com/l3SsK4A.png)
[https://i.imgur.com/Z4I9MLb.png](https://i.imgur.com/Z4I9MLb.png)
**Environment**:

  - CTFd Version/Commit: latest
  - Operating System:  Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-1018-azure x86_64)
  - Web Browser and Version: chromium
 
**What happened?**
iam finish install ctfd, and can't setup the platform
**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Did you have devtools open when this happened by chance? Have you tried
clearing out cookies?

**Comment by ColdHeat** [comment]
I don't think this related to CTFd but if you have more information feel free to update.
