### ISSUE TITLE
Make IP List be a Tab

### ISSUE THREAD

**Issue by jimender2** [CTFd/CTFd#1146]
I feel like the IP addresses shown at the bottom of the admin Users page should be in a tab like the rest of the data on that page. It feels out of place how it is displayed currently.

**Comment by ColdHeat** [comment]
Hmm I don't really agree with a tab. It's not really challenge data or something that would  change the score. 

Maybe it would be better as a modal.

**Comment by jimender2** [comment]
That might work out better.  Just needs something because it looks out of place where it is currently.

**Comment by ColdHeat** [comment]
@jimender2 perhaps you could mock up an example of where the IP data might go?

**Comment by ColdHeat** [comment]
I'm going with a modal and a button

![image](https://user-images.githubusercontent.com/166333/80771607-fe02cf00-8b21-11ea-815c-7cdf17cc72fa.png)

**Comment by ColdHeat** [comment]
Closed in #1371
