### ISSUE TITLE
On the challenges page, order the categories lexically

### ISSUE THREAD

**Issue by rcanzanese** [CTFd/CTFd#1149]
For my CTFs, I always want the categories to be ordered lexically.  The lexical ordering of the challenges makes it easier for the participants to navigate.

I already have a fix for this that I can submit as a PR if there is enough interest.

**Comment by ColdHeat** [comment]
This behavior should be implemented as a custom theme. The learning theme in the [CTFd Store](https://ctfd.io/store/) does this.

**Comment by rcanzanese** [comment]
That is fair, thanks.  I'll maintain this as a custom theme for myself.
