### ISSUE TITLE
Backup file fails to download

### ISSUE THREAD

**Issue by sebastian0x00** [CTFd/CTFd#1169]
Hello!
I'm using CTFd Version 2.1.5 via Docker, Nginx 1.14.0 (reverse proxy) and Ubuntu 18.04.3 LTS 
Via Google Chrome, when making a backup of the CTF (export data), starts downloading the zip file (several MB) but before finishing it tells me "Network Error". In firefox the same problem, only that tells me "Failed". 
On the CTF Backup page, it does not show the error. The error is only indicated to me by Google Chrome or Firefox after downloading more than 60 MBs.
The strangest thing that this problem began to appear suddenly, before I could download the backup files without problem.
I tried another connection, another PC and it's always the same problem.
If no solution is possible... Can I make a CTF backup, via any command on the server? (remember that the CTF is running in a Docker)

Any idea of the BUG?

**Comment by ColdHeat** [comment]
You can use the `export.py` script from inside of the container. As for why it's not downloading I suspect it would be nginx terminating the connection.
