### ISSUE TITLE
iterative challenge

### ISSUE THREAD

**Issue by CingulateCortex** [CTFd/CTFd#117]
Just an idea, 

besides seing all the challgenges, maybe second option is openning challenges by solving previous challenge. 

might be good feature :)

**Comment by ColdHeat** [comment]
It's a feature that's been considered for CTFd internally but ultimately not implemented as CTFd's architecture is not quite that intuitive for something like that. 

A plugin architecture will be developed eventually which could allow something like this.

**Comment by ColdHeat** [comment]
The CTFd plugin architecture has been developed and challenge unlocking can be implemented through there. Professional instances of CTFd hosted on [ctfd.io](https://ctfd.io/) have a plugin that implements this behavior so it is definitely possible now.
