### ISSUE TITLE
The Demo website can't works.

### ISSUE THREAD

**Issue by imargin** [CTFd/CTFd#1179]
I hava tried many times, but it always went wrong。
![Clip_20191210_200834](https://user-images.githubusercontent.com/29521747/70528332-e9c93000-1b88-11ea-82fc-b406eb21b603.png)

**Comment by ColdHeat** [comment]
I'm not exactly sure what happened here but demo should automatically reset itself. I've brought it back up manually and I'll keep an eye on it.
