### ISSUE TITLE
Improve email validation (2)

### ISSUE THREAD

**Issue by theKidOfArcrania** [CTFd/CTFd#1184]
The issue here: https://github.com/CTFd/CTFd/issues/622

Doesn't seem to have been fully resolved with the pull request:  https://github.com/CTFd/CTFd/pull/693

Seems like the code that actually calls whether if the email is valid or not is still using the old verification function: https://github.com/CTFd/CTFd/blob/master/CTFd/auth.py#L175

**Comment by ColdHeat** [comment]
This is closed in 2.2.0. Thanks for filing the issue!
