### ISSUE TITLE
Add users via endpoint

### ISSUE THREAD

**Issue by rataman098** [CTFd/CTFd#1196]
Hey there!

I don't know if this is a bug or not, but I'm trying to add users via POST requests to the endpoint `/api/v1/users`, and it's being impossible.

**Environment**
  - CTFd version: 2.2.0 (running on docker)
  - Operating System: Windows 10
  - Web Browser and Version: curl

**What happened?**
When I try to create a user via the endpoint, it returns an error saying that I'm not authorized to acces that URL.

**What did you expect to happen?**
When I make the request, user should be created.

**How to reproduce**
Simply launch the following command:
```bash
 curl -u [USERNAME] -X POST "http://localhost:[PORT]/api/v1/users" -H "content-type: application/json" -b cookie -d '{"name":"foobar",
"email":"fooxx@bar.com",
"password":"123",
"type":"user",
"verified":"false",
"hidden":"false",
"banned":"false"}'
```
It will ask you for the pass. When you introduce it, server will return this:
```json
{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."} 
```

**Any associated stack traces or error logs**
Nope, I haven't seen any relevant info there.

Thanks in advance!

**Comment by ColdHeat** [comment]
You're running into CSRF protection. You can either add a nonce parameter to the JSON payload that you can get from the DOM or use an access token to authenticate instead.  Take a look at the code here: https://github.com/CTFd/CTFd/blob/master/CTFd/utils/initialization/__init__.py#L206-L240
