### ISSUE TITLE
Ability to add members to a team via Admin Panel

### ISSUE THREAD

**Issue by dmartinez301299** [CTFd/CTFd#1197]
Hey there!

I'm making a CTF and I am making users and team registration externally. I have seen that you are able to remove players from teams via the Admin Panel, but you are unable to do the reverse. It'd be great to add users from there, and not having to login into the player account and click "Join team".

Thanks!

**Comment by ColdHeat** [comment]
This will be done in a later version of CTFd. The kind of searching functionality that this requires isn't something that has been prioritized in CTFd before. I would probably look to do this from a plugin/script or with database access for the time being.

**Comment by ColdHeat** [comment]
It looks like this already kind of exists via `POST /api/v1/teams/[team_id]/memberes`.

**Comment by ColdHeat** [comment]
This is closed in v3.3. Quite like the interface too!
