### ISSUE TITLE
Bug loading graphs.js 

### ISSUE THREAD

**Issue by Throgbor** [CTFd/CTFd#1201]
**Environment**:
  - CTFd Version/Commit: 2.2.0 / 2019-12-22

**What happened?**
On page /user, Console : Get ressource not found
Error : 
/themes/core/static/js/graphs.min.js?d=ea03f045 net::ERR_ABORTED 404 (NOT FOUND)

Reference in core/templates/users/public.html
<script defer src="{{ url_for('views.themes', path='js/graphs.js') }}"></script>

**Comment by ColdHeat** [comment]
Does this actually affect graph rendering? My suspicion is that this is related to some quirks in webpack which I haven't created a tracking issue for just yet.

**Comment by ColdHeat** [comment]
This is related to #1203. Closing in favor of that.
