### ISSUE TITLE
Ctfd docker database issue

### ISSUE THREAD

**Issue by linuxjustin** [CTFd/CTFd#1213]
After updating the Ctfd, Im facing database issue like if i close the docker, the ctf setup is gone,again i have to configure the startup ( wheneven i close the docker-compose up and restart  its going with new ctf setup.)

**Comment by ColdHeat** [comment]
Docker containers should be viewed as temporary. If you want to persist data you should use docker-compose which will store CTFd data outside of the containers. Not sure what issue you're running into with docker-compose but this needs more details to be an issue I can investigate.

**Comment by linuxjustin** [comment]
Can you check cause when I run the old version it's working fine like when
I restart the docker-compose up also no issue. But new when I restart the
docker it's going with new startup database.

Regards,
Justin.

**Comment by ColdHeat** [comment]
This seems to work just fine. 

I ran:

```
rm -rf .data && rm -rf CTFd/ctfd.db
docker-compose build && docker-compose up
... Setup the CTFd instance
... exited with Ctrl C
docker-compose up
```
My same account worked and data appeared to have been persisted. 

You'll need to provide more information to better investigate this.
