### ISSUE TITLE
Question: How to modify the challenge view 

### ISSUE THREAD

**Issue by sharathbaddam** [CTFd/CTFd#1227]
I have a challenge which has longer description than normal. I am looking for ways to change the challenge view so that it can be little wider than usual.

Where and how do i change that ?

**Comment by midodany11** [comment]
Did you try this? 
_<code>put your description here</code>_

**Comment by midodany11** [comment]
Try this
<"pre> your description <"/pre>
remove the quotes

**Comment by kolayne** [comment]
Should this be closed?

**Comment by ColdHeat** [comment]
Sure I suppose but not sure why you're going around bumping them :) 

You can set this via theme settings in the config panel for the core theme now I believe. You could also inject custom CSS and JS to expand the view yourself.
