### ISSUE TITLE
Enable external access, only local working

### ISSUE THREAD

**Issue by Unaim1** [CTFd/CTFd#1228]
**Environment**:

  - CTFd Version/Commit:
  - Operating System: Ubuntu 18.04 LTS
  - Web Browser and Version: 

**What happened?**
I've modified `serve.py` to bind address 0.0.0.0 to have access from internet (out the local network) and it's not working

**What did you expect to happen?**

To have access to my CTFd from external network.

**How to reproduce your issue**

**Any associated stack traces or error logs**

root@vps730830:/home/ctfd/CTFd# systemctl status ctfd.service

[Unit]
Description = CTFd
After = network.target

[Service]
PermissionsStartOnly = true
PIDFile = /run/CTFd.pid
User = ctfd
Group = ctfd
WorkingDirectory = /home/ctfd/CTFd
ExecStartPre = /bin/mkdir -p /run/CTFd
ExecStartPre = /bin/chown -R ctfd. /run/CTFd
ExecStart = /usr/local/bin/gunicorn 'CTFd:create_app()' --bind '0.0.0.0:8000' --workers 2 --worker-class 'gevent' --pid /run/CTFd/CTFd.pid --access-logfile "/var/log/CTFd/access.log" --error-logfile "/var/log/CTFd/error.log"
ExecReload = /bin/kill -s HUP $MAINPID
ExecStop = /bin/kill -s TERM $MAINPID
PrivateTmp = true

[Install]
WantedBy = multi-user.target

------------------------------------------

● ctfd.service - CTFd
   Loaded: loaded (/etc/systemd/system/ctfd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-02-07 12:28:51 CET; 13min ago
  Process: 14560 ExecStartPre=/bin/chown -R ctfd. /run/CTFd (code=exited, status=0/SUCCESS)
  Process: 14558 ExecStartPre=/bin/mkdir -p /run/CTFd (code=exited, status=0/SUCCESS)
 Main PID: 14568 (gunicorn)
    Tasks: 3 (limit: 2303)
   CGroup: /system.slice/ctfd.service
           ├─14568 /usr/bin/python3 /usr/local/bin/gunicorn CTFd:create_app() --bind 0.0.0.0:8000 --workers 2 --worker-class gevent --pid
           ├─14580 /usr/bin/python3 /usr/local/bin/gunicorn CTFd:create_app() --bind 0.0.0.0:8000 --workers 2 --worker-class gevent --pid
           └─14581 /usr/bin/python3 /usr/local/bin/gunicorn CTFd:create_app() --bind 0.0.0.0:8000 --workers 2 --worker-class gevent --pid

feb 07 12:28:50 vps730830 systemd[1]: Starting CTFd...
feb 07 12:28:51 vps730830 systemd[1]: Started CTFd.

------------------------------------------------------------

When I do that from the server to the external address (is a VPS) , is answering, but I have no access from my PC to x.x.x.x:8000, regardless I modified the serve.py as is showed here https://github.com/CTFd/CTFd/issues/1108

![image](https://user-images.githubusercontent.com/23213610/74027012-9d8f4600-49a7-11ea-9f8e-4b850164e5ac.png)

**Comment by ColdHeat** [comment]
If CTFd is listening on 0.0.0.0 then the problem lies elsewhere. Maybe a firewall.

**Comment by Unaim1** [comment]
I don't have a firewall and if I put apache server or something it's working properly. Can you help me instead of saying "the problem lies eslewhere". Thanks

> If CTFd is listening on 0.0.0.0 then the problem lies elsewhere. Maybe a firewall.
