### ISSUE TITLE
All user IP are 127.0.0.1

### ISSUE THREAD

**Issue by tete2soja** [CTFd/CTFd#1230]
**Environment**:

  - CTFd Version/Commit: 2.2.3
  - Operating System: Debian
  - Web Browser and Version: Firefox 72

**What happened?**
All users IP on the website are 127.0.0.1.

**What did you expect to happen?**
Real user IP instead of the localhost. I guess, Flask don't use the X-Forwaded-For headers to read the external address IP.

So, I wonder how to correct pass the client IP to nginx or Flask to show it back on CTFd user page.

Thanks in advance.

**Comment by jimender2** [comment]
Are you reverse proxying the server at all?

**Comment by tete2soja** [comment]
I'm using this as nginx configuration:

```
location / {
		proxy_pass http://127.0.0.1:5000;
		proxy_set_header X-Real-IP  $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
}
```

**Comment by tete2soja** [comment]
Ok, nginx didn't reload correctly last time. Solved buy using the same conf. Thanks!
