### ISSUE TITLE
[Question] How do I call ezq.js functions after upgrade?

### ISSUE THREAD

**Issue by frankli0324** [CTFd/CTFd#1236]
ezQuery/ ezAlert

originally the ezq.js functions can be accessed easily in challenge "view.js"s added by plugins. Now It's hidden in the webpack. Is there any possibility I can call them?

**Comment by frankli0324** [comment]
Or could you please place them in `CTFd.lib` ?

**Comment by ColdHeat** [comment]
Closed in #1241
