### ISSUE TITLE
unable to edit hint

### ISSUE THREAD

**Issue by frankli0324** [CTFd/CTFd#1242]
**Environment**:

  - CTFd Version/Commit: latest (354954b)
  - Operating System: Docker/python3 serve.py/unrelated
  - Web Browser and Version: Chrome/Firefox/unrelated

**What happened?**

![image](https://user-images.githubusercontent.com/20221896/74612365-b7672080-513f-11ea-9d9e-4f5da6ed4fc7.png)

**Any associated stack traces or error logs**

though in https://github.com/CTFd/CTFd/blob/354954bbe90cf583f05d272b9ce0437c1c9ad24f/CTFd/themes/admin/assets/js/challenges/hints.js#L116 , `editHint()` is implemented correctly, it appears to be that there's a `_readOnlyError` in https://github.com/CTFd/CTFd/blob/354954bbe90cf583f05d272b9ce0437c1c9ad24f/CTFd/themes/admin/static/js/pages/challenge.dev.js#L189 somehow, didn't know much about the frontend stuff

`npm i; npm run build` **didn't** solve the issue

btw, I suggest that npm commands be written into the Dockerfile

**Comment by frankli0324** [comment]
oh, the `editHint` func was **not** implemented correctly
you assigned to a `const`
![image](https://user-images.githubusercontent.com/20221896/74612627-fa29f800-5141-11ea-8e1f-c7785d86fa48.png)

**Comment by frankli0324** [comment]
still, npm run build should go into the Dockerfile, and static folders should be removed from the repo. otherwise once I edit something in assets/ , build them, git pull, conflicts.

**Comment by ColdHeat** [comment]
CTFd is deployed in a variety of ways. Removing static folders is unlikely to happen until there's a standardized deployment setup which is targeted for 3.x.

**Comment by ColdHeat** [comment]
Closed in #1247
