### ISSUE TITLE
Unicode in filenames

### ISSUE THREAD

**Issue by rickest-rick** [CTFd/CTFd#1244]
**Environment**:
CTFd Version/Commit: Version 2.2.3 354954bbe90cf583f05d272b9ce0437c1c9ad24f

**What happened?**
Attempting to upload a file with a filename of "😆" returns a 500 response.

If I attempt to do this through the UI, it just hangs.  If I change the filename to  "😆.lol", it changes the filename to just "lol" with no error.

What I think is happening is unicode characters are being stripped off and it's attempting to create a file with an empty filename.

**What did you expect to happen?**
A file named "😆".

**How to reproduce your issue**
`python3 -c "with open(chr(128518), 'w') as fh: fh.write('foo')"`
Try to upload that while running `docker logs -f ctfd_ctfd_1`

**Any associated stack traces or error logs**
```[2020-02-17 03:50:40,157] ERROR in app: Exception on /api/v1/files [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 105, in admins_only_wrapper
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/api/v1/files.py", line 34, in post
    obj = uploads.upload_file(file=f, **request.form.to_dict())
  File "/opt/CTFd/CTFd/utils/uploads/__init__.py", line 31, in upload_file
    location = uploader.upload(file_obj=file_obj, filename=file_obj.filename)
  File "/opt/CTFd/CTFd/utils/uploads/uploaders.py", line 57, in upload
    return self.store(file_obj, file_path)
  File "/opt/CTFd/CTFd/utils/uploads/uploaders.py", line 44, in store
    with open(location, "wb") as dst:
IsADirectoryError: [Errno 21] Is a directory: '/var/uploads/0d2e2529c2c7b4a6c0dada94eecdf732/'```

**Comment by ColdHeat** [comment]
Can you submit a PR to fix this since you seem to have a working test case?

**Comment by ColdHeat** [comment]
Just sharing some information about this from the PR: https://github.com/CTFd/CTFd/pull/1246#issuecomment-586822454

Likely intended behavior from Werkzeug.

**Comment by rickest-rick** [comment]
It says in the comments of Werkzeug util.py that secure_filename is to return an ascii-only filename. 

> Pass it a filename and it will return a secure version of it.  This
    filename can then safely be stored on a regular file system and passed
    to :func:`os.path.join`.  The filename returned is an ASCII only string
    for maximum portability.

 For the record if anyone wants to bypass this behavior, this was the solution for my very specific use case.

CTFd/CTFd/utils/uploads/uploaders.py
``` 
53         if not '😆' in filename:
54             filename = secure_filename(filename)
```

Thinking about it some more - it's probably safe to enable unicode in the filenames since only admins *should* be able to upload files.  I'm not familiar enough with CTFd to make that call though.  Something about not taking down a fence if you don't know why it was put up.
