### ISSUE TITLE
Is there a way to easily reset the scoreboard?

### ISSUE THREAD

**Issue by shawntiemann** [CTFd/CTFd#1254]
I'm trying to run multiple 'mini' CTF sessions back to back, and I need a way to preserve users and teams while resetting all team scores and submissions to zero (this button is too blunt: https://github.com/CTFd/CTFd/issues/639 ).

I thought I could use export / import to work around this, but when trying to import and reset submissions, I got an import failed error and am now getting Internal Server Errors.

**Comment by ColdHeat** [comment]
The simplest way to do this is to go into the database and TRUNCATE all of the submissions tables. Perhaps resets should allow the admin to select what they want to delete but that's probably a little more complicated to pull off.

**Comment by ColdHeat** [comment]
This is resolved with #1355 and will be available in v2.4.0.
