### ISSUE TITLE
Unable to import backups with ISO 8601 date+time based flags

### ISSUE THREAD

**Issue by TomPenrose** [CTFd/CTFd#1255]
**Environment**:

  - CTFd Version/Commit: Latest (As of 18/02/2020)
  - Operating System: Docker (Underlying OS tested on Mac and Google Cloud Run)
  - Web Browser and Version: Chrome for Mac Version 79.0.3945.130 (Official Build) (64-bit)

**What happened?**

When importing a backup into a fresh CTFd container I receive the error "ValueError('unconverted data remains: Z')"

After a bit of testing, the 'Z' is part of one of my flags in flag.json. Unzipping the backup, removing the Z and re-zipping allows the backup to be imported correctly.

Full flag in broken backup was: 1996-02-20T05:00:00Z

**What did you expect to happen?**

Backup should be imported correctly

**How to reproduce your issue**

Create a CTF game with "1996-02-20T05:00:00Z" as a flag (no quotes). Export this backup, then try and re-import it

**Any associated stack traces or error logs**

"ValueError('unconverted data remains: Z')" as a browser popup

**Comment by ColdHeat** [comment]
This is related to #1174. Are you using SQLite or MySQL as your database backend?

**Comment by ColdHeat** [comment]
Considering this appears to be more common than I thought I'll re-evaluate merging that fix in.

**Comment by TomPenrose** [comment]
Hey @ColdHeat Appreciate the quick reply.

Apologies, I did not see the PR to fix this issue.

I am using the standard DockerFile in the repo, which looks to use SQLite

Let me know if you'd anymore information, or want me to test anything

**Comment by ColdHeat** [comment]
You'd probably be better off using docker-compose which will give you a MySQL database to avoid this issue.
