### ISSUE TITLE
Version changes by importing backup to version on which it was generated

### ISSUE THREAD

**Issue by HydroSausager** [CTFd/CTFd#1256]
- CTFd Version/Commit: 2.3.1
  - Operating System: Docker, latest(20.02.20)

The displaying version changes when importing a backup to the version on which this backup was generated, so maybe it can be changed to any version by changing current variable in backup. 

For example:
1)I exported backup from version 2.1.5
2)Started new docker container based on ctfd/ctfd:latest (2.3.1)
3)Imprted backup throught browser
4)Now version is 2.1.5 (saw only in admin mode) (before import version is 2.3.1)
![Screenshot_2020-02-20-16-01-20-747_com android chrome](https://user-images.githubusercontent.com/45184745/74935984-56b73c80-53fa-11ea-82e2-689b7798d664.jpg)

**Comment by ColdHeat** [comment]
Interesting, thanks for reporting. This is probably because the version is being loaded from config instead of directly from the CTFd app.

**Comment by jaco-za** [comment]
Had the same experience now with versions changing when importing backups using CTFd with Docker.

**Comment by ColdHeat** [comment]
This should be closed with 0cfbf9020140ba4a46ac984f416bfe0aaf9b9102. Fixed by just pinning the config properly at the end of the import process.
