### ISSUE TITLE
Can't update hint on a challenge

### ISSUE THREAD

**Issue by pmcstjean** [CTFd/CTFd#1258]
**Environment**:

  - CTFd Version/Commit: 2.2.3
  - Operating System: linux
  - Web Browser and Version: firefox and chrome, any version

**What happened?**
I'm trying to update hint on an existing challenge, changing text and number (cost) of points.

**What did you expect to happen?**
Receive a success or error message.

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
This was resolved in CTFd v2.3.0.
