### ISSUE TITLE
Learning theme categories collapse every time you answer a question

### ISSUE THREAD

**Issue by bndabbs** [CTFd/CTFd#1261]
**Environment**:

  - CTFd Version/Commit: 2.3.1
  - Operating System: Alpine 3.10 container
  - Web Browser and Version: Google Chrome 80

**What happened?**

When using the leaning theme, every time you answer a question in a category other then the very top one, that category collapses and reopens the top category.

**What did you expect to happen?**

The category you are answering questions in should remain open.

**How to reproduce your issue**

Install the learning theme, create more than one category of questions, answer a question in any category other than the top one.

This behavior is also seen at https://demo.ctfd.io/

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
@bndabbs thanks for reporting this. From my testing it seems like you need to have two categories open and the top most category will stay open but the other will force close.

**Comment by Oofles** [comment]
@ColdHeat - I'm testing on the same environment. It seems to always keep one of the other categories open, but force closes the category that I am answering questions in. For the most part, it seems to keep the previous category open, so maybe the indexing is off?

**Comment by ColdHeat** [comment]
The code was only keeping the first category tab open instead of tracking all open tabs.

You should receive/have received an email with the updated plugin shortly. Email support@ctfd.io if you need anything else.
