### ISSUE TITLE
Hints on Multiple Choice Questions don't open

### ISSUE THREAD

**Issue by Oofles** [CTFd/CTFd#1262]
**Environment**:

  - CTFd Version/Commit: 2.3.1
  - Operating System: Alpine 3.10 Container
  - Web Browser and Version: Google Chrome 79

**What happened?**

On multiple choice questions, the hints do not open when attempting to open a hint. They still work for standard questions, but when you click the "View Hint" button, nothing happens.

**What did you expect to happen?**

You should be able to use hints on multiple choice questions.

**How to reproduce your issue**

This behavior can be replicated and seen at https://demo.ctfd.io/

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Thanks for reporting this. An update to the plugin will be released shortly.

**Comment by ColdHeat** [comment]
@Oofles you should receive/have received an email with the updated plugin. Email support@ctfd.io if you need anything else.
