### ISSUE TITLE
Add email blacklist

### ISSUE THREAD

**Issue by jimender2** [CTFd/CTFd#1264]
Currently exists an account domain whitelist.  There should be a feature to allow you to blacklist certain domains.

**Comment by ColdHeat** [comment]
I don't really see the benefit here. What prevents someone from using another non-banned email address?

**Comment by jimender2** [comment]
For example, if I have a lot of spam accounts being created on one email domain, I might wish to block it.  Or if I dont want gmail addresses to sign up, that might be another option.

**Comment by ColdHeat** [comment]
That's a game of whack a mole that would be beyond CTFd's scope. You can make a plugin for it or achieve it with your mail provider through validations or something like that.
