### ISSUE TITLE
Toast notification timeout

### ISSUE THREAD

**Issue by jimender2** [CTFd/CTFd#1265]
When using toast notifications to save files and do other configuration, the toast notifications should go away after 30 or 45 seconds.

When using them for notifications from the admin panel, they should have an area to specify how long they are shown for on screen.

**Comment by ColdHeat** [comment]
There should actually be a timeout here. Maybe it's not working.

**Comment by ColdHeat** [comment]
From testing a progress bar out, it's very distracting so I'm not going to add it in.
