### ISSUE TITLE
Refresh challenge visibility on page update

### ISSUE THREAD

**Issue by jimender2** [CTFd/CTFd#1267]
In the admin panel, when I manually update a challenges status from hidden to visible, and click update, the little bar that says if it is hidden or visible at the top of the page does not update until I refresh the page.

It is annoying in the fact that it is showing unreliable data.  I was working on a challenge that I released, then came back to it (left the computer to go look at something and came back), and saw that it was not released. Started changing some things I saw wrong with it and heard from a team that they were having issues with it.  Look again and it was released but the red banner saying hidden was still visible on my screen. Refreshed the page and it was green.

**Comment by ColdHeat** [comment]
This is annoying to fix without having a proper front end framework in place. You're welcome to write a PR to fix it.

**Comment by ColdHeat** [comment]
I suppose since this is the one case you can get away with updating the information on challenge update from the HTTP response values. I would much rather do something ala setState in React but that's probably quite a ways away.

**Comment by ColdHeat** [comment]
Closed with #1331 in the `2.4.0-dev` branch
