### ISSUE TITLE
127.0.0.1 in confirmation emails instead of correct URL

### ISSUE THREAD

**Issue by nadrojisk** [CTFd/CTFd#1288]
**Environment**:

  - CTFd Version/Commit: 2.3.1
  - Operating System: Ubuntu
  - Web Browser and Version: Multiple Browsers

**What happened?**

When receiving an account verification email the URL for the confirmation link starts with 127.0.0.1.

**What did you expect to happen?**

When receiving an account verification email the URL for the confirmation link should start with the domain name of the server.

**How to reproduce your issue**

Use CTFd within docker. I'm not sure if this is on my end or CTFd's. Emails were working before the recent changes to allow more customization.

**Any associated stack traces or error logs**

Similar Issue: https://github.com/CTFd/CTFd/issues/588

**Comment by frankli0324** [comment]
more env details plz? do you use a reverse proxy?

**Comment by nadrojisk** [comment]
Yes, we are using NGINX to handle HTTPS traffic which then points it to the CFTd docker instance on 8000. If that’s the issue where should I change the variable in the configuration?

**Comment by frankli0324** [comment]
in docker-compose.yml:
```yml
environments:
    ...
    - REVERSE_PROXY=true <-add this
```
in nginx config:
```conf
location / {
    ...
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;
}
```
for details:
see: https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/#werkzeug.middleware.proxy_fix.ProxyFix

**Comment by nadrojisk** [comment]
Gotcha will try that and let you know if it fixes it.

**Comment by nadrojisk** [comment]
```
 server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ctf.auburn.edu;
    location / {
        proxy_pass http://127.0.0.1:8000/;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        #proxy_set_header X-Forwarded-Host $host;
        #proxy_set_header X-Forwarded-Port $server_port;
    }

    ssl_certificate /etc/letsencrypt/live/ctf.auburn.edu/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ctf.auburn.edu/privkey.pem; # managed by Certbot
}
```
This is in our NGINX config file. We are still getting the 127.0.0.1:8000 in the URL though.

**Comment by frankli0324** [comment]
you need to set the host which you commented out
#proxy_set_header X-Forwarded-Host $host;

**Comment by frankli0324** [comment]
any news? @nadrojisk

**Comment by nadrojisk** [comment]
@frankli0324 Yes, we got it working thank you! Only thing is the confirmation email uses http instead of https for some reason?

We added `REVERSE_PROXY = true` to the docker-compose.yml

And this to the NGINX config file.
```
    location / {
        proxy_pass http://127.0.0.1:8000/;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header Host $host
        #proxy_set_header X-Forwarded-Port $server_port;
    }
```
