### ISSUE TITLE
Issue with parsing backtick ( ` ) characters from juice-shop 

### ISSUE THREAD

**Issue by bhamill638** [CTFd/CTFd#1293]
**Environment**:

  - CTFd Version/Commit: Latest Docker Image (b658b641144e if that's the right refrerence)
  - Operating System: Mac OS Mojave 10.14.6
  - Web Browser and Version: Firefox Developer Edition 75.0b4

It looks like there's an issue with Juice Shop challenges containing backticks (`). I think the markdown JavaScript is parsing them and translating them into HTML ```<code>``` blocks.

This causes the following challenge for DOM XSS:

```Perform a <i>DOM</i> XSS attack with <code>&lt;iframe src="javascript:alert(`xss`)"&gt;</code>.```

To render as:

```Perform a <i>DOM</i> XSS attack with <code>&lt;iframe src="javascript:alert(<code>xss</code>)"&gt;</code>.```

Here are two screenshots demonstrating the issue:
<img width="499" alt="Screenshot 2020-03-21 at 19 52 19" src="https://user-images.githubusercontent.com/29688856/77235464-c6614880-6bad-11ea-951c-e5851e3d4d5e.png">

<img width="260" alt="Screenshot 2020-03-21 at 19 52 31" src="https://user-images.githubusercontent.com/29688856/77235467-c95c3900-6bad-11ea-9e9d-852dc1f1220d.png">

This issue means that if you spin up CTFd with [juice-shop challenges](https://github.com/bkimminich/juice-shop/blob/master/data/static/challenges.yml), at present 8 of them will be displayed incorrectly and copy and pasting the challenge payload will not cause a Juice Shop instance running in CTF mode to output the 'challenge complete' message and solution key.

I believe that the issue arises from the "markdown-it" library utilised by CTFd, particularly the [backtick parsing function](https://github.com/markdown-it/markdown-it/blob/c36309ef1c22ef002680dab767c6b157ff54711e/lib/rules_inline/backticks.js).

A workaround is for users to edit the challenges that contain backticks and escape them with backslashes via the admin interface.
If anyone is using the juice-shop-ctf CLI then I'm assuming you could apply the backup zip to the CTFd instance, modify the challenges and then export a backup zip to be used in the future. (Have not tested this yet).

If any further details are needed let me know!

**Comment by ColdHeat** [comment]
This sounds like an issue in markdown-it as you mentioned but also couldn't the juice shop CLI generate escaped backticks?

**Comment by bhamill638** [comment]
So the juice-shop CLI grabs it's challenge details from wherever you point it (defaul is the [juice shop heroku app](juice-shop.herokuapp.com/)).
Basically to make the CLI escape backticks I think the actual Juice Shop repo would need to be updated.

That then brings the question, should an API escape characters based on how it may be rendered?

I haven't fully investigated the CTFd code yet but could the platform possibly escape all backticks when loading the challenges? This would then prevent this issue if Facebook CTF or RootTheBox challenges come with backticks included.

**Comment by ColdHeat** [comment]
Other markdown parsers will likely have the exact same issue here. 

CommonMark:
https://spec.commonmark.org/dingus/

![image](https://user-images.githubusercontent.com/166333/77348751-5fa87000-6d10-11ea-895c-5b7161e2496d.png)

I would probably recommend that this be resolved at the CLI or repo level with ```javascript:alert(&#x60;xss&#x60;)``` which should render properly in HTML or markdown

HTML:
https://jsfiddle.net/bn97L6mp/

Markdown:
![image](https://user-images.githubusercontent.com/166333/77349165-fb39e080-6d10-11ea-8cb8-a65b565fd55f.png)

cc @bkimminich
