### ISSUE TITLE
unlocks api does not check already unlocked hints 

### ISSUE THREAD

**Issue by GaspareG** [CTFd/CTFd#1301]
There is not check in the unlocks api for already unlocked hints in the file [unlocks.py](https://github.com/CTFd/CTFd/blob/master/CTFd/api/v1/unlocks.py)

It is possible to unlock multiple times the same hint by just calling the api.

**Comment by ColdHeat** [comment]
Hmm how did you identify this issue? This wouldn't normally show up during usage because the hint endpoints are always hit before the unlock endpoints.
