### ISSUE TITLE
log rotation does not works

### ISSUE THREAD

**Issue by GaspareG** [CTFd/CTFd#1302]
In the file https://github.com/CTFd/CTFd/blob/master/CTFd/utils/initialization/__init__.py#L107
the log handlers `logging.handlers.RotatingFileHandler` are not created with the right parameters (see [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler)) because _if either of maxBytes or backupCount is zero, rollover never occurs_ (`backupCount` parameter is missing)

**Comment by ColdHeat** [comment]
Related to #844. 

Thanks for pointing this out I suspected there was an issue with rotation. Do you have any suggestions with regards to what `backupCount` should be?
