### ISSUE TITLE
Kubernetes replicas >1, 403

### ISSUE THREAD

**Issue by MatteoManzoni** [CTFd/CTFd#1303]
I will host a quite large event in my company so I decided to deploy CTFd in our kubernetes cluster but I'm stuck with this problem: I cannot run any number replica (I'm going to use HPA during the event) >1. 
In the past I also deployed other flask app with more success in the same environment.
I followed the deployment guide, in particular [Secretkey for multi-server deployment](https://docs.ctfd.io/en/latest/configuration.html#secret-key) & [Reverse proxy](https://docs.ctfd.io/en/latest/configuration.html#reverse-proxy)

I confirm that running a single replica doesn't presents this problem.

-------

**Environment**:
  - CTFd Version/Commit: docker :latest
  - Operating System: Kubernetes 1.18 on ubuntu 18.04
  - Web Browser and Version: Chrome 83.0.4100.3, Safari 13.1, Firefox 75.0b12
  - redis cache on the same pod of ctfd
  - mysql 5.7

**What happened?**
During the web setup phase after I press the last submit I receive a 403 error, the culprit is a POST to /login.

**What did you expect to happen?**
Setup completed and CTFd up and running.

**How to reproduce your issue**
Set the redacted params and run the attached manifest on kubernetes.

**Any associated stack traces or error logs**

"POST /login HTTP/1.1" 403 4807 "https://REDACTED_event-url-to-ctfd/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4100.3 Safari/537.36"

[ctfd-example-manifest.txt](https://github.com/CTFd/CTFd/files/4431245/ctfd-example-manifest.txt)

**Comment by ColdHeat** [comment]
In general a 403 means a CSRF nonce problem. Are you sure that all CTFd instances are communicating with the same Redis instance? Another issue I've seen had to do with a bug with Chrome inspector preventing the sending of SameSite cookies.

**Comment by MatteoManzoni** [comment]
I recicled an old deployment with a sidecar redis, so no, every istance was connecting to a standalone redis, hence the problem. Now I'm using a stateful-set based redis cluster but flask caching is not cluster aware (redis.exceptions.ResponseError: MOVED)

**Comment by MatteoManzoni** [comment]
I confirm that with a single, standalone instance of redis everything is working fine
