### ISSUE TITLE
Personal information display function

### ISSUE THREAD

**Issue by DuanNengxin** [CTFd/CTFd#1305]
**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**
When you set the user of the game to private, and then you log in with a normal account to view the account information of another user;
**What did you expect to happen?**
You can't see other people's information
**How to reproduce your issue**

**Any associated stack traces or error logs**
so line 58 of the users.py file has some logical problems , This is my thinking, I do n’t know if I understand it correctly, I look forward to your reply, thank you

**Comment by ColdHeat** [comment]
I have no idea what the issue is here. Please provide more details about the issue.

**Comment by DuanNengxin** [comment]
When the admin user sets the competition user attribute to private, ordinary users can still view the information of other users when they log in, so I think the function check_account_visibility used in line 58 of the users.py module is only to verify whether the user is logged in, and does not verify the viewed user. Is it the same as the logged-in user?

**Comment by ColdHeat** [comment]
Okay I see the concern here. This is behaving as expected. Private means that only logged in users should be able to see accounts. The default (Public) means that accounts are freely accessible. 

If anything the subtext documentation could be better because it doesn't really cover the three settings. 

Currently:
> Control whether accounts (users & teams) are shown to everyone or only to admins 

Should be:
> Control whether accounts (users & teams) are shown to everyone, only to authenticated users, or only to admins

**Comment by DuanNengxin** [comment]
I got it,think you your reply
