### ISSUE TITLE
Questions about optimizing Dockerfile play

### ISSUE THREAD

**Issue by 99Kies** [CTFd/CTFd#1313]
## optimize Dockerfile, make the container lighter, mainly by removing PIP and apk download file cache to achieve a goal

**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**

**What did you expect to happen?**

Let the container lighter!

**How to reproduce your issue**

**Any associated stack traces or error logs**
-----------------
I feel sorry about my English

**Comment by ColdHeat** [comment]
Closed in #1312
