### ISSUE TITLE
Feature request: Optional styles dict for challenge pages

### ISSUE THREAD

**Issue by Gerrit0** [CTFd/CTFd#1314]
When developing more complicated user interfaces with a plugin, chances are some CSS will be required.

Right now, the best way to include said CSS seems to be including a `<style>` tag in the template file. While this works, it would be nice to be able to specify a `styles` dict on the challenge class similar to templates. This stylesheet would be added to the page in the same way as the templates/scripts already are (well, as the templates are, the scripts don't have a cachebusting parameter added to their URL, which gets in the way sometimes)

```python
class MyChallenge(BaseChallenge):
    id = "test2"
    name = "test2"
    templates = {
        "create": "/plugins/test_challenge/assets/create.html",
        "update": "/plugins/test_challenge/assets/update.html",
        "view": "/plugins/test_challenge/assets/view.html",
    }
    scripts = {
        "create": "/plugins/test_challenge/assets/create.js",
        "update": "/plugins/test_challenge/assets/update.js",
        "view": "/plugins/test_challenge/assets/view.js",
    }
    styles = {
        "create": "/plugins/test_challenge/assets/create.css",
    }

```

**Comment by ColdHeat** [comment]
I understand where this is coming from but I'm not sure scripts being defined in the Python code was a great idea either.

I'll leave this issue open for tracking but I'm trying to see how a front end in Vue or React would look like.

**Comment by Gerrit0** [comment]
That makes sense, I've been looking for an excuse to use Vue somewhere to learn it...
