### ISSUE TITLE
API searching, API pagination

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1318]
The API needs better searching capability and pagination capability. Somewhat related to #1165

I like the following structure for a request and response:

```
/api/v1/item?page=1&per_page=100&q=search&field=table_column

{
    "meta": {
        {
            "pagination": {
                "page": q.page "next": q.next_num "prev": q.prev_num "pages": q.pages "limit": q.per_page "total": q.total,
            }
        }
    },
    "data": []
}
```

**Comment by frankli0324** [comment]
is hiding APIs behind a unified decorators a good idea?

**Comment by ColdHeat** [comment]
Are you referring to #1480 or are you suggesting creating a new decorator for wrapping responses so that they search and paginate? 

I'm not sure if it makes sense because it's difficult to validate the provided data. #1480 has a validation strategy but it doesn't account for user permissions.

**Comment by frankli0324** [comment]
> Are you referring to #1480 or are you suggesting creating a new decorator

the latter
yes... seems hard when wrapping response data
how about wrapping database queries?

**Comment by frankli0324** [comment]
the latter
how about wrapping database queries?
anyway, I suggest tidying up existing API designs before adding pagination...

**Comment by ColdHeat** [comment]
See #1498 for potential implementation. If you're not happy with how that looks you're free to make a PR. 

The API works fairly well and has mostly covered most of the usages that I've needed it for. Pagination is a little tricky so this may be postponed but is still a goal.

**Comment by ColdHeat** [comment]
I think this is basically done. Changing too many endpoints isn't worth it in v1. I'm going to consider the structure of the API frozen for now barring documentation or usability improvements.
