### ISSUE TITLE
Plugins 'Config.json' parser only set up for one URL.

### ISSUE THREAD

**Issue by offsecginger** [CTFd/CTFd#1370]
**Environment**:

  - CTFd Version/Commit: 2.3.3
  - Operating System: Windows/Linux
  - Web Browser and Version: Chrome

**What happened?**
The config.json file is used for adding URLs to the Admin section of the CTFd instance based on plugin requirements.
The current code that parses it:
```
def get_configurable_plugins():
    Plugin = namedtuple("Plugin", ["name", "route"])

    plugins_path = os.path.join(app.root_path, "plugins")
    plugin_directories = os.listdir(plugins_path)

    plugins = []

    for dir in plugin_directories:
        if os.path.isfile(os.path.join(plugins_path, dir, "config.json")):
            path = os.path.join(plugins_path, dir, "config.json")
            with open(path) as f:
                plugin_json_data = json.loads(f.read())
                p = Plugin(
                    name=plugin_json_data.get("name"),
                    route=plugin_json_data.get("route"),
                )
                plugins.append(p)
        elif os.path.isfile(os.path.join(plugins_path, dir, "config.html")):
            p = Plugin(name=dir, route="/admin/plugins/{}".format(dir))
            plugins.append(p)

    return plugins
```
is not configured to handle multiple entries.

**Comment by offsecginger** [comment]
Solution:
```
def get_configurable_plugins():
    Plugin = namedtuple("Plugin", ["name", "route"])

    plugins_path = os.path.join(app.root_path, "plugins")
    plugin_directories = os.listdir(plugins_path)

    plugins = []

    for dir in plugin_directories:
        if os.path.isfile(os.path.join(plugins_path, dir, "config.json")):
            path = os.path.join(plugins_path, dir, "config.json")
            with open(path) as f:
                plugin_json_data = json.loads(f.read())
                for d in plugin_json_data:
                    p = Plugin(
                        name=d.get("name"),
                        route=d.get("route"),
                    )
                    plugins.append(p)
        elif os.path.isfile(os.path.join(plugins_path, dir, "config.html")):
            p = Plugin(name=dir, route="/admin/plugins/{}".format(dir))
            plugins.append(p)

    return plugins
```
This requires the config.json file to always be a list. So a Sample Config.json file would look like this:

```
[
    {
        "name" : "Config",
        "route" : "/path/to/config"
    }
]
```

**Comment by ColdHeat** [comment]
Can you leverage the `register_admin_plugin_menu_bar` function? I don't see why config.json is lacking here since you can add more pages in the plugin itself and also adding more plugins each with their own config.json.

**Comment by offsecginger** [comment]
register_admin_plugin_menu_bar adds a root menu item on the admin menu. I wanted a new entry under Plugins.

**Comment by offsecginger** [comment]
To add to this:
![image](https://user-images.githubusercontent.com/1323154/80751526-f0385400-8af7-11ea-978f-355e64fde7ee.png)
This is my intended goal with the modification above.
![image](https://user-images.githubusercontent.com/1323154/80751560-047c5100-8af8-11ea-8ffe-e9f38a020054.png)
![image](https://user-images.githubusercontent.com/1323154/80751575-09d99b80-8af8-11ea-99c0-dbbaf1931a44.png)
