### ISSUE TITLE
Wrong method is used to check for request data in user creation API endpoint

### ISSUE THREAD

**Issue by jbrinksma** [CTFd/CTFd#1398]
CTFd version:  2.4.2

The following line uses the wrong method on the `flask.Request` instance, causing user creation e-mails to never be sent out:
https://github.com/CTFd/CTFd/blob/1a57a33fe712d3b449b9075b7587012f56ceb38f/CTFd/api/v1/users.py#L59

From the [flask documentation](https://flask.palletsprojects.com/en/1.1.x/api/#flask.request) about `request`: 
```
 property args

    The parsed URL parameters (the part in the URL after the question mark).
```

This causes `request.args` to always be an empty `ImmutableMultiDict` here which means the `if` statement will never be true, and thus the creation e-mail will never be sent either.

Instead we can use the `req` variable to access `notify` just like you did inside the statement to access the `password`:

`if req.get("notify"):`

**Comment by ColdHeat** [comment]
This is explicitly looking for the notify parameter as a GET parameter. If `req` is used it will only get the data from the POST'ed JSON data. Perhaps the issue is in JS?

**Comment by jbrinksma** [comment]
Maybe I am missing something here, but why you would want to check the URL parameters in this specific method (as it is for POST requests)?

JS just bundles all form data from the create user page (including `"notifiy"`) as JSON, and then sends it out as the body of a POST request to the before mentioned `api/v1/users` endpoint as I would expect:
https://github.com/CTFd/CTFd/blob/1a57a33fe712d3b449b9075b7587012f56ceb38f/CTFd/themes/admin/assets/js/pages/user.js#L8-L20

**Comment by ColdHeat** [comment]
Why would it be considered part of the POST body if it isn't actually part of the User model?

**Comment by jbrinksma** [comment]
Ah right, I didn't even think about the User model creation before the `if` statement. That is not very good.

I am kind of new to the conventions of handling these type of API requests, however. Personally I would set a `notify` variable to `True` or `False`, and then make sure the `"notify"` POST parameter is deleted from `request` before the new User instance is created.

Adding a URL parameter to a POST request in general just seems weird to me, but if that is what's normal in a situation like this then I guess that works too. Let me know :)
