### ISSUE TITLE
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.(ocuured at CTFd on AWS ALB)

### ISSUE THREAD

**Issue by 0410akihiro** [CTFd/CTFd#1407]
My CTFd system consisit with following three components.

1. One ALB for Load Balance for 2 EC2 
2. Some EC2s for CTFd web, at same target group. The number of this EC2 will change regarding to work-load.
3. One RDS  (mysql) for CTFd DB, this server recieved DB request from some EC2s.

When only one EC2 works , CTFd works good.
But when more than 2 EC2s work, user challenge to log-in to CTFd, DB error happend with following message.

"You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."

Someone helop me?

**Comment by 0410akihiro** [comment]
DB error message

2020-05-14T03:13:30.334593Z 825 [Note] Aborted connection 825 to db: 'ctfd' user: 'admin' host: '172.16.1.172' (Got an error reading communication packets)

**Comment by hugoprudente** [comment]
Hi @0410akihiro,

I have a similar setup and I don't have issues, but I have the Redis cache layer that is responsible for keep the authorization and authentication consistent between the 2+ instances.

Without it if you hit a different target with ALB the authentication token is not created and you need to do it again. 

Can you check if the cache will work for you?

**Comment by 0410akihiro** [comment]
Hi @hugoprudente
Great Thanks for your very useful comment.

I do NOT use cache server, so each EC2(web server) have file cache system following directory.

   CTFd/.data/filesystem_cache/

Is it not recommended structure?
You created one Redis server and set the environment value 'REDIS_URL' ?

And my additional information .  
Eve if many EC2 work , 
・Access to each EC2 ip address directly ---> DB Error NOT occurred.
・Access to ALB or NLB --->　DB Error occurred.

**Comment by 0410akihiro** [comment]
I built Redis server, and
-Set the value "REDIS_URL" on each EC2 config.py.
-Deleted all cache files (CTFd/.data/filesystem_cache/***) . 
-Again typed command "sh prepare.sh" and launch the server (python serve.py)

But same phenomenon happen,
Access to each EC2 directly , it works well. 
But access to ALB , same DB error occurred.

When only one EC2 works, ALB works as well as access to IP address directly.

I changed following point from default config.py.
1. DATABASE_URL = "mysql+pymysql://<user>:<pass>@<RDS endpoint>/ctfd
2. REDIS_URL = "redis://<REDIS endpoint>:6379"

you have any additional config points ?

Thanks for your kindness.

**Comment by hugoprudente** [comment]
So in the case of SystemCache if you have 2 EC2 instances, the folder below will be created individually in each instance.

> CTFd/.data/filesystem_cache/

And they will not be shared with the others instances.

What is the error exactly that you see when you access your application?  Can you provide som outputs like `curl -I url` from the EC2 IP and the ALB load balancer?

Can you also provide the logs from the application itself to see if it's receiving the requests?

If the ALB request is not reaching the instance, can you check if the security group from the instance is allowing the security group of the load balancer and the security group of the load balancer is allowing the ports required 80/443.

**Comment by 0410akihiro** [comment]
Hi @hugoprudente 
Thanks your comments.

I understood issue of systemChache. So I built the Redis server and config following two points at config.py.
- REDIS_URL
- SECRET_KEY
Only when all EC2 has same SECRET_KEY , It works WELL so far!!!!
 
Did you set the same SECRET_KEY at yoru each EC2 instances ?



>What is the error exactly that you see when you access your application? Can you provide som outputs like curl -I url from the EC2 IP and the ALB load balancer?

OK, but my log information is poor following. 
I paste log about DB error (do not care about each log's time stamp)
--------------------------------------
- mfctf.log on EC2
172.16.1.178 - - [17/May/2020 00:36:56] "POST /login?next=%2Fchallenges%3F HTTP/1.1" 403 

- HTTP Response Header on ClientPC (wireshark)
HTTP/1.1 403 FORBIDDEN
Date: Sun, 17 May 2020 00:40:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 3799
Connection: keep-alive
Server: Werkzeug/0.16.0 Python/2.7.16

- error/mysql-error-running.log on RDS 
2020-05-17T01:09:32.270827Z 132 [Note] Aborted connection 132 to db: 'ctfd' user: 'admin' host: '172.16.1.88' (Got timeout reading communication packets)
--------------------------------------

Thank you for your very kindness.

**Comment by hugoprudente** [comment]
Hey @0410akihiro 

It looks like the problem is not on the is not on the ALB directly it's with the connection with the database.

As it has being a while, were you able to resolve it?

**Comment by 0410akihiro** [comment]
Thank you @hugoprudente 
I solved this problem using radis instead of local cache, and using same secret key through all ec2 (web).
thank your comments. 
closed
