### ISSUE TITLE
"Duplicate column name 'captain_id'" on docker-compose up

### ISSUE THREAD

**Issue by RezaSi** [CTFd/CTFd#1429]
**Environment**:

  - CTFd Version/Commit: last version
  - Operating System: ubuntu 16.04 and ubuntu 18.04

**What happened?**
i just use docker-compose up on last version, but it not work and got this 

> sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'captain_id'")

**What did you expect to happen?**
just work fine :D
**How to reproduce your issue**
run docker-compose up :)
**Any associated stack traces or error logs**
> ctfd_1   | Waiting for db: to be ready
ctfd_1   | db is ready
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | pymysql.err.InternalError: (1060, "Duplicate column name 'captain_id'")
ctfd_1   | 
ctfd_1   | The above exception was the direct cause of the following exception:
ctfd_1   | 
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "manage.py", line 9, in <module>
ctfd_1   |     app = create_app()
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 200, in create_app
ctfd_1   |     upgrade()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
ctfd_1   |     f(*args, **kwargs)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
ctfd_1   |     command.upgrade(config, revision, sql=sql, tag=tag)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
ctfd_1   |     script.run_env()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
ctfd_1   |     util.load_python_file(self.dir, "env.py")
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
ctfd_1   |     module = load_module_py(module_id, path)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
ctfd_1   |     spec.loader.exec_module(module)
ctfd_1   |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
ctfd_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ctfd_1   |   File "migrations/env.py", line 99, in <module>
ctfd_1   |     run_migrations_online()
ctfd_1   |   File "migrations/env.py", line 91, in run_migrations_online
ctfd_1   |     context.run_migrations()
ctfd_1   |   File "<string>", line 8, in run_migrations
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
ctfd_1   |     self.get_context().run_migrations(**kw)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
ctfd_1   |     step.migration_fn(**kw)
ctfd_1   |   File "/opt/CTFd/migrations/versions/b5551cd26764_add_captain_column_to_teams.py", line 27, in upgrade
ctfd_1   |     op.add_column("teams", sa.Column("captain_id", sa.Integer(), nullable=True))
ctfd_1   |   File "<string>", line 8, in add_column
ctfd_1   |   File "<string>", line 3, in add_column
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/operations/ops.py", line 1929, in add_column
ctfd_1   |     return operations.invoke(op)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 374, in invoke
ctfd_1   |     return fn(self, operation)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 132, in add_column
ctfd_1   |     operations.impl.add_column(table_name, column, schema=schema, **kw)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 237, in add_column
ctfd_1   |     self._exec(base.AddColumn(table_name, column, schema=schema))
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
ctfd_1   |     return conn.execute(construct, *multiparams, **params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
ctfd_1   |     return meth(self, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
ctfd_1   |     return connection._execute_ddl(self, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
ctfd_1   |     compiled,
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
ctfd_1   |     e, statement, parameters, cursor, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
ctfd_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
ctfd_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
ctfd_1   |     raise value.with_traceback(tb)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'captain_id'")
ctfd_1   | [SQL: ALTER TABLE teams ADD COLUMN captain_id INTEGER]
ctfd_1   | (Background on this error at: http://sqlalche.me/e/2j85)
ctfd_ctfd_1 exited with code 1
`

**Comment by ColdHeat** [comment]
Please see #1411 to see if it resolves your issue.

**Comment by RezaSi** [comment]
yes it works, thanks!
