### ISSUE TITLE
ctfd_1   | [SQL: ALTER TABLE teams ADD COLUMN captain_id INTEGER]

### ISSUE THREAD

**Issue by deathflash1411** [CTFd/CTFd#1434]
I've tried running using docker-compose up

same error every time and then ctfd_ctfd_1 exited with code 1

![image](https://user-images.githubusercontent.com/42869390/82682484-f2ac4a80-9c6c-11ea-9b8b-fa8f5d2db3d3.png)

**Comment by ColdHeat** [comment]
Please see if #1411 resolves your issues
