### ISSUE TITLE
Questions about csrf protection

### ISSUE THREAD

**Issue by DuanNengxin** [CTFd/CTFd#1448]
**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**
When you use your browser to open two login pages, then log in on one of the pages, and then log in to another page, 403 will appear
**What did you expect to happen?**
Can log in normally。
My solution：
After the user logs in, session ["nonce"] is not regenerated;
The code is as follows: # session ["nonce"] = generate_nonce ();
But I am not sure whether it will cause other security problems. Can you answer my doubts? Thank you
**How to reproduce your issue**
Use a browser to open 2 login pages, then log in one of them, and log in using another page
**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
This probably opens you up to some sort of issue CSRF or otherwise. A better question to think about is why is the code not working for you? Did you deploy CTFd with a proper caching mechanism like redis?

**Comment by DuanNengxin** [comment]
I use redis for caching, I don't know if there will be any problems. My task user generates another session ["nonce"] after logging in. The effect is the same as using the original one. If someone else wants to cause a CSRF attack, then the new session ["nonce"] is the same. I don't know if you have other opinions.

**Comment by ColdHeat** [comment]
I don't really understand what you're trying to do but none of this touches on how the CSRF token leaked which would be the prerequisite for pulling off a CSRF attack.
