### ISSUE TITLE
Issues possibly with frontend related to mixing up of input values

### ISSUE THREAD

**Issue by sakshamsharma** [CTFd/CTFd#145]
So I just finished with my CTF which I hosted on CTFd. Works nicely, except for a major issue which is highly variable and I don't know of a nice way to replicate this.

Scenario: We had only 5 (huge pool) teams. So we created 5 different accounts for them, along with passwords. After a while it turns out, that when we change password of one team, it actually changes the password of another team randomly as well, but only sometimes. We spent half an hour doing this, and repeatedly testing all passwords till they were finally set. I believe this had something to do with the (password change box) which pops back up after you click on the update button in the original password change box.

Beyond this, during the contest I noticed that when I set that key/flag for a new question I added, it also changed the flag of another old question to that value. Again, on updating flags, I noticed that sometimes the question info change box pops up again on pressing update once.

This might be a frontend issue, but am reporting here in case someone knows of this. Other than this, I'd love to host more CTFs on this platform :smile:

**Comment by ColdHeat** [comment]
Perhaps your database is messed up? 

You can look in the code and it should only select the first matching user from the database before changing the password.

**Comment by sakshamsharma** [comment]
So I believe that this issue is on the front-end, since I did check the
code. Also, it also happened for the flag values. Just for completeness, I
had used the default SQLite DB.

**Comment by ColdHeat** [comment]
I've never seen this so I am going to close this issue because it's almost a year old. If you see something similar to this again, just re-open or make a new issue.
