### ISSUE TITLE
Lint Docker-related files

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1458]
We should be able to lint the Dockerfile: https://github.com/hadolint/hadolint

Linting docker compose: https://stackoverflow.com/questions/29225972/validating-docker-compose-yml-file

**Comment by ColdHeat** [comment]
An alternative is https://github.com/replicatedhq/dockerfilelint

**Comment by frankli0324** [comment]
since the compose file changed less than 20 times among all commits, I think this is kind of unnecessary

**Comment by frankli0324** [comment]
hmmm... since the compose file & dockerfile each changed less than 20 times among all commits, I think this is kind of unnecessary.

**Comment by ColdHeat** [comment]
Along with Python code, Dockerfile changes are often recommended in PRs. As the primary person doing those PR reviews, linting is a beneficial process to keeping lackluster code out of the codebase.

**Comment by ColdHeat** [comment]
Closed with #1518

Would prefer to not rely on an external Github Action but it's tricky to integrate hadolint.
