### ISSUE TITLE
Can you scale CTFd horizontally?

### ISSUE THREAD

**Issue by laurrentt** [CTFd/CTFd#1489]
Hi 👋 

I'm currently running the CTFd docker image. I've configured it to use an external database, as well as Redis for caching and S3 for file storage. At this point I think the container is pretty much stateless. However, it's hard to tell without asking the developers if multiple containers could run in parallel in a load balanced setup. Is it a "supported" scenario or you wouldn't recommend it?

My exact setup:
CDN (CloudFront)
Load-Balancers (ALB)
Docker (Fargate)
Postgres (Aurora-serverless)
Redis (Elasticache)
S3

**Comment by ColdHeat** [comment]
I can't comment on your setup, but as long as the individual workers aren't sharing state and are using the same secret key then it should scale horizontally just fine.
