### ISSUE TITLE
your docker image is not work  when i increase worker count 

### ISSUE THREAD

**Issue by mahdibahramih** [CTFd/CTFd#1500]
**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**

**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by mahdibahramih** [comment]
i increase that by envirements var and directly in docker-entrypoint.sh but it not work!!!

**Comment by ColdHeat** [comment]
Refer to https://docs.ctfd.io/en/latest/deployment.html. You should probably be using docker-compose instead of directly using the Docker image if you're not familiar with how CTFd works.
