### ISSUE TITLE
solves undefined if visibility is set to hidden

### ISSUE THREAD

**Issue by publicqi** [CTFd/CTFd#1530]
**Environment**:

- CTFd Version/Commit: adc70fb320242d5e4df1a7ce2d107c0e2b8039e7
- Operating System: Ubuntu 18.04
- Web Browser and Version: Safari 13.1.1, Chrome 83.0.4103.106

**What happened?**

When _Score Visibility_ or _Account Visibility_ is not public, users cannot see challenges.

**What did you expect to happen?**

Challenges should be able to be seen and solves are hidden.

**How to reproduce your issue**

In `CTFd/api/v1/challenges.py`, line 361 to line 376, `solves` is only defined if `scores_visible() is True and accounts_visible() is True`. Yet, `solves` is referenced later in the code.

**Any associated stack traces or error logs**

<img width="747" alt="error" src="https://user-images.githubusercontent.com/56060664/86547616-1bae4380-bf6c-11ea-89ac-cd6c5db663f0.png">

**Comment by ColdHeat** [comment]
Thanks for filing this, I believe this is fixed with `solves = None` on line 377. I'll put at fix up when I get a chance.
