### ISSUE TITLE
Database column "secret" in users table.

### ISSUE THREAD

**Issue by h4ckd0tm3** [CTFd/CTFd#1535]
Hi!

My question is, if there is a purpose this column servers, otherwise I would like to use it for something.

Greetings,
h4

**Comment by ColdHeat** [comment]
It is currently a placeholder column for future features. I have a specific goal in mind but haven't had the time to implement it. As with just about any open source project, you can do whatever you want but you'll need to support it yourself.

**Comment by h4ckd0tm3** [comment]
Thank you for the quick response! All questions answered, thank you!
