### ISSUE TITLE
Challenge types missing

### ISSUE THREAD

**Issue by jensregel** [CTFd/CTFd#1543]
**Environment**:

- CTFd Version/Commit: 3.0.0a2
- Operating System: Ubuntu 18.04.4 LTS
- Web Browser and Version: Chromium 83.0.4103.61 & FF 78.0.1

**What happened?**
There are only "standard" and "dynamic" challenge types, code and multiple_choice is missing

**What did you expect to happen?**
To see all challenge types

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by h4ckd0tm3** [comment]
Code and Multiple Choice are both plugins, that are not included by default. Do you have them both installed?

**Comment by jensregel** [comment]
Ah, thanks a lot!

**Comment by YavorIvanov90** [comment]
Where is the Code plugin ? I can`t find it
