### ISSUE TITLE
Add team password reset functionality

### ISSUE THREAD

**Issue by arxenix** [CTFd/CTFd#1545]
Currently, there is no way for the team creator to reset the team password.

There should be a "forgot team password" functionality, which allows them to reset it via email.

**Comment by ColdHeat** [comment]
Admins can set a new password. I don't think I see this as a high priority issue.

If someone is willing to contribute a PR or flow for how this would work, I'll look at it more closely.

**Comment by arxenix** [comment]
I'm an organizer for UIUCTF, which is taking place this weekend. I agree it's not super high priority, but it's something that should be added. We've received ~20 team password reset requests in the past few days, and it is definitely an annoyance to manually verify team ownership and then reset their password.

**Comment by likuilin** [comment]
A simple way to achieve this is to not require the current password if a team captain wants to change the team password.

**Comment by ColdHeat** [comment]
That would expose the team password to be reset by anyone who can access the captain's account. Perhaps by hijacking their computer while they're not looking. This is of course low risk given how CTFd is structured, but still a risk. 

It's an overall reasonable idea though. Perhaps we can accept the captain's password or the team's password for password reset.

**Comment by ColdHeat** [comment]
Closed in #1598. 

Team captains can now use their own password to change the team password. Additionally I opened #1597 to track work in team join links.
