### ISSUE TITLE
Importing custom backup gets SQL IntegrityError

### ISSUE THREAD

**Issue by JohnHammond** [CTFd/CTFd#1547]
**Environment**:
Windows 10, Windows Subsystem for Linux 2 - Docker container for CTFd
```
docker run -p 8000:8000 -it ctfd/ctfd
```

- CTFd Version/Commit: CTFd Version 3,0.0a2

- Operating System: Windows 10
- Web Browser and Version: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"

**What happened?**

![image](https://user-images.githubusercontent.com/6288722/87615812-8f292100-c6e1-11ea-9f4e-eac93d70eb97.png)

Importing a new backup gets an `IntegrityError` within the database. Comparing and contrasting the JSON files that get made up into the database, I do not see any difference between the two...

Looking at the stack traces or error logs it seems to be a problem with the user that is being created.

**What did you expect to happen?**

Expected CTFd to successfully import the backup

**How to reproduce your issue**

Please feel free to try and upload this backup ZIP: 

[new.zip](https://github.com/CTFd/CTFd/files/4928802/new.zip)

**Any associated stack traces or error logs**

```
172.17.0.1 - - [16/Jul/2020:01:28:26 +0000] "GET /themes/admin/static/js/pages/configs.min.js?d=85e4d20e HTTP/1.1" 200 0 "http://localhost:8000/admin/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
Failed to disable foreign key checks. Continuing.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 8369118943a1, Initial Revision
INFO  [alembic.runtime.migration] Running upgrade 8369118943a1 -> 4e4d5a9ea000, Add type to awards
INFO  [alembic.runtime.migration] Running upgrade 4e4d5a9ea000 -> b5551cd26764, Add captain column to Teams
INFO  [alembic.runtime.migration] Running upgrade b5551cd26764 -> b295b033364d, Add ondelete cascade to foreign keys
INFO  [alembic.runtime.migration] Running upgrade b295b033364d -> 080d29b15cd3, Add Tokens table to store user access tokens
INFO  [alembic.runtime.migration] Running upgrade 080d29b15cd3 -> a03403986a32, add theme code injections to configs
INFO  [alembic.runtime.migration] Running upgrade a03403986a32 -> 1093835a1051, Add default email templates
(sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO users (oauth_id, name, password, email, type, secret, website, affiliation, country, bracket, hidden, banned, verified, team_id, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, 'a', '$bcrypt-sha256$2b,12$OIPwj1HgenZJwq1tPuvMtu$6/EiWL2tRGj/D1oFBrE1z85k6f.BGeS', 'a@a.com', 'admin', None, None, None, None, None, 1, 0, 1, True, '2020-07-16 01:27:30.427251')]
(Background on this error at: http://sqlalche.me/e/gkpj)
172.17.0.1 - - [16/Jul/2020:01:28:37 +0000] "POST /admin/import HTTP/1.1" 500 72 "http://localhost:8000/admin/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
```

**Comment by ColdHeat** [comment]
Did you make this import yourself or did CTFd generate this import? 

Because if it's the former, the issue is in your custom code.

**Comment by JohnHammond** [comment]
It is custom, I had made the import. I'll keep hunting down the problem. Thanks!

**Comment by ColdHeat** [comment]
Depending on what you're trying to do, using https://github.com/CTFd/ctfcli or the REST API on it's own could be a better approach. 

If you are adamant on building a custom import then you should look at a valid one and then diff it against your own.
