### ISSUE TITLE
Wish list: invitation code registration mechanism

### ISSUE THREAD

**Issue by Le0nsec** [CTFd/CTFd#1548]
# Wish list: invitation code registration mechanism

**What happened?**
I hope that the official can create a simple invitation code registration mechanism, which can prevent users who do not have an invitation code from registering

**Comment by h4ckd0tm3** [comment]
How fast do you need this?
I think this might be possible with a plugin, I can code such a plugin, but it will take some time.

**Comment by Le0nsec** [comment]
thank you very much

**Comment by Le0nsec** [comment]
It's not very urgent, you can notify me when you make it

**Comment by h4ckd0tm3** [comment]
https://github.com/h4ckd0tm3/ctfd-bouncer

If you find any bugs, please leave an issue at my repository.

**Comment by Le0nsec** [comment]
Thank you very much for the plugin, if I find any bugs I will tell you the
first time

Marcel Schnideritsch <notifications@github.com> 于2020年7月16日周四 下午10:58写道：
