### ISSUE TITLE
Config page revamp

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#155]
The config page is very cluttered and needs to be broken up into tabs.

**Comment by nategraf** [comment]
I'll get a draft for this ready

**Comment by ColdHeat** [comment]
Some improvements from https://github.com/isislab/CTFd/pull/171. 

Needs a little integration into the theme but this is starting with a push from @nategraf!

**Comment by ColdHeat** [comment]
I think this work well enough to close the issue. I'll change up the buttons in a bit.
