### ISSUE TITLE
forget password

### ISSUE THREAD

**Issue by alahammad** [CTFd/CTFd#1576]
**Environment**:

- CTFd Version/Commit: 3.0.0
- Operating System: Ubuntu
- Web Browser and Version: Chrome 83.0.4103.116

**What happened?**
Forget password or verification email not working. I have email using zoho service and tried to connect this configs :

Outgoing Server Name: smtp.zoho.com
Port: 587
Security Type: TLS

**Comment by ColdHeat** [comment]
Wouldn't zoho require a password? Have you properly configured SMTP according to their rules? https://www.zoho.com/mail/help/zoho-smtp.html

Highly unlikely this is an issue in CTFd code as SMTP is used in Hosted CTFd. I'd recommend posting more details in https://community.majorleaguecyber.org/ and perhaps someone there can help you.
