### ISSUE TITLE
Upload Path Randomness

### ISSUE THREAD

**Issue by calebstewart** [CTFd/CTFd#1595]
Is there a specific security or practical reason that the component before the file name of an upload path is random? The variable names in `uploaders.py` seem to indicate that at some point this was a hash sum of the file (`md5hash`).

I ask because I'm trying to implement an automated CTF management tool which can synchronize a CTFd instance with a local configuration (defined in YAML files). The challenge definitions define file names/paths to upload, but there's no way for me to quickly check whether a file has changed, which makes it difficult to implement the sync logic.

Currently my only options are:

1. Assume the file is dirty and always delete/re-upload
2. Assume the file is clean if it exists, and require a separate option to force re-uploading.

In case one, this makes synchronizing the entire platform always take a long time (due to deleting/re-uploading every challenge attachment). Option two requires the user to remember if/when files are changed. In a distributed development environment, it would be great to allow developers to push changes to the CTFd configuration and an admin to simply synchronize the configuration.

I'm open to running a local fork of CTFd for my use-case, but I wanted to make sure there wasn't a serious reason it was implemented in this way before I just decided to change it. Thanks!

**Comment by ColdHeat** [comment]
Doesn't the ctfcli tool handle this for you? Literally just syncs a defined yaml with CTFd via API. https://github.com/CTFd/ctfcli. It deletes the existing file and re-uploads it.

Security wise it was originally intended to protect against accidental disclosure of files. Nowadays it helps with dealing with duplicate files. 

Perhaps it will be changed but it's actually been very useful as a means of guaranteeing a unique space for the file without changing the file's name. If you have an alternative strategy you are welcome to PR it.

**Comment by calebstewart** [comment]
Okay, awesome. I appreciate the quick response. I believe that answers my question!

**Comment by ColdHeat** [comment]
I am interested in having a solution for this. 

One possible idea is perhaps to be able to control the name of the folder that is used. Perhaps it could be something like a named files idea where the upload path is constant and controlled by the admin.
