### ISSUE TITLE
After a git pull, CTFd is broken

### ISSUE THREAD

**Issue by C0deH4cker** [CTFd/CTFd#160]
At https://ctf.hackucf.org, we are using CTFd deployed from within Docker using this command:

```
docker run --restart=unless-stopped -d -p 127.0.0.1:8000:8000 -v /ctf/ctfd.db:/opt/CTFd/CTFd/ctfd.db --name ctfd ctfd
```

I was updating CTFd from an older commit (417e51eba9c576f0087a16c3d70a256bf96dbe03). The steps I performed were:
1. `git pull`
2. Backup running docker container to new image via `docker commit` and save it as a tar with `docker save`, just in case the upgrade failed (turned out to be a good idea).
3. Build the new docker image with `docker build -t ctfd .`
4. Run new docker container based on new docker image with `docker run --restart=unless-stopped -d -p 127.0.0.1:8000:8000 -v /ctf/ctfd.db:/opt/CTFd/CTFd/ctfd.db --name ctfd ctfd`

After this, the updated CTFd is hopelessly broken. The teams page is broken with an error message, the scoreboard page is blank, the challenges page loads but solves don't, logging in doesn't work, and many other issues. My guess is there's something different in the way the two versions of CTFd handle the database.

I also tried reverting to the old, working docker container and doing the following steps (just in case it was broken because of differences in files):
1. Run a shell in the container via `docker exec -it ctfd /bin/sh`
2. `git pull`
3. `./prepare.sh`
4. `reboot`

After this, the result was exactly the same, still broken. I have since reverted to the old, working version again.

What is the recommended way of upgrading to a newer version of CTFd? Does the database need to be migrated somehow? This issue is related to #141.

**Comment by ColdHeat** [comment]
Typically what breaks CTFd right now are changes to models and your commit is very far back and a few breaking changes were introduced. 

I'm still working on a bunch of CTFd related things and this is one of them to resolve. The current strategy is to get to a 1.0 where everything can be frozen and versioning introduced. Probably going to set 1.0 to be the current commit. 

Then start getting database migrations in followed by tests. 

My suggestion would be to create a new CTFd container and then copy over data from the old database.

**Comment by C0deH4cker** [comment]
I managed to upgrade it with a lot of hand-editing of the database and building a new docker image. Took a few hours, but we're now even with master. I'll probably be contributing changes soon!

**Comment by C0deH4cker** [comment]
If the version or even current commit hash were stored in the database, it would make it easier to automatically upgrade the database when breaking changes are made.

**Comment by ColdHeat** [comment]
Pretty easy to store that in a config flag but maybe a version number would
be better instead of a commit hash

**Comment by C0deH4cker** [comment]
Yeah I agree. It would only need to increment when a change is made to the database format. It would need to be read-only on the admin page for config.

**Comment by ColdHeat** [comment]
I am not a huge fan of `Flask-Migrate` but CTFd now has versioning in place and and `alembic_version` in the database allowing you to do database migrations more easily. 

Hopefully this lets everyone stay up to date. If you're really far behind (like REALLY far behind) it's likely nothing short of manually editing the database will help. 

And as always, back up your databases and such.
