### ISSUE TITLE
Changes in view.py not getting reflected 

### ISSUE THREAD

**Issue by bhaviksec** [CTFd/CTFd#1606]
**Environment**:
Ubuntu18.04
- CTFd Version/Commit:3.0.1
- Operating System:Linux
- Web Browser and Version:

**What happened?**
Made changes to the view.py and could not see the changes being made
**What did you expect to happen?**
expect the changes to reflect on the web page 
**How to reproduce your issue**

**Any associated stack traces or error logs**
followed https://github.com/CTFd/CTFd/issues/873 but did not understand what changes to be made

**Comment by h4ckd0tm3** [comment]
Which changes do you want to make at the first place?

**Comment by ColdHeat** [comment]
After changing a Python file, depending on how you've deployed you may need to restart your CTFd instance. That depends on how you've deployed. 

But as referenced in #873, there is a built in page editor. For simple page edits you don't need to change views.py.

**Comment by RodEsV** [comment]
Hello, I try to redirect the page content to another html file so I changed the static_html fontion to return my page. Now, I'm having problems to link my css and js files that comes with the html page. 
Someone has an idea of how can I achieve this ?
