### ISSUE TITLE
Is there any option to update existing platform?

### ISSUE THREAD

**Issue by PunitTailor55** [CTFd/CTFd#1612]
**Environment**:

- CTFd 2.4:
- Operating System: Ubuntu 18
- Web Browser and Version: Latest Chrome

**What happened?**
I have already setup platform version 2.4. Is there anyway to update/upgrade existing setup?
**What did you expect to happen?**
I am expecting that directly update option. Also, I have try to setu mail server in version 2.4. Unfortunately, Mail function is not working. I have already check with hosting provider web mail is working fire but when I configured in the platform, email sending is not working. 
**How to reproduce your issue**
Please provide the details of how to setup email config in platform. I have already tried with given documentation. If anyone have step by step method please let me know.
**Any associated stack traces or error logs**
No

**Comment by ColdHeat** [comment]
You can upgrade by using git pull or updating the underlying docker image. There is no built in upgrade mechanism at this time. For what it's worth Hosted CTFd instances are upgrade managed for you (https://ctfd.io/hosting/).

**Comment by ColdHeat** [comment]
Regarding the mail server functionality, the code is working. I would recommend sharing a specific case where it isn't working or double checking your email settings.

**Comment by PunitTailor55** [comment]
Hi there!
I have check my server credentials and server details. I have also tried
with gmail integration with my hosted email address. I have setup the same
email-id and password but unable to send an email through platform.

Thanks and Regards,
