### ISSUE TITLE
redis: max number of clients reached

### ISSUE THREAD

**Issue by ConnorNelson** [CTFd/CTFd#1622]
Hello, we have several hundred users concurrently using a CTFd instance. After approximately 8 hours of usage, we faced internal server errors for nearly everything. This trace back is the underlying cause. I would be happy to look into fixing it in a couple of days, but I figured I'd report the issue now in case it is an already known issue with a known solution. Thanks.

```
[2020-08-27 17:45:31 +0000] [29] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/opt/CTFd/CTFd/utils/sessions/__init__.py", line 77, in open_session
    val = cache.get(self.key_prefix + sid)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 243, in get
    return self.cache.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/backends/rediscache.py", line 114, in get
    self._read_clients.get(self._get_prefix() + key)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 730, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 337, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached
```

We are using commit 976b191b535018827e8d8f1eadefb2e352179e19 (3.0.1).

**Comment by ColdHeat** [comment]
I believe Flask-caching pools redis connections but the Notifications system could potentially consume pubsub clients. You can disable it by toggling `SERVER_SENT_EVENTS` in `config.ini`. 

To figure this out, you'd need to know what redis's max client amount is, what type of clients they are, and what factor is increasing the client list. https://redis.io/topics/clients

To be clear, I don't believe I've run into this issue before personally.

**Comment by ConnorNelson** [comment]
Thanks, I'll try setting it to False and see if that resolves the issue.
Just as an FYI, in trying to do this, I came across the issue: #1623.

**Comment by ConnorNelson** [comment]
I suspect this will fix the issue.
Before rebooting the instance there were 5000+ clients using `cmd=subscribe`.
Now I see 16 clients (plus 1 for me), which are mostly using `cmd=get` and the occasional `cmd=setex`.

I'll update in a day or so to let you know if this has indeed resolved it. Thanks!

If I find some time, I can try to dig a little deeper into the issue to that events can be restored (though I'm not sure how much I actually care about them for my use case).

**Comment by ColdHeat** [comment]
I dug into this and suspect that there's a variety of factors here. Some of which may have been unintentionally mitigated in the hosted version of CTFd. 

If you can try the below patch, it would be useful. 

```diff
diff --git a/CTFd/utils/events/__init__.py b/CTFd/utils/events/__init__.py
index 7e95f6c..5fe69e7 100644
--- a/CTFd/utils/events/__init__.py
+++ b/CTFd/utils/events/__init__.py
@@ -75,22 +75,15 @@ class RedisEventManager(EventManager):
         return self.client.publish(message=message, channel=channel)
 
     def subscribe(self, channel="ctf"):
-        while True:
-            pubsub = self.client.pubsub()
-            pubsub.subscribe(channel)
-            try:
-                # Immediately yield a ping event to force Response headers to be set
-                # or else some reverse proxies will incorrectly buffer SSE
+        pubsub = self.client.pubsub()
+        pubsub.subscribe(channel)
+        try:
+            while True:
                 yield ServerSentEvent(data="", type="ping")
-
-                with Timeout(10) as timeout:
-                    for message in pubsub.listen():
-                        if message["type"] == "message":
-                            event = json.loads(message["data"])
-                            yield ServerSentEvent(**event)
-                            timeout.cancel()
-                            timeout.start()
-            except Timeout:
-                yield ServerSentEvent(data="", type="ping")
-            except Exception:
-                raise
+                message = pubsub.get_message(ignore_subscribe_messages=True, timeout=5)
+                if message:
+                    if message["type"] == "message":
+                        event = json.loads(message["data"])
+                        yield ServerSentEvent(**event)
+        finally:
+            pubsub.close()
```

**Comment by ColdHeat** [comment]
I spent a lot of time experimenting with this and I believe I have a solution that closes this issue. It would be good if you could try out #1626. It has a different base branch but the code should still apply to your commit/master.

**Comment by ColdHeat** [comment]
I believe #1626 resolves this issue and an existing workaround already exists so I'm closing this.
