### ISSUE TITLE
[Request] Email Domain Restriction

### ISSUE THREAD

**Issue by AridDay** [CTFd/CTFd#1624]
My team would like to be able to restrict registered users to those that have emails with a specific domain. For example, I would like to restrict registered user's email addresses to [username]@org-domain.com if my organization's email domain is "org-domain.com".

**Comment by ColdHeat** [comment]
CTFd already supports this behavior. https://docs.ctfd.io/tutorials/whitelisting-email-addresses/

**Comment by AridDay** [comment]
Thanks 👍 . Missed that in documentation.
