### ISSUE TITLE
Challenges buggy

### ISSUE THREAD

**Issue by 0x8** [CTFd/CTFd#163]
I'm not sure why / if it was intended but I've found the challenges on the page keep moving around, categories shift, and upon clicking on a challenge it often loads the wrong challenge until the page is refreshed.

I set it up with a postgres database, and followed the directions on the main page to install. I am running it using gunicorn as well. I don't know if any of that is relevant.

I started looking through some of the python files but so far I can't really find what might be causing the behavior, but perhaps I am just missing something.

**Comment by ColdHeat** [comment]
Definitely not intended. 

Can you provide a screenshot and what browser and what version you're on?

**Comment by 0x8** [comment]
I'm trying to get a screenshot, the behavior is seemingly random so it may take some time. As per browser I am using Firefox version 49.0.2 (Linux and OS X both with the same version).

**Comment by ColdHeat** [comment]
Were you using Postgres by chance?

**Comment by 0x8** [comment]
yes, I was using postgres

**Comment by ColdHeat** [comment]
Postgres doesn't order by ID when you SELECT data. I believe this is no longer an issue but I will test when I have the chance. 

Is this still happening for you?

**Comment by ColdHeat** [comment]
Closing due to lack of response. Feel free to reopen if it's still an issue for you.
