### ISSUE TITLE
Regression in Latest Release 3.1.0: Unable to create challenges

### ISSUE THREAD

**Issue by kevin-he-01** [CTFd/CTFd#1637]
**Environment**:

- CTFd Version/Commit: 3.1.0 or 9264e9642831e7dfcab5af8258b353e9a207e655

- Operating System:
    - Client: Windows 10: Microsoft Windows [Version 10.0.18363.1016]
    - Server:
        - Userland from the [Dockerfile](https://github.com/CTFd/CTFd/blob/adc70fb320242d5e4df1a7ce2d107c0e2b8039e7/Dockerfile)
        - Kernel: `Linux 5.8.2-arch1-1 #1 SMP PREEMPT Thu, 20 Aug 2020 20:45:00 +0000 x86_64 GNU/Linux`

- Web Browser and Version: Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**What happened?**

As an admin, you cannot create any challenges from the Admin Panel. The create challenge page at `/admin/challenges/new` is blank except for a challenge type chooser.
![image](https://user-images.githubusercontent.com/32375681/92525228-4e78f000-f1d8-11ea-91d4-2c893a95746c.png)

**What did you expect to happen?**

There should be a wizard directing you through the steps of creating a challenge, like inputting challenge name and flags, as in previous versions.

**How to reproduce your issue**

1. Pull this commit directly from GitHub and run `docker-compose up`, or just go to the [Demo](https://demo.ctfd.io/) which uses the latest commit from GitHub (make sure the version number at the bottom of the page is 3.1.0).
2. Set up a CTF if necessary, then log into your admin account. Then navigate to the Create Challenge page at https://demo.ctfd.io/admin/challenges/new (http://localhost:8000/admin/challenges/new if running locally).
- The same steps can be achieved by clicking on Admin Panel, then click Challenges on the top menu bar, and click the plus sign.
3. See a blank page.

**Any associated stack traces or error logs**

```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at HTMLDocument.<anonymous> (challenge.min.js?d=a70a5c94:1)
    at e (vendor.bundle.min.js?d=a70a5c94:150)
    at t (vendor.bundle.min.js?d=a70a5c94:150)
```
which I believe is due to this new change in the latest commit: https://github.com/CTFd/CTFd/commit/9264e9642831e7dfcab5af8258b353e9a207e655#diff-ae7cdb1cdad0bb5200c93bd5882c2741R431
It's in [line 431 of challenge.js](https://github.com/CTFd/CTFd/blob/9264e9642831e7dfcab5af8258b353e9a207e655/CTFd/themes/admin/assets/js/pages/challenge.js#L431)

**Comment by ColdHeat** [comment]
Thanks for reporting this and the detailed issue report, I'll fix this momentarily.
