### ISSUE TITLE
Next challenge after solve

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1668]
This could be pulled off with a next column that points to the next ID to be viewed. It would need API changes, Admin Panel changes and a migration.

**Comment by bdorr1105** [comment]
Is this feature broken? I thought this was already possible by adding a challenge as a requirement so it could not been until the requirement was complete?

**Comment by ColdHeat** [comment]
This is for a different, new feature. Automatically showing the "next" challenge after solving one challenge.

**Comment by ColdHeat** [comment]
This is very difficult to do because of how limiting `challenges.js` is. I think it would be better to push this off to 4.0 instead of hacking more things onto 3.x.

**Comment by ColdHeat** [comment]
Aiming for this to come out in CTFd 3.5
