### ISSUE TITLE
Email Confirmation is not working. How can we test via command line

### ISSUE THREAD

**Issue by bdorr1105** [CTFd/CTFd#1671]
**Environment**:

- CTFd Version/Commit: docker version from cloned repo v3.1.1
- Operating System: Ubuntu 20.04
- Web Browser and Version: Version 85.0.564.63 (Official build) (64-bit)

**What happened?**

I set up SMTP settings for gmail, and it does not appear to even trigger or attempt to send an email. It claims it does, but this does not appear to be accurate. I installed ssmtp on the same box, ran an email script to test and it works just fine. Not sure what is occurring with CTFd.

**What did you expect to happen?**

For email to actually work

**How to reproduce your issue**

Registered with a user to an email of mine waiting for an email to come through, but it never works

I do not know where the logs are located

Additional Note: I watched my firewall to look live at the time of submission, only saw dns:53 go out, not even an attempt to use port 587
![test email 2](https://user-images.githubusercontent.com/12386911/94371835-618c2b00-00c7-11eb-9c21-5da42048af78.PNG)

**Comment by ColdHeat** [comment]
Email code is tested and known to be working. You should double check your settings.

**Comment by bdorr1105** [comment]
Why would that be your reply? That made no sense, I already tested with SSMTP and it works just fine. I entered the SAME exact settings in the GUI, and it is not working at all. It is not even reaching out to even make an attempt. It only did a DNS request, so maybe your email code is not working. I provided the evidence and the follow up was less than helpful

**Comment by ColdHeat** [comment]
Hosted CTFd deployments (https://ctfd.io/hosting/) use the exact same SMTP code as open source CTFd. If the email code was broken, there would be a lot more issues than just your open source installation. 

Hence, unless you can prove what the actual issue is in the code, the only explanation would be your configuration or something specific to your instance. Also this is a Github issue tracker, not a place for tech support.

**Comment by bdorr1105** [comment]
the demo didn't work either....so is that proof?

**Comment by ColdHeat** [comment]
Demo is a fairly restricted server, just because something doesn't work there doesn't mean it won't work on another installation. 

You also haven't provided any of your settings, I don't know what you expect anyone to do here. Do you expect me to magically go into your server and figure out what's wrong?

**Comment by bdorr1105** [comment]
you said the demo has the code, is that not the next best thing to test to see if the issue exists? I don't mind you going in the server and checking it, at the end of the day, just trying to get an explanation. If you don't want to help, that is fine, however, if someone reports a bug, and you dont absolutely nothing to disprove the bug, then that is terrible business model. You don't have to support it, but i will say, that completely turned me off for every paying for a managed one in every way because I see the type of support to expect
![email seetings](https://user-images.githubusercontent.com/12386911/94374201-994f9e80-00d8-11eb-9e70-91e6a68ae248.PNG)

**Comment by ColdHeat** [comment]
Hosted CTFd instances automatically receive their own email sending credentials. They wouldn't even have to set this up. 

To prove my point, I just setup Gmail on my local test instance and it worked just fine. I also know that the code is tested by automated tests and the fact that it's currently used in production. 

I don't care if you use managed CTFd or not, but if you use OSS solutions, you should debug and figure out your own problems. 

You provided zero information beyond "it's not working", and I told you to double check your configuration. And again, I'm going to say that you should double check your configuration. 

```
❯ nslookup smtp.google.com
Server:		167.206.13.180
Address:	167.206.13.180#53

** server can't find smtp.google.com: NXDOMAIN
```

https://support.google.com/a/answer/176600?hl=en

**Comment by bdorr1105** [comment]
I provided you screenshots of working emails sent with the same exact configurations, sent a screenshot of CTFd, and you looking up smtp.google.com shows nothing and no proof of anything you did that worked. Your public one to test is having the same exact issues of not sending a single email. So, what point did you actually prove besides making a bunch of noise with absolutely nothing to back it. 

You started off immediately like a clown and were aggressive and arrogant, you are a terrible representative for this company. I would say I see the issue and it didn't click. I told you a number of times i tested with ssmtp and it worked with the same configuration. I received the emails just fine on that.

**Comment by hegdenischay** [comment]
Not sure if you got it working, but your smtp server should be smtp.gmail.com.
Also, I got smtp.py working by copying the CTFd/utils/email/smtp.py to the repo dir, so that might help.

**Comment by bdorr1105** [comment]
Yes I did, thank you very much for the follow up. During my interaction
with the Mr. Chung that the issue was my fault. The tough part was when I
tested it with ssmtp I entered the correct server and it took the
screenshot he sent for me to finally get it to click. Thanks again for your
help

**Comment by davidhcefx** [comment]
Oh, I finally know why there was no email sending out. Because there was no "Default email servers", I have to provide one LOL
