### ISSUE TITLE
standard or static?

### ISSUE THREAD

**Issue by RaminAT** [CTFd/CTFd#1687]
There are two challenge types in ctfd: standard and dynamic
I think the term "standard" should change to static. because dynamic is also standard

**Comment by frankli0324** [comment]
from the developers view, dyn chall type inherits standard chall type, and all other challenge types from plugins inherits the standard challenge type, so it's reasonable (at least for me) to call it 
"standard"

**Comment by ColdHeat** [comment]
I don't see the benefit of going through this rename.
