### ISSUE TITLE
How to limit the number of singups per IP

### ISSUE THREAD

**Issue by RaminAT** [CTFd/CTFd#1689]
How to limit the number of signups per IP and in a period (Like 5 signups per hour for each IP)?

**Comment by kaushalag29** [comment]
@RaminAT Hi!
I was going through the code and found this file.
**CTFd/auth.py**
`@ratelimit(method="POST", limit=10, interval=5)
def register():`
You can change limit=10 to 5, and interval(in seconds) respectively.
Hope this should work.

**Comment by RaminAT** [comment]
Thanks.
