### ISSUE TITLE
ctfd, when deployed using docker is vulnerable to denial of service by default

### ISSUE THREAD

**Issue by RaminAT** [CTFd/CTFd#1690]
**Environment**:

- CTFd Version/Commit: 3.1.1
- Operating System: Ubuntu 20.04 (LTS) x64

**What happened?**
ctfd, when deployed using docker and is not behind any DDoS mitigation service, is vulnerable to denial of service by default configurations. A single user can occupy the entire CPU usage of a server using 8GB of ram and 4 vCPUs. 

**What did you expect to happen?**
docker instance should be configured in a way that 1 user can not consume all of the resources of server.

**How to reproduce your issue**
You need to use my DoS script, that I will not post it online to prevent abuse. But I can test it against your docker instance.

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Security issues should be directed to support@ctfd.io instead of posted on the Github issue tracker.
