### ISSUE TITLE
None initiated a confirmation email resend

### ISSUE THREAD

**Issue by davidhcefx** [CTFd/CTFd#1706]
**Environment**: 

- CTFd Version/Commit: `3.1.1`
- Operating System: `Linux linux 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Web Browser and Version: `Google Chrome  86.0.4240.183`

**What happened?**
When I pressed the `Resend` button for resending a verification email, CTFd logged a line (in `logs/registrations.log`) like this:
```
[11/05/2020 16:12:32] 10.0.2.2 - None initiated a confirmation email resend
```
From my inspection, `session` in `utils/logging/__init__.py` didn't contain a key called 'email', as well as key 'name' and other stuff.

**What did you expect to happen?**
The `None` been replaced by my email which I used to register. If this is not a bug, then I apologize for the inconvenience.

**How to reproduce your issue**
- Start CTFd with `docker-compose up`.
- Register an account and press the `Resend` button for email verification.

**Any associated stack traces or error logs**
No

**Comment by alperb** [comment]
In addition to the current issue, registrations processes are also not interpreted correctly in the logs.
Here's a log from `logs/registrations.log`:
`[11/22/2020 12:32:03] 127.0.0.1 - None registered with None`
