### ISSUE TITLE
Multiple Choice Challenge Plugin

### ISSUE THREAD

**Issue by tomyxy** [CTFd/CTFd#172]
I want to add some multiple choice? is there any methods can do this? or how to modifiy ctfd?

**Comment by nategraf** [comment]
The easiest way to do this would be to simply provide a A, B, C, D answers in the challenge description and then instruct your users to enter their choice in the key text box. Make sure to enter the correct answer in the key box when you make the challenge in the admin view

Example:

```
What is the airspeed of an unladen swallow?

A - 31 – 40 mph
B - African or European?
C - 20 -31 mph
D - 343 m/s

Please enter your answer in the Key box below.
```

If this does not work for you can modify various pieces of the backend and front end code to add a flag for multiple choice and serve a specially designed template.

**Comment by ColdHeat** [comment]
nategraf has probably the simplest solution. 

In a longer term solution perhaps there should be a field for type in the Challenges schema allowing for choosing what "type" a question is and thus allow the front end to render different descriptions based on it.

**Comment by jhaddix** [comment]
this brings up a separate feature which is; limiting the number of guesses allowed for specific challenges.

**Comment by ColdHeat** [comment]
The testing branch has the ability to specify custom challenges. 

With a custom Challenge class and the associated templates for the UI, this is very feasible.

**Comment by ColdHeat** [comment]
Although it will likely require a database migration. But that shouldn't be a huge deal.

**Comment by ColdHeat** [comment]
This functionality exists in [professional hosted instances of CTFd](https://ctfd.io/hosting). I'm debating whether to offer the plugin for sale, open source it, etc. 

In addition, challenge types have been very fully fleshed out as of https://github.com/CTFd/CTFd/pull/425. I'm going to rename this issue and mark it as a plugin idea.

**Comment by ColdHeat** [comment]
This plugin has been available for sale at https://ctfd.io/store/ for some time now. Closing.
