### ISSUE TITLE
Erroneous requirements.txt

### ISSUE THREAD

**Issue by hopkinskong** [CTFd/CTFd#1729]
**Environment**:

- CTFd Version/Commit: 1883c62cf5f03476ebd1e5c04f3ac782dbad0512
- Operating System: Kali
- Web Browser and Version: N/A

**What happened?**
When building the docker container, it fails with:
```
...
Step 6/12 : RUN pip install -r requirements.txt --no-cache-dir
 ---> Running in feda56aeeb06
Collecting alembic==1.4.3
  Downloading alembic-1.4.3-py2.py3-none-any.whl (159 kB)
Collecting aniso8601==8.0.0
  Downloading aniso8601-8.0.0-py2.py3-none-any.whl (43 kB)
Collecting attrs==20.3.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting bcrypt==3.1.7
  Downloading bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56 kB)
Collecting boto3==1.13.9
  Downloading boto3-1.13.9-py2.py3-none-any.whl (128 kB)
Collecting botocore==1.16.26
  Downloading botocore-1.16.26-py2.py3-none-any.whl (6.2 MB)
Collecting certifi==2020.11.8
  Downloading certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
Collecting cffi==1.14.3
  Downloading cffi-1.14.3-cp37-cp37m-manylinux1_x86_64.whl (401 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click==7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting cmarkgfm==0.4.2
  Downloading cmarkgfm-0.4.2-cp37-cp37m-manylinux1_x86_64.whl (147 kB)
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from -r requirements.txt (line 18)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.8 (from -r requirements.txt (line 18))
ERROR: Service 'ctfd' failed to build: The command '/bin/sh -c pip install -r requirements.txt --no-cache-dir' returned a non-zero code: 1
```

It seems that the issue root from the following commit:
https://github.com/CTFd/CTFd/commit/1e9c0b43b17072fa8f9ee302b5c3e38adbb5a6e8

Where when building the docker image, `dataclasses == 0.8` was not found. When reverting this commit by:
`mv requirements.in requirements.txt`

The container was successfully built.

**Comment by jrespeto** [comment]
Also getting that error. 

```
ERROR: Package 'dataclasses' requires a different Python: 3.7.6 not in '>=3.6, <3.7'
```

In the mean time I added this line to the Dockerfile
```
RUN pip install --ignore-requires-python dataclasses==0.8
```

And committed out `dataclasses==0.8` in `requirements.txt`


https://github.com/ericvsmith/dataclasses/blob/master/setup.py

There is am open pull request to fix the issues for dataclasses. 
https://github.com/ericvsmith/dataclasses/pull/161/commits

**Comment by ColdHeat** [comment]
Thanks for doing the investigation @jrespeto. I think perhaps the requirements.txt could probably be generated on 3.7 and let 3.6 automatically pick up dataclasses based on the [pydantic setup.py](https://github.com/samuelcolvin/pydantic/blob/31bc2435d7968fdf8d1f0c5c67f0f851c1bef54e/setup.py#L128-L130). 

I kind of consider this a bug in dataclasses though.
