### ISSUE TITLE
Rewrite the rest of the challenge properties side bar to be in Vue

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1732]
Vue just works a lot better. There's no reason to not use it as much as possible. 
Rewrite tags, files, hints to use Vue components if possible.

**Comment by alperb** [comment]
Could you describe more what exactly you have in your mind? Switching to Vue?

**Comment by ColdHeat** [comment]
This should be closed now that the linked PRs are merged in. Most of the functionality on the admin challenge pages is Vue.
