### ISSUE TITLE
Unable to run CTFd behind a reverse-proxy endpoint

### ISSUE THREAD

**Issue by atz-dev** [CTFd/CTFd#1765]
**Environment**:

- CTFd Version/Commit: latest docker image
- Operating System: Debian 4.19
- Web Browser and Version:

**What happened?**
Unable to get CTFd to work behind an nginx reverse proxy endpoint.  
I'm using a docker-compose file with an nginx reverse-proxy on my server and a CTFd service running on the same docker network.  
The goal is to make an architecture with multiple CTFd behind a reverse-proxy, for example with /ctf1 and /ctf2.  

I'm actually trying to make CTFd accessible through example.com/noob-ctf, but CTFd doesn't handle properly my requests and redirect the client to /setup, at root (I expect to get redirected to /noob-ctf/setup instead).  

Here's my nginx configuration :
![Capture d’écran 2020-12-23 à 12 58 21](https://user-images.githubusercontent.com/44492274/102994108-b13f8e80-451e-11eb-9618-52472737b933.png)

Below, the docker-compose configuration for the two services : 
![Capture d’écran 2020-12-23 à 12 58 56](https://user-images.githubusercontent.com/44492274/102994303-1b583380-451f-11eb-9f31-cdd05cc1b916.png)
![Capture d’écran 2020-12-23 à 12 58 38](https://user-images.githubusercontent.com/44492274/102994295-18f5d980-451f-11eb-982c-20e37be235ab.png)

**Comment by ColdHeat** [comment]
Please see the APPLICATION_ROOT configuration value: https://docs.ctfd.io/docs/deployment/configuration/#application_root

**Comment by atz-dev** [comment]
Thanks for your response, @ColdHeat. 
Could I be able to set the APPLICATION_ROOT value directly in the environment with my docker-compose file ?  

![Capture d’écran 2020-12-23 à 22 51 15](https://user-images.githubusercontent.com/44492274/103039499-5daa6080-4571-11eb-8f0d-077f5e5af4b2.png)
