### ISSUE TITLE
Modifying the routes to accomodate challenge questions

### ISSUE THREAD

**Issue by OungKennedy** [CTFd/CTFd#1775]
Hi I'm using CTFd to host an event where some questions are based of a web application. I'm thinking of integrating CTFd with my own web app. This way, there will only need to be 1 backend to handle routing instead of 2. 

I've studied the architecture of this project and it seems some of the original Flask functionalities have been overridden. This makes it a little confusing to add my own routes. Are there any resources that explain how to do so? 

Apologies if this question has already been asked previously, if it has, please let me know of the issue number.

**Comment by ColdHeat** [comment]
Isn't this covered by https://docs.ctfd.io/docs/plugins/#adding-new-routes?

**Comment by OungKennedy** [comment]
Oh I see thanks so much !
