### ISSUE TITLE
Mark wrong key as correct button

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#181]

**Comment by Ret2lib** [comment]
Could you explain this a bit more?

**Comment by ColdHeat** [comment]
@Ret2lib sure! Basically CTFd has pages that show incorrect submissions for the entire CTF. I believe this issue was for admins to be able to mark an incorrect submission as correct. Does that make sense?

**Comment by Ret2lib** [comment]
Understood, I’ll take ownership of this and start working on it on downtime.

**Comment by ColdHeat** [comment]
This is actually not so easy to do because CTFd relies on the ID to determine who submitted something first. Optimistically we would want to directly convert an incorrect flag into a correct one so that it retains its ID. This way the timing is correct. 

However, directly inserting IDs seems like a bad idea. I'll investigate what happens but seems like this is more trouble than its worth. It might be better to just handle these kinds of situations manually.

**Comment by ColdHeat** [comment]
I think after https://github.com/CTFd/CTFd/pull/2212 this is now possible
