### ISSUE TITLE
Add solve count to challenge list API

### ISSUE THREAD

**Issue by maybe-sybr** [CTFd/CTFd#1811]
It would be nice if we could add the number of solves to the challenge list API so themes could render things like first blood or medal availability. We can currently request the solves for each challenge but that'd be extremely wasteful and since we already make queries for solves to manage challenge requirements, it doesn't seem unreasonable to also add a count on the challenge ID  in the solves table. Something like:

```
solve_counts = {
    chal_id: solves for (chal_id, solves) in db.session.query(
        Solves.challenge_id, sa_func.count(Solves.challenge_id),
    ).group_by(Solves.challenge_id).all()
}
```

We can also do some trickery to wrap up the check for if the current user/team has solved it like so:
```
solve_counts = {
    chal_id: (solves, user_solved) for (chal_id, solves, user_solved) in db.session.query(
        Solves.challenge_id, sa_func.count(Solves.challenge_id),
        sa_func.sum(Solves.account_id == user.account_id),
    ).group_by(Solves.challenge_id).all()
}
```

which would save us from doing more queries later on.

Would you be interested in a PR for this?

**Comment by ColdHeat** [comment]
I was wondering this myself a few days ago but I didn't remember exactly why it wasn't included in the response. I think you're right so would definitely be interested in a PR. 

I think perhaps the idea was to make the challenge listing endpoint cacheable but by including requirements it overall is much harder to cache so adding more user-specific things is probably not going to make it worse.

**Comment by maybe-sybr** [comment]
> I think perhaps the idea was to make the challenge listing endpoint cacheable

Yep, that had been my guess as well as it being a relic from before requirements were implemented and possibly not wanting to make more queries to the database which might have slowed down the endpoint if not done carefully (the submissions table would typically be much larger than the challenges one).

I'll look into doing this during the week and getting something up for you. I may also take the opportunity to refactor the challenge list endpoint a bit since to merge some common logic :)

**Comment by ColdHeat** [comment]
This is v3.3 so I'm going to close it but I will create a new issue to add the fields to the API docs. I'm not sure how to add random entries to the Pydantic model or if it would require a custom model.

**Comment by ColdHeat** [comment]
Actually re-opening this b/c we should be able to cut out the additional queries for solves on the initial challenges page load. Forgot about that.
