### ISSUE TITLE
Rework Challenge Requirements UI

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1825]
Challenge requirements should probably be sets of checkboxes instead of the current list. With Vue this should be a lot easier to pull off. 

Also we should explicitly support the hidden functionality of anonymized challenges that can't be seen until they're unlocked.

**Comment by maybe-sybr** [comment]
I was about to make an issue about the anonymized thing. Good to know you're already aware. For the moment I've just been making crafted PATCH requests to create them lol
