### ISSUE TITLE
Can't create a user through the REST API

### ISSUE THREAD

**Issue by zurro** [CTFd/CTFd#1828]
**Environment**:

- CTFd Version/Commit: 3.2.1, 9374c2a
- Operating System: Ubuntu 20.04 (docker)
- Web Browser and Version:

**What happened?**

I installed CTFd cloning the repo and launching the command: _docker-compose up_

I generated a token through the UI.

Executed a POST using Postman to the API endpoint: _http://10.60.175.144/api/v1/users_ with the following headers:

`CSRF-Token:f193e4240de8f4d5dec6b5a49944e33b00d11410872fa55f66b9a22ca8bc326c`
`Content-Type:application/json`

and the following body: 
`{"banned":false,"verified":true, "hidden":false,"name":"MyUser","type":"user","password":"MyNiceUser","email":"myuser@acme.corp" }`

**What did you expect to happen?**

I expected the user to be created and instead of that I get the following message: 
`"message": "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."`

**Comment by ColdHeat** [comment]
Here's an example of how the ctfcli project communicates with the CTFd API: https://github.com/CTFd/ctfcli/blob/46f1e222332decff95798ba564c3f40dfbceab1c/ctfcli/utils/config.py#L64-L70

**Comment by zurro** [comment]
And this does not work for the users endpoint. The authentication is correct but the user seems not having permissions, even if the token was generated with an Admin user.

**Comment by ColdHeat** [comment]
Admins are the only ones who can add users via the users endpoint. 

If you have used the approach that the ctfcli code uses, then you would need to provide a more thorough test case to determine what the issue is.
