### ISSUE TITLE
Idea: Export challenge board refresh function to page javascript

### ISSUE THREAD

**Issue by maybe-sybr** [CTFd/CTFd#1841]
At the moment, it feels difficult to write javascript in a plugin which interacts effectively with core JS from the theme (which is webpacked). If I'm not missing anything, this is mostly because there do not appear to be any `module.exports` in the page javascript sources in the core theme.

It would be nice if it were possible to simple call some export available to normal JS to refresh the challenge board. IIUC, simply adding something like the following to `core/assets/js/pages/challenges.js` would suffice:
```javascript
module.exports = {
  updateChallengeBoard: update,
}
```

We should obviously think about this as a wider effort though and there are probably other bits of webpacked page JS which would be worth exporting for use in other templates.

This would also obviously be theme specific since some other theme might not export the same functions or use the same names, but given that most themes probably diverge from `core` to start with (or share assets like the hacker theme), the worst case is probably that the console barfs errors when a plugin isn't careful about checking if what they are calling actually exists.

**Comment by maybe-sybr** [comment]
This specific idea would be less necessary if #1819 happens but it can't hurt to have both.

**Comment by ColdHeat** [comment]
This is a bigger issue overall. Yes more things should be exported but I'm going to work on just getting rid of webpack overall. 

https://github.com/CTFd/CTFd/issues/737

This is next in the todo list which I expect will let the harder JS work be handled by CTFd code and then theme code can be written however the end-dev wants to be.

**Comment by ColdHeat** [comment]
I'm adding the scoreboard and challenge board update functions to the window global with #1957 so I'm going to close this. But this is improved in CTFd.js: https://github.com/CTFd/CTFd.js/blob/main/main.js#L89-L97.
