### ISSUE TITLE
Rebuild and release Dockerfiles

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#187]
The Dockerfile here is not exactly written properly. We should be able to have the entierety of the CTFd workdir as a VOLUME outside of the container but because of the structure (or something else) the folder cannot be mounted. 

Some research is needed into adding a `docker-entrypoint.sh` file that will handle the initial setup of CTFd.

In addition I think the Dockerfile should pull the files from master or latest instead of copying from the current working directory. This needs a versioning system in place.

**Comment by C0deH4cker** [comment]
Hey, I just saw this issue! At https://ctf.hackucf.org we deploy CTFd in Docker using a `VOLUME` mount. This is what our Dockerfile looks like:

```Dockerfile
FROM alpine:3.2
RUN apk update && apk upgrade
RUN apk add git gcc musl-dev libffi-dev python python-dev py-pip

VOLUME /opt/CTFd
WORKDIR /opt/CTFd
COPY requirements.txt ./

RUN pip install -r requirements.txt
RUN pip install pymysql

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "-w", "4", "CTFd:create_app()"]
EXPOSE 8000
```

It is started with the following docker command:

```bash
docker run --restart=unless-stopped -d -p 127.0.0.1:8000:8000 -v /etc/localtime:/etc/localtime:ro -v /ctf/CTFd:/opt/CTFd --name ctfd ctfd
```

I'd strongly recommend against having the Dockerfile pull from master. Instead, users should simply `git pull` to get to the version they wish to deploy before building the docker image.

I hope this helps!

**Comment by ColdHeat** [comment]
I released a Docker image on DockerHub: https://hub.docker.com/r/ctfd/ctfd/

It's still mildly beta so it won't go up on the README yet.
