### ISSUE TITLE
Purchased Theme Breaks Server

### ISSUE THREAD

**Issue by d4ng3r-z0n3** [CTFd/CTFd#1873]
Works fine using 'core' Theme I bough learning Theme from store they haven't been able to help

 ERROR [CTFd] Exception on /login [GET]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
ctfd_1   |     response = self.full_dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
ctfd_1   |     rv = self.handle_user_exception(e)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
ctfd_1   |     return original_handler(e)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
ctfd_1   |     reraise(exc_type, exc_value, tb)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
ctfd_1   |     raise value
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 184, in ratelimit_function
ctfd_1   |     return f(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/auth.py", line 400, in login
ctfd_1   |     return render_template("login.html", errors=errors)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
ctfd_1   |     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
ctfd_1   |     return self.get_template(template_name_or_list, parent, globals)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
ctfd_1   |     return self._load_template(name, self.make_globals(globals))
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 96, in _load_template
ctfd_1   |     template = self.loader.load(self, name, globals)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
ctfd_1   |     source, filename, uptodate = self.get_source(environment, name)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
ctfd_1   |     return self._get_source_fast(environment, template)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
ctfd_1   |     raise TemplateNotFound(template)
ctfd_1   | jinja2.exceptions.TemplateNotFound: login.html

**Environment**:

- Current CTFd Version/Commit:
- Operating System:
- Web Browser and Version:

**What happened?**

**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
You should reset all configuration by deleting `.data` and running docker-compose down, docker-compose build --no-cache, and docker-compose up. This issue is b/c your theme is either missing files or is incorrectly configured.
