### ISSUE TITLE
Be able to export scoreboard to CTFtime format

### ISSUE THREAD

**Issue by 0xmmalik** [CTFd/CTFd#1939]
After CTFd moved away from the CTFtime integration, they removed the capability of having a live-updating scoreboard on CTFtime. Is it possible to export the scoreboard to the CTFtime JSON format after the event has ended to still have the scoreboard there? If not, can this be added?

**Comment by ColdHeat** [comment]
You can do this through the MLC integration or through a CTFd plugin.

**Comment by 0xmmalik** [comment]
I don't believe there's an existing CTFd plugin for this. How would it work through the MLC integration?
