### ISSUE TITLE
Size limits on logo, favicon, image uploads

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1972]
Sometimes people upload really big images for small things like the logo or the favicon. We should impose some kind of size limit or automatic resizing.

**Comment by 0x0elliot** [comment]
hey, i would like to help out with this issue. is there a particular file which I should work on? 

i have worked on CTFd multiple times and i am quite a bit familiar with it. pointing me in the right direction would speed things up :)
