### ISSUE TITLE
Dockerhub Docker Image not updating

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#1982]
The Docker image on CTFd isn't updating anymore. Likely because of Docker's various account changes. We'll need to see how to get this working again or figuring out an alternative solution.

**Comment by kraft87** [comment]
Would it be possible for someone to manually update it for now?

**Comment by frankli0324** [comment]
try ghcr.io

**Comment by ColdHeat** [comment]
@kraft87 I manually pushed new images but will work on getting something automated running again and also pushing to ghcr.io.
