### ISSUE TITLE
SqlAlchemy error using docker-compose with latest commit

### ISSUE THREAD

**Issue by KptCheeseWhiz** [CTFd/CTFd#1992]
**Environment**:

- CTFd Version/Commit: Latest commint d03692d002938df0eef43404d38035e53c134fe2
- Operating System: Azure VM Std B2s with Ubuntu 20.04.2
- Web Browser and Version: X

**What happened?**
The ctfd server crashes every few hours due to a sqlalchemy connection queuepool overflow.
**What did you expect to happen?**
The ctfd server to not crash every few hours.
**How to reproduce your issue**
Run the ctfd infrastructure using docker-compose, nothing changed. Changing the `SQLALCHEMY_MAX_OVERFLOW` value in config.ini seems only to push back the problem.
**Any associated stack traces or error logs**
```
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
ctfd_1   |     response = self.full_dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
ctfd_1   |     rv = self.handle_user_exception(e)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
ctfd_1   |     return original_handler(e)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
ctfd_1   |     reraise(exc_type, exc_value, tb)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
ctfd_1   |     raise value
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1948, in full_dispatch_request
ctfd_1   |     rv = self.preprocess_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2242, in preprocess_request
ctfd_1   |     rv = func()
ctfd_1   |   File "/opt/CTFd/CTFd/utils/initialization/__init__.py", line 241, in banned
ctfd_1   |     user = get_current_user_attrs()
ctfd_1   |   File "/opt/CTFd/CTFd/utils/user/__init__.py", line 39, in get_current_user_attrs
ctfd_1   |     return get_user_attrs(user_id=session["id"])
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 834, in decorated_function
ctfd_1   |     rv = f(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/utils/user/__init__.py", line 46, in get_user_attrs
ctfd_1   |     user = Users.query.filter_by(id=user_id).first()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3375, in first
ctfd_1   |     ret = list(self[0:1])
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3149, in __getitem__
ctfd_1   |     return list(res)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
ctfd_1   |     return self._execute_and_instances(context)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in _execute_and_instances
ctfd_1   |     querycontext, self._connection_from_session, close_with_result=True
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _get_bind_args
ctfd_1   |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3496, in _connection_from_session
ctfd_1   |     conn = self.session.connection(**kw)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
ctfd_1   |     execution_options=execution_options,
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
ctfd_1   |     engine, execution_options
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
ctfd_1   |     conn = bind._contextual_connect()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2311, in _contextual_connect
ctfd_1   |     self._wrap_pool_connect(self.pool.connect, None),
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
ctfd_1   |     return fn()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
ctfd_1   |     return _ConnectionFairy._checkout(self)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
ctfd_1   |     fairy = _ConnectionRecord.checkout(pool)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
ctfd_1   |     rec = pool._do_get()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
ctfd_1   |     code="3o7r",
ctfd_1   | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 20 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

**Comment by ColdHeat** [comment]
Your issue seems to imply that this is happening without any load, is that the case? If so then there may be an issue with CTFd holding a connection open somewhere. But if that isn't the case then it's more likely that the issue is a configuration problem of some sort that you'll need to figure out based on your workload. Perhaps you need more workers (the max overflow limit is per worker)? You could also consider setting the overflow limit to unlimited but you'll need to understand the risks behind that as well.

**Comment by KptCheeseWhiz** [comment]
It is not without load, we are hosting a CTF for around 100-150 persons. It makes sense to add workers. I guess its a case of RTFM, sorry for bothering, but it looked like nobody had this issue before. Thank you for replying.

**Comment by ColdHeat** [comment]
No problem, I actually think this is weird behavior in SQLAlchemy but it seems like the general recommendation is to not do unlimited connections. I think Django implements no pooling with no limit on total connections but expires them after some time. But Django uses Postgres so I don't really know the calculus there. 

If anyone else stumbles on this issue and has more experience feel free to suggest an improved pooling system or whether or not it makes sense to disable pooling.

**Comment by KptCheeseWhiz** [comment]
@restran Yes, in the `docker-compose.yml` file, you need to set the `WORKERS` enviroment variable in the ctfd service to something else than 1 and add a random `SECRET`. Make sure to completly up and down the service to make it "reload" the variables, just restarting it won't be enough.

**Comment by restran** [comment]
@KptCheeseWhiz this solution didn't works for me, this error still exists.

**Comment by nscuro** [comment]
We're seeing this error as well, even with quite a bit more workers and `SQLALCHEMY_MAX_OVERFLOW` set to `100`. Looks like CTFd isn't releasing connections properly and / or opening too many.

**Comment by ColdHeat** [comment]
@nscuro perhaps but afaik CTFd is releasing connections properly and queries aren't being slow. It is more likely that you are running into scaling issues. For example MySQL has a connection limit in place so even if you were to increase your workers and SQLAlchemy limits you might still not be able to make enough connections. Try seting SQLALCHEMY_MAX_OVERFLOW to -1 for unlimited connections. However keep in mind that this may still hit your database's configured connection limit as discussed in the SQLAlchemy docs here: https://docs.sqlalchemy.org/en/14/errors.html#queuepool-limit-of-size-x-overflow-y-reached-connection-timed-out-timeout-z. 

If you're able to find out where the leak is (if there is one), let me know and I'll promptly resolve.
