### ISSUE TITLE
Broken URL generation when behind proxy

### ISSUE THREAD

**Issue by lamermoon** [CTFd/CTFd#1993]
**Environment**:

- CTFd Version/Commit: d03692d002938df0eef43404d38035e53c134fe2
- Operating System: Cent OS 7, Linux Kernel 3.10.0-1160.15.2.el7.x86_64, Docker version 20.10.4, build d3cb89e

**What happened?**
A fresh CTFd fails to load the scoreboard and challenges. Also, changes to the competition name and other configuration options like start and end times do not show any effect and do not get stored. This is caused by a broken URL generation algorithm that prepends the X-FORWARDED-PREFIX twice.

**What did you expect to happen?**
The scoreboard should show no results and the challenges page should display a dummy challenge I configured. The competition name should be changeable and the start and end time of the competition can be set to a different value.

**How to reproduce your issue**
In `docker-compose.yml` I commented out the Nginx section as I use Traefik as reverse proxy. CTFd is supposed to be reachable in the subdirectory `domain.com/matz`. Traefic runs a middleware that removes the `/matz` part from URLs before forwarding requests to CTFd. CTFd is aware of the proxy (REVERSE_PROXY=true in docker-compose.yml)

**Any associated stack traces or error logs**
![2021-09-21-132630_4480x1440_scrot](https://user-images.githubusercontent.com/11388608/134166074-e418fdc2-84cb-45c9-a73c-17f07163c3b7.png)
![2021-09-21-135022_4480x1440_scrot](https://user-images.githubusercontent.com/11388608/134166752-65c727ba-371e-4321-8e4a-15a578f09c0d.png)

**Comment by ColdHeat** [comment]
Have you tried the `APPLICATION_ROOT` setting in config.ini?

**Comment by lamermoon** [comment]
That solved the problem, thanks!
However, in my browser I can see that /matz still gets prepended twice (screenshots would still look the same with a single difference: 404 codes are now 200). Due to the `APPLICATION_ROOT = /matz` setting, CTFd now just knows what to do with the request. Wouldn't it make sense to prevent the double-prepending in the first place?

**Comment by ColdHeat** [comment]
Okay after very carefully reading this and looking at your screenshot more carefully, I think you are looking for the more specific setting of REVERSE_PROXY: https://github.com/CTFd/CTFd/blob/master/CTFd/config.ini#L139-L143. You can control how Flask's ProxyFix functionality handles the X-Forwarded headers. Perhaps `1,1,1,1,0` instead of just `true`. 

But I think it's more likely that you've misconfigured Traefik somehow. CTFd can run on a subdirectory on it's own, and doesn't need Traefik to rewrite URLs for it or anything. Traefik just needs to proxy that subdirectory to CTFd and CTFd needs `APPLICATION_ROOT` properly configured. 

CTFd needs to have `APPLICATION_ROOT` set because it needs to generate the right URLs and also for Javascript to know where to communicate.

**Comment by lamermoon** [comment]
Oh, I wasn't aware of that! I now tried to run CTFd with `APPLICATION_ROOT = /matz` and `REVERSE_PROXY = false` and configured Traefik to not rewrite URLs and CTFd is working fine.

But in the CTFd logs I still see
```log
ctfd_1   | 192.168.32.2 - - [22/Sep/2021:08:24:08 +0000] "GET /matz/scoreboard HTTP/1.1" 200 6903 "https://domain.com/matz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"
ctfd_1   | 192.168.32.2 - - [22/Sep/2021:08:24:08 +0000] "GET /matz/themes/core/static/js/pages/scoreboard.min.js?d=412401b3 HTTP/1.1" 200 0 "https://domain.com/matz/scoreboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"
ctfd_1   | 192.168.32.2 - - [22/Sep/2021:08:24:08 +0000] "GET /matz/themes/core/static/js/echarts.bundle.min.js?d=412401b3 HTTP/1.1" 200 0 "https://domain.com/matz/scoreboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"
ctfd_1   | 192.168.32.2 - - [22/Sep/2021:08:24:09 +0000] "GET /matz/matz/api/v1/scoreboard/top/10 HTTP/1.1" 200 30 "https://domain.com/matz/scoreboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"
```

where the last line shows a `GET /matz/matz/api/v1/scoreboard/top/10 HTTP/1.1` instead of what I would expect to be a `GET /matz/api/v1/scoreboard/top/10 HTTP/1.1`

---
Concerning the `1,1,1,1,0` instead of `true` configuration: I tried that one but everything I tried made CTFd crash with a Value Error:
```
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "ping.py", line 10, in <module>
ctfd_1   |     from CTFd.config import Config
ctfd_1   |   File "/opt/CTFd/CTFd/config.py", line 81, in <module>
ctfd_1   |     class ServerConfig(object):
ctfd_1   |   File "/opt/CTFd/CTFd/config.py", line 177, in ServerConfig
ctfd_1   |     REVERSE_PROXY: bool = process_boolean_str(empty_str_cast(config_ini["optional"]["REVERSE_PROXY"], default=False))
ctfd_1   |   File "/opt/CTFd/CTFd/config.py", line 43, in process_boolean_str
ctfd_1   |     return bool(strtobool(value))
ctfd_1   |   File "/usr/local/lib/python3.7/distutils/util.py", line 307, in strtobool
ctfd_1   |     raise ValueError("invalid truth value %r" % (val,))
ctfd_1   | ValueError: invalid truth value '"1,1,1,1,0"'
```
The above log shows the error thrown when I set `REVERSE_PROXY="1,1,1,1,0"` in `docker-compose.yml`. But the same error occurs if I try `REVERSE_PROXY=1,1,1,1,0` or `REVERSE_PROXY='1,1,1,1,0'`. Setting `REVERSE_PROXY` in `config.ini` directly results in the same error as well.

**Comment by ColdHeat** [comment]
I think that double prepend might be a separate issue. I will re-open and take a look when I can. Subdirectory deployments aren't very common so they don't get a lot of usage so its possible there's a glitch there. 

The REVERSE_PROXY thing is definitely an issue though.

**Comment by ColdHeat** [comment]
Still need to look into the double prepend thing.

**Comment by ColdHeat** [comment]
This double prepend issue is related to some JS code that was codegenned to interact with the API. It doesn't appear to be a breaking issue but it should be fixed nonetheless. However it will be fixed in the rewrite of the JS/theme that I'm planning.

**Comment by ColdHeat** [comment]
This should be fixed by https://github.com/CTFd/core-beta but I will test to make sure that the `APPLICATION_ROOT` setting works there before closing this.

**Comment by ColdHeat** [comment]
This is fixed in [core-beta](https://github.com/CTFd/core-beta) which will become the default slowly as we move to v4.
