### ISSUE TITLE
Parameters for /v1/teams/{team_id}/members ?

### ISSUE THREAD

**Issue by jLemmings** [CTFd/CTFd#1997]
**Environment**:

- CTFd Version/Commit: 3.4.0
- Operating System: Provider docker-compose running in WSL
- Web Browser and Version: Firefox 92.0

**What happened?**

Trying to add a user to a team using the API. Did not work as expected and no documentation is provided.

**What did you expect to happen?**

`GET localhost:8000/api/v1/teams/1/members` returns following data:
```
{
    "success": true,
    "data": [
        1
    ]
}
```

I would then expect that `POST localhost:8000/api/v1/teams/1/members` with following body would add the 2nd user:
```
{
    "data": [1,2]
}
```

Actual return:
```
{
    "message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. You have requested this URI [/api/v1/teams/1/members] but did you mean /api/v1/teams/<team_id>/members or /api/v1/teams/me/members or /api/v1/teams/me ?"
}
```

I replaced the "data" field with following strings: "members", "team_members", "user_id", "user". None of them worked as expected.

**How to reproduce your issue**

Follow steps above.

What is the correct way to create such a request? I was not able to find the solution using the frontend code...

Cheers

**Comment by ColdHeat** [comment]
I believe it should just be "user_id" and the ID of the user you wish to add to the team. The endpoint doesn't take bulk lists like that. You can look at the request in Inspector from the Admin Panel to see what CTFd does when you manually add a user to a team. 

Here's the relevant code: https://github.com/CTFd/CTFd/blob/master/CTFd/api/v1/teams.py#L425-L449

**Comment by jLemmings** [comment]
Great that was it, somehow I missed that code section...

Thanks!
