### ISSUE TITLE
API documentation is broken

### ISSUE THREAD

**Issue by MrSuicideParrot** [CTFd/CTFd#2006]
I'm trying to access the API documentation page of CTFd, https://docs.ctfd.io/docs/api/Swagger%20UI, but it's broken and doesn't show Swagger UI.
I didn't find any other contacts, so I reported here.

**Comment by ColdHeat** [comment]
Thanks for pointing that out. The docs site is being rewritten so it's easier to search. For now the best alternative is probably https://demo.ctfd.io/api/v1/ but Ill look to fix this when I can.

**Comment by ColdHeat** [comment]
Fix this by embedding an iframe to the demo site. Still need to improve a lot of the API docs. Looking for someone to help with that as well.
