### ISSUE TITLE
Double check links to docs in CTFd

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#2015]
Since moving CTFd's docs to docusaurus, we may have broken some links in CTFd itself. We should double check that none of them are broken.

**Comment by Carlosbogo** [comment]
Hi, I would be glad to help with it, but just to make sure: the idea is to just go through the docs checking if the links are broken?

**Comment by ColdHeat** [comment]
Go through CTFd itself and the documentation but overall yes.

**Comment by ColdHeat** [comment]
I actually think all of the docs were updated beforehand so this seems okay to close.
