### ISSUE TITLE
[bug] Can't authenticate to the API using access token

### ISSUE THREAD

**Issue by nikitastupin** [CTFd/CTFd#2020]
**Environment**:

- CTFd Version/Commit: (1) https://demo.ctfd.io, (2) the bug also exists in my self-hosted installation (CTFd 3.4.0)
- Operating System: Ubuntu 20.04
- Web Browser and Version: N/A

**What happened?**

I can't authenticate to the API:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/login?next=%2Fapi%2Fv1%2Fusers%2Fme%3F">/login?next=%2Fapi%2Fv1%2Fusers%2Fme%3F</a>. If not click the link.
```

**What did you expect to happen?**

Data from the `api/v1/users/me` endpoint.

**How to reproduce your issue**

1. Navigate to https://demo.ctfd.io/login and login using `admin:password`
2. Navigate to https://demo.ctfd.io/settings#tokens and generate an access token (with Expiration in the future)
3. Execute the following command replacing `ACCESS_TOKEN` with the obtained token

```
curl -X GET "https://demo.ctfd.io/api/v1/users/me" -H "Authorization: Token ACCESS_TOKEN" -H "accept: application/json"
```
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/login?next=%2Fapi%2Fv1%2Fusers%2Fme%3F">/login?next=%2Fapi%2Fv1%2Fusers%2Fme%3F</a>. If not click the link.
```

**Comment by nikitastupin** [comment]
A temporary workaround is to use cookie:

```bash
curl https://demo.ctfd.io/api/v1/users/me -b session=YOUR_SESSION_COOKIE
```

**Comment by ColdHeat** [comment]
Isn't this the same as https://github.com/CTFd/CTFd/issues/1974?

**Comment by nikitastupin** [comment]
Yeah, seems like a duplicate!
