### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by Matir** [CTFd/CTFd#2023]
**Environment**:

- CTFd Version/Commit: git rev-parse HEAD                        
a0783c334c321103054a31a8e09ae4d1a404d7c1
- Operating System: Debian Linux
- Web Browser and Version: n/a

**What happened?**

`npm install` failed:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ctfd@3.4.0
npm ERR! Found: webpack@4.28.4
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"~4.28.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.36.0 || ^5.0.0" from sass-loader@8.0.2
npm ERR! node_modules/sass-loader
npm ERR!   dev sass-loader@"^8.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**What did you expect to happen?**

Install node modules.

**Comment by ColdHeat** [comment]
I'm looking into this. Always a battle with JS :(

**Comment by ColdHeat** [comment]
I have a PR to fix this but I believe you can work around this if you downgrade node to about version 14.
