### ISSUE TITLE
Apache Reverse Proxy

### ISSUE THREAD

**Issue by OpenSecureCo** [CTFd/CTFd#2035]
**Environment**:

Running via docker containers using docker-compose

**What happened?**
When I select "logout" within the web UI I get redirected to a webpage that shows the internal ip

![image](https://user-images.githubusercontent.com/74164997/148009577-bdccd0ae-2e85-4e0b-805e-e0b4eee9f85e.png)

**What did you expect to happen?**
I have a reverse proxy running Apache infront of this server and all other features work fine but the logout one.

Apache config:
![image](https://user-images.githubusercontent.com/74164997/148009668-05e0ee2e-727f-4db2-aa50-890f84355d6f.png)

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by OpenSecureCo** [comment]
And I am not sure how to get around that issue? It seems like my apache server may not be redirecting users back to / ?

**Comment by ColdHeat** [comment]
CTFd only provides an nginx config and it's been many years since I've configured Apache so I unfortunately have no idea what's going on here.
