### ISSUE TITLE
Hints in CSV export/import

### ISSUE THREAD

**Issue by bkimminich** [CTFd/CTFd#2038]
We're currently working on a generator for @juice-shop challenges for CTFd 3.x and wanted to use the CSV import instead of the full-backup approach we have for CTFd 2.x: https://github.com/juice-shop/juice-shop-ctf/issues/116

It seems we wouldn't be able to import hints with all their functionality this way, as you can't set hint costs for example in the CSV. Or can you and we are just missing some full-scope CSV template other than https://docs.ctfd.io/docs/imports/csv that would specify how to fully declare hints with unlock costs?

**Comment by ColdHeat** [comment]
Yes you're correct that this isn't currently possible through CSV importing as we don't even take in a cost value. https://github.com/CTFd/CTFd/blob/c1a27176b6c8cf59ea72456c8822ac2f91717f00/CTFd/utils/csv/__init__.py#L310

I'll put some thought into how this can be done but I don't know if I want to make the challenge CSV importer some complicated format.

**Comment by bkimminich** [comment]
Hi @ColdHeat!

Sorry for digging up this 🧟 issue, but it seems the native data export that https://github.com/juice-shop/juice-shop-ctf has been using so far, is no a) longer working in at least 3.4 upwards and b) the current 3.6 even tells you that DB imports are not supported in Docker any more.

This seems now really like the best time to move over to the CSV importer instead. It will be easier to generate from my tool and I suspect it to be much more stable. The only downside is the lack of hint cost support. Everything else we could do with the current CSV format or it's nothing we'd really miss (like the hints requiring other hints to be used first).

Attached you find the CSV export of a single Juice Shop challenge I manually created in CTFd 3.6 and then exported the relevant tables:

[x-flags.csv](https://github.com/CTFd/CTFd/files/12473309/x-flags.csv)
[x-hints.csv](https://github.com/CTFd/CTFd/files/12473310/x-hints.csv)
[x-challenges.csv](https://github.com/CTFd/CTFd/files/12473311/x-challenges.csv)
[x-tags.csv](https://github.com/CTFd/CTFd/files/12473312/x-tags.csv)

In the current CSV template format, I could do this to achieve the same minus
* the unsupported hint costs as requested via this issue
* the fact that hints cannot contain commas because it seems not possible to escape them with the used "hint1,hint2,hint3" syntax (I tried wrapping such a hint itself in `"friendly comma-free hint,https://url-hint-also-friendly,""hint, that contains comma"""` but that doesn't work - I will open a dedicated issue for that)

So, this is what I currently use for testing:

```
name,description,category,value,type,state,max_attempts,flags,tags,hints,type_data
API-only XSS,"Perform a <i>persisted</i> XSS attack with <code>&lt;iframe src=\""javascript:alert(&#x60;xss&#x60;)\""&gt;</code> without using the frontend application at all. <em>(This challenge is <strong>not available</strong> on Heroku!)</em> (Difficulty Level: 3)",XSS,450,standard,visible,0,f94113c07b6e82fa8ba90369088818711423838a,Danger Zone,"You need to work with the server-side API directly. Try different HTTP verbs on different entities exposed through the API.,https://pwning.owasp-juice.shop/part2/xss.html#perform-a-persisted-xss-attack-without-using-the-frontend-application-at-all",
```

I think you could add hint costs without making the format very complicated, by just having an additional `hint_costs` column which expected costs in `cost_single_hint` or `"cost_hint1,cost_hint2_cost_hint3"` format like you did it with hints, flags and tags. So, my example would become:

```
name,description,category,value,type,state,max_attempts,flags,tags,hints,hint_costs,type_data
API-only XSS,"Perform a <i>persisted</i> XSS attack with <code>&lt;iframe src=\""javascript:alert(&#x60;xss&#x60;)\""&gt;</code> without using the frontend application at all. <em>(This challenge is <strong>not available</strong> on Heroku!)</em> (Difficulty Level: 3)",XSS,450,standard,visible,0,f94113c07b6e82fa8ba90369088818711423838a,Danger Zone,"You need to work with the server-side API directly. Try different HTTP verbs on different entities exposed through the API.,https://pwning.owasp-juice.shop/part2/xss.html#perform-a-persisted-xss-attack-without-using-the-frontend-application-at-all","0,90",
```

**Comment by bkimminich** [comment]
If it helps, here is a test export from Juice Shop that works fine with CTFd 3.6:
[OWASP_Juice_Shop.2023-08-31.CTFd.csv](https://github.com/CTFd/CTFd/files/12480872/OWASP_Juice_Shop.2023-08-31.CTFd.csv)

And here an example with the hint costs as proposed above. If it's implemented differently, no problem - it's just as a playground example for you:
[OWASP_Juice_Shop.2023-08-31.CTFd_with_hint_costs.csv](https://github.com/CTFd/CTFd/files/12480877/OWASP_Juice_Shop.2023-08-31.CTFd_with_hint_costs.csv)

**Comment by ColdHeat** [comment]
I will work on this as I have the time. I recently had a need for the Juice Shop CLI and I was pretty happy with the import zip but I recognize that the CSV is likely easier.

**Comment by bkimminich** [comment]
https://www.npmjs.com/package/juice-shop-ctf-cli v10.0.0 was just released and it will generate CSV files for CTFd now. They work on CTFd 3.6 for me. The code to generate an additional column for the hint costs is already prepared and just needs to be commented in once your release 3.7 drops. Just give me a ping please, when that happens and I'll adjust our tool to match the column name, formart and position you ended up with.
