### ISSUE TITLE
Optional css source selection for offline and online instances

### ISSUE THREAD

**Issue by chateaulav** [CTFd/CTFd#2048]
**Environment**:

- CTFd Version/Commit: `3.4.0`
- Operating System: `Ubuntu 20.04`
- Web Browser and Version: `Any Current`

**What happened?**
Be default css for fonts is pulled from cdn url's, and while there is a fallback for offline it takes about `30 secs` for your browser to track that it has no access to those url's for it to then fallback to the offline css. Then, rinse and repeat for every page that needs to load.

**What did you expect to happen?**
immediate fallback, if not a `2 sec` timeout to ensure that performance is not hindered on the client side.

**How to reproduce your issue**
Host a capture the flag within a controlled environment where open web access is not permitted on the client systems that have direct access to the CTFd server. Example being:

- 20 physical laptops (providing internet and user access to environment)
- 20 virtual systems (located in cyber range, with limited or no internet access allowed)
- 1 CTFd server (located in cyber range, having or not having internet access is not applicable)
- CTFd server is only accessible to the virtual systems, which causes the client-side issue of the css loading

**Any associated stack traces or error logs**

related issue: #76 
related issue: #77

These are the locations where external cdn urls are provided. removing them directly will only load offline which is fine, but potentially adding a variable that can be set to toggle what css you want may be better for more general use and applicability.

`CTFd/themes/core/assets/css/fonts.scss`
```
@import url("https://use.fontawesome.com/releases/v5.9.0/css/all.css");
@import url("https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Raleway:400,400i,700,700i&subset=latin-ext");
```

`CTFd/themes/core/static/css/fonts.dev.css`
```
@import url(https://use.fontawesome.com/releases/v5.9.0/css/all.css);
@import url(https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Raleway:400,400i,700,700i&subset=latin-ext);
```

`CTFd/themes/core/static/css/fonts.min.css`
```
@import url(https://use.fontawesome.com/releases/v5.9.0/css/all.css);@import url(https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Raleway:400,400i,700,700i&subset=latin-ext);
```

**Comment by ColdHeat** [comment]
Thank you for creating this new issue!

I think a switch is probably more work than is necessary. I think best practice now is to serve the assets yourself since I don't think browsers don't share assets between sites anymore. I'm okay with just serving all assets directly from CTFd.
