### ISSUE TITLE
Error code:500 | An Internal Server Error Has Occurred

### ISSUE THREAD

**Issue by pritam2k** [CTFd/CTFd#2057]
Infra is still live on https://foobar.nitdgplug.org

Don't know what's crashing, but the server returns 500 internal error, here and there. Challenges doesn't load in one go, graph of the scoreboard doesn't work in one go. Exporting also returns 500. Moreover using ctfcli to upload the challenges automatically also returns 500 internal server error.

Current spec of server: 8vCPU in GCP with 8GB RAM. Ubuntu 20.something that is on GCP.

Total number of registered users: a little more than 1K

Workers: 8 (specified in docker-compose). Other settings are at their default values. 

The error doesn't come from NGINX, it is able to handle the requests quite well.

How can I resolve this issue?

**Comment by ColdHeat** [comment]
There are a number of possible things it could be, it's not possible to tell without looking at the server directly. Increase your worker count, increase the size/connection limit of MySQL, use redis, etc.

**Comment by pritam2k** [comment]
Is there any parameters I can add in docker-compose file to increase mysql
max connection limit?

**Comment by sunset-move** [comment]
CTFd3.5.0 Exported data.zip Imported data.zip shows Internal Server Error is there a solution?

**Comment by pavansarvesh** [comment]
i'm getting the same issue
