### ISSUE TITLE
challenge description nor rendering html/markdown/text

### ISSUE THREAD

**Issue by GoCode0** [CTFd/CTFd#2071]
**Environment**:

- CTFd Version/Commit:3.4.3
- Operating System:
- Web Browser and Version:

**What happened?**
After configuring challenges, the challenges do not render at all the description html/markdown.
**What did you expect to happen?**
To see the challenge description
**How to reproduce your issue**
Run server with : docker-compose up
**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Can you try docker-compose build and then docker-compose up again? I suspect you are using an outdated version of CTFd.

**Comment by GoCode0** [comment]
I'm sorry, this is stupid. Because when I used zip source code, it worked fine!
