### ISSUE TITLE
error at py serve.py

### ISSUE THREAD

**Issue by Nokenter** [CTFd/CTFd#2080]
Traceback (most recent call last):
  File "C:\Users\sheenon\Downloads\CTFd-3.4.3\CTFd-3.4.3\serve.py", line 21, in <module>
    from CTFd import create_app
  File "C:\Users\sheenon\Downloads\CTFd-3.4.3\CTFd-3.4.3\CTFd\__init__.py", line 9, in <module>
    from flask.helpers import safe_join
ImportError: cannot import name 'safe_join' from 'flask.helpers' (C:\Users\sheenon\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py)

**Comment by ColdHeat** [comment]
Have you installed the versions of dependencies specified in `requirements.txt`? `pip install --force -r requirements.txt` ?

**Comment by Nokenter** [comment]
> Have you installed the versions of dependencies specified in `requirements.txt`? `pip install --force -r requirements.txt` ?

Yes.

**Comment by ColdHeat** [comment]
Python 3.10 doesn't actually seem to have many differences from other Python versions in terms of requirements. 

I think you will need to try running CTFd on a Linux environment or via Docker.

**Comment by ColdHeat** [comment]
I bumped the Python version in use to 3.9. I suspect this issue is elsewhere rather than in CTFd but if you can find out what the root cause of the issue is let me know and I will patch.
