### ISSUE TITLE
Incorrect {url} when behind a reverse proxy

### ISSUE THREAD

**Issue by huornlmj** [CTFd/CTFd#2098]
**Environment**:

- CTFd Version/Commit: Docker image sha256:66fecddf2c759b1b0a77be45ace471f99e1f526217ea3ff2ac3ed8d0f6010294
- Operating System: Linux Ubuntu 22.04 LTS
- Web Browser and Version: Vivaldi N/A
- Docker run command: `docker run -d --restart unless-stopped -p 127.0.0.1:8000:8000 ctfd/ctfd`
- Docker exposed port to 127.0.0.1:8000, with an nginx reverse proxy connecting TCP:443 to 127.0.0.1:8000.
- Host name is ctf.domain.local

**What happened?**
When account activation emails are sent then {url} is http://127.0.0.1:8000/xxxxxxxxxxx, and not https://ctf.domain.local/xxxxxxxxxxx

**What did you expect to happen?**
https://ctf.domain.local/xxxxxxxxxxx, or at least know what to configure to provide a custom URL to the docker image.

How to I provide the proper URL to the docker container version of CTFd?

**Comment by huornlmj** [comment]
Update - I see the solution in #1288 works for me, but I do not know how to introduce the `REVERSE_PROXY = True` into the container via a docker run command line?  I had to manually edit the config.ini in the running container.  If I scrap the container and make a new one then I lose the setting.

**Comment by ColdHeat** [comment]
Did you see this line at the top of `config.ini`? 

https://github.com/CTFd/CTFd/blob/b9b7de77bd5c720c2f32b3abb71e5dfcc1899f85/CTFd/config.ini#L8

Use `-e` to set an envvar: https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file. In this case `-e REVERSE_PROXY=true` should work.
