### ISSUE TITLE
Is the same salt used for all user accounts?

### ISSUE THREAD

**Issue by huornlmj** [CTFd/CTFd#2101]
Running latest version of CTFD docker container.  The ctfd.db file passwords all start with what appears to be a shared salt, rather than a different salt per account.  Is this true?

**Comment by ColdHeat** [comment]
No it's not true at all, how did you come to that conclusion? 

Password hashing function: 
https://github.com/CTFd/CTFd/blob/b9b7de77bd5c720c2f32b3abb71e5dfcc1899f85/CTFd/utils/crypto/__init__.py#L8

The format used by the passlib function: 
https://passlib.readthedocs.io/en/stable/lib/passlib.hash.bcrypt_sha256.html#format

```
Version 1 of this format had the format $bcrypt-sha256$type,rounds$salt$digest
```

**Comment by huornlmj** [comment]
I opened the ctfd.db SQlite database file and looked at the passwords.  I saw bcrypt-sha256, followed by what I expect were $ delimeters.  And the first chunk after bcrypt-sha256 was the salt. But it was the same salt for all of the user accounts!  And a very small salt too.
