### ISSUE TITLE
CTFd behind reverse proxy sending http://<host:443/> redirects (http to a https port)

### ISSUE THREAD

**Issue by huornlmj** [CTFd/CTFd#2111]
**Environment**:

- CTFd Version/Commit: CTFd Docker image:latest sha256:d84063acb83fa8a8e0bfb28860aa9bd64b7fcecde4011cc92c635831f8b7bc8a
- Operating System: Ubuntu 22.04 LTS
- Web Browser and Version: N/A
- Architecture:  CTFd running on http://127.0.0.1:8000/ behind nginx as reverse proxy.  REVERSE_PROXY=true set, and using the provided CTFd nginx conf which is providing TLS termination.

**What happened?**
Visiting https://server works.  Then use the login link.  I am then redirected to http://server:443/ which yields an nginx error:
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

**What did you expect to happen?**
I expected to continue on using https://server/ URLs (https to the correct port) with no errors.

**Any associated stack traces or error logs**
To rule out nginx as the culprit I grabbed a tcpdump on the docker0 interface to watch the traffic between the nginx reverse proxy and the http://127.0.0.1:8000 endpoint, as it was in plaintext I could read it.  The gunicorn server responds with the bad redirect, not nginx.  Nginx just passes it back to the user:

**CLIENT POST**
```
POST /login HTTP/1.0
X-Real-IP: [REDACTED IP]
X-Forwarded-For: [REDACTED IP]
X-Forwarded-Host: [REDACTED HOSTNAME]
X-Forwarded-Port: 443
Host: 127.0.0.1:8000
Connection: close
Content-Length: 126
Cache-Control: max-age=0
sec-ch-ua: "Chromium";v="100", " Not A;Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Origin: https://[REDACTED HOSTNAME]
Upgrade-Insecure-Requests: 1
DNT: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://[REDACTED HOSTNAME]/login
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: session=[REDACTED COOKIE]

name=[REDACTED USERNAME]&[REDACTED PASSWORD]=[REDACTED]&_submit=Submit&nonce=[REDACTED NONCE]
```
**GUNICORN RESPONSE**
```
HTTP/1.0 302 FOUND
Server: gunicorn/20.0.4
Date: Wed, 04 May 2022 07:26:03 GMT
Connection: close
Content-Type: text/html; charset=utf-8
Content-Length: 229
Location: http://[REDACTED HOSTNAME]:443/challenges
Set-Cookie: session=[REDACTED COOKIE]; Expires=Wed, 11-May-2022 07:26:03 GMT; HttpOnly; Path=/; SameSite=Lax

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/challenges">/challenges</a>.  If not click the link.
```
Note the line from gunicorn in the response: **Location: http://[REDACTED HOSTNAME]:443/challenges**

**Comment by ColdHeat** [comment]
Your nginx config is likely missing the header to tell CTFd that it's operating behind HTTPS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto.

**Comment by huornlmj** [comment]
@ColdHeat I'm not sure it's nginx's fault here as I'm using an nginx config taken from some documentation at this site.  Also as you can see it's the CTFd container's gunicorn that's sending back the wrong link.  Do you perhaps have a working version using nginx with TLS as reverse proxy for the CTFd containerized version?

**Comment by huornlmj** [comment]
Why was this closed?  It's not resolved.!?  Can you re-open it please.  You may find it could have something to do with https://github.com/CTFd/CTFd/issues/987

**Comment by huornlmj** [comment]
This is my nginx default site configuration

```
server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        ssl_certificate /etc/ssl/certs/cert.crt;
        ssl_certificate_key /etc/ssl/private/cert.key;
        ssl_prefer_server_ciphers on;
        server_name _;
        location / {
                proxy_pass http://127.0.0.1:8000/;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;
        }
}
```

**Comment by ColdHeat** [comment]
This issue is almost always related to nginx configuration error. If you can prove in code where CTFd is doing something wrong I will re-open. Keep in mind this is a bug tracker for CTFd, not a support forum. 

Try the following:

```
proxy_set_header X-Forwarded-Proto https;
```

I do not think `$http_x_forwarded_proto` is standard and everything online seems to suggest it proxies the header from the client which is the wrong behavior.

**Comment by huornlmj** [comment]
> This issue is almost always related to nginx configuration error. If you can prove in code where CTFd is doing something wrong I will re-open. Keep in mind this is a bug tracker for CTFd, not a support forum.

Is there a support forum you can share with me?
