### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by vFREE-1** [CTFd/CTFd#2112]
**Environment**:

- CTFd Version/Commit: 3.4.0
- Operating System: centos 7.1
- Web Browser and Version: edge/google/firefox

**What happened?**
  Hello, there is a small problem that needs to be raised to you. After restarting the server, an error 502 bad gateway will be reported when you visit it again. I hope you can get a solution

**What did you expect to happen?**
A solution

**How to reproduce your issue**
A solution

**Comment by ColdHeat** [comment]
Needs more details, can't reproduce.
