### ISSUE TITLE
The mail service is not available

### ISSUE THREAD

**Issue by vFREE-1** [CTFd/CTFd#2114]
**Environment**:

- CTFd Version/Commit:3.4.0
- Operating System:centos
- Web Browser and Version: google/edge/forefox...

**What happened?**
> Hello, excuse me, I'm using ctfd 3.4.0. It seems that SMTP is configured, but I still can't send mail. I hope I can get a solution from you. Thank you
and I use Netease 163 mailbox and the server is SMTP 163.com, port 465, using SSL Protocol

**What did you expect to happen?**
> Send mail normally

**How to reproduce your issue**
> Hope to get a solution

**Comment by ColdHeat** [comment]
Please review your SMTP settings as this can't be reproduced.
