### ISSUE TITLE
aws s3 not working with specific providers (need to add a parameter)

### ISSUE THREAD

**Issue by mh4ckt3mh4ckt1c4s** [CTFd/CTFd#2115]
**Environment**: Docker / Kubernetes

- CTFd Version/Commit: 3.4.3
- Operating System: Linux
- Web Browser and Version: Firefox v99

**What happened?** 
When I configured the aws s3 storage with OVH as the cloud provider, the configuration was not working. I thought it was a problem of boto3 (https://github.com/boto/boto3/issues/3258) but the problem was not on their side. As the issue shows, using the `region_name` in boto3 fixes the issue. However in CTFd, it is currently no possible to parameter this value.

**What did you expect to happen?**
aws s3 configuration is working.
 
**How to reproduce your issue**
Try to setup a CTFd with an OVH s3 endpoint (or just try with boto3 directly as shown in the boto3 issue). I am not sure was is really causing the issue, but this problem could exist with a lot of other cloud providers. Also, setting the `region_name` parameter is good practice and will generally help reducing bugs.  

**Any associated stack traces or error logs**
The error in the CTFd logs is the same as the one shown in the boto3 issue. The issue is in the `uploaders.py` file.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
I succeeded in fixing this issue in my own private CTFd fork (not available in public) in a very hacky way, but I think I'll be able to submit a PR before the end of the summer. If you're validating the issue and want a specific milestone to fix this issue in, let me know so I can try to make the PR on time.

**Comment by ColdHeat** [comment]
Closed in #2188
