### ISSUE TITLE
Not sending email with smtp-relay.gmail.com

### ISSUE THREAD

**Issue by childrda** [CTFd/CTFd#2117]
**Environment**:

- CTFd Version/Commit: 3.4.1
- Operating System: Ubuntu 20.04
- Web Browser and Version: Chrome  101.0.4951.41

**What happened?**
Not sending emails.  No error messages.

**How to reproduce your issue**
I used the following in my mail server settings:
smpt@lcps.k12.va.us
smtp-relay.gmail.com
port 465
SSL

I did mannually connect ussing openssl and was able to send a sample email from this server.

**Any associated stack traces or error logs**
My CTFd log folder is empty.  Does the system track any returned error messages?
![ctfd-email](https://user-images.githubusercontent.com/100962032/167729745-5cf2e8cc-5f45-4292-bfc8-ddcf34a40f14.PNG)
![ctfd-emaillog](https://user-images.githubusercontent.com/100962032/167730018-c22070bc-8d78-4b3c-b533-857899e75a10.PNG)

**Comment by childrda** [comment]
This is a docker install.

**Comment by Matir** [comment]
Your mail server address shows "smpt", not "smtp".

**Comment by ColdHeat** [comment]
I can only recommend that you double check your configuration. Perhaps check mail server address as mentioned above.
