### ISSUE TITLE
500 when calling `api/teams/me` under user mode

### ISSUE THREAD

**Issue by frankli0324** [CTFd/CTFd#2119]
**Environment**:

- CTFd Version/Commit: 3.5.0
- Operating System: irrelevant
- Web Browser and Version: irrelevant

**What happened?**

`curl /api/v1/teams/me --with-cookie -i` > 500 Internal Server Error

**What did you expect to happen?**

`{"success": False, "message": "proper reason"}`

**Any associated stack traces or error logs**

https://github.com/CTFd/CTFd/blob/6d74c1c4267b4dc395949a65331c369e0737d16f/CTFd/api/v1/teams.py#L262-L270

```log
ctfd_1     |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 87, in authed_only_wrapper
ctfd_1     |     return f(*args, **kwargs)
ctfd_1     |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 153, in require_team_wrapper
ctfd_1     |     return f(*args, **kwargs)
ctfd_1     |   File "/opt/CTFd/CTFd/api/v1/teams.py", line 269, in get
ctfd_1     |     response.data["place"] = team.place
ctfd_1     | AttributeError: 'NoneType' object has no attribute 'place'
```

**Comment by ColdHeat** [comment]
Interesting... I see that this route does have the `require_team()` decorator so I feel like this shouldn't happen. 

https://github.com/CTFd/CTFd/blob/6d74c1c4267b4dc395949a65331c369e0737d16f/CTFd/api/v1/teams.py#L251

I would accept a PR for this if you can track it down.

**Comment by frankli0324** [comment]
> Interesting... I see that this route does have the `require_team()` decorator so I feel like this shouldn't happen.
> 
> https://github.com/CTFd/CTFd/blob/6d74c1c4267b4dc395949a65331c369e0737d16f/CTFd/api/v1/teams.py#L251
> 
> I would accept a PR for this if you can track it down.

`require_team` doesn't assert team mode, `require_team_mode` does.

**Comment by frankli0324** [comment]
yeah it should though, simple fix
