### ISSUE TITLE
Disable Imports on SQLite database provider

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#2131]
I don't really want to implement support for migrations on SQLite. Self hosted users should use docker-compose instead of just the Docker image. So I'd rather simply disallow imports if you're using SQLite.

**Comment by ColdHeat** [comment]
Related Issues: #2121, #2130

**Comment by huornlmj** [comment]
@ColdHeat who maintains the current public Docker image?  Is it this group or an independent 3rd party?  if it's this group then I would suggest removing SQlite from the Docker image if a more robust RDMS is required for upgrade capability.

Also by any chance is this related to https://github.com/CTFd/CTFd/issues/2130 or https://github.com/CTFd/CTFd/issues/2121 ?
