### ISSUE TITLE
More user information should be included in user mode scoreboard export

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#2133]
User mode scoreboard CSV exports are missing the user IDs as well as user emails. 

https://github.com/CTFd/CTFd/blob/2c32791c241cd9ee6bb3183ed2221154e70a927f/CTFd/utils/csv/__init__.py#L117-L126

**Comment by joelebutler** [comment]
I will work on this later tonight if nobody else has gotten to it yet.

**Comment by ColdHeat** [comment]
Closed by #2136
