### ISSUE TITLE
There is an issue with the CTFd platform's scoreboard.

### ISSUE THREAD

**Issue by dhje0ng** [CTFd/CTFd#2156]
**Environment**:

- CTFd Version/Commit: CTFd/3.5.0
- Operating System: Docker
- Web Browser and Version: Chrome 103.0

**What happened?**
```
scoreboard.min.js?d=963ff4ad:1
GET http://localhost/api/v1/scoreboard/top/10 404 (NOT FOUND)
```

This error occurs when the score display mode in the admin page is set to Private.

**What did you expect to happen?**
When the error is fixed, the scoreboard graph should be displayed normally.
In addition, if I use a different theme to apply the theme, the scoreboard page itself throws a 404 error.

**How to reproduce your issue**
I don't know.. I'm stumped as to where the platform configuration went wrong.

**Any associated stack traces or error logs**
<img width="1512" alt="스크린샷 2022-07-31 오후 8 55 25" src="https://user-images.githubusercontent.com/50125695/182025159-196a2e64-c782-499e-8d52-438f4e691005.png">

<img width="1511" alt="스크린샷 2022-07-31 오후 8 55 48" src="https://user-images.githubusercontent.com/50125695/182025173-df9fe05e-3ff9-4f34-883d-e793b9540a9f.png">

**Comment by dhje0ng** [comment]
The aforementioned problem only affects regular user accounts, not administrators.

Sign up for a regular account and set the score display mode to Private on the admin page to reproduce the problem.

**Comment by ColdHeat** [comment]
Score Visibility and Account Visibility should generally be set to the same value. You have them set to "Private" and "Admins Only". 

The scoreboard page reveals both Accounts and Score so having them set to conflicting values results in odd behavior like what you're seeing.
