### ISSUE TITLE
Hints nonfunctional unless logged in

### ISSUE THREAD

**Issue by arxenix** [CTFd/CTFd#2157]
**Environment**:

- CTFd Version/Commit: 3.5.0
- Operating System: any
- Web Browser and Version: any

**What happened?**
Clicking on a hint while being signed out does absolutely nothing. This makes it seem like the website is nonfunctional.

**What did you expect to happen?**
Hints with no cost should be viewable without being signed in. If the hint has a cost, an error/alert telling the user to sign in should be displayed.

**How to reproduce your issue**
Have a CTFd instance with the challenges page public, attempt to click on a challenge hint.

**Comment by ColdHeat** [comment]
I thought this would be a straightforward UI change but this is actually an issue inside of the API since it needs to return hint data when users aren't authenticated. This is a bigger change than it looks so it could take some time.

**Comment by arxenix** [comment]
yeah, for now I think a good alternative would be to simply tell the user they must be logged in to view a hint.
