### ISSUE TITLE
Custom Plugin custom form page 403 when clicking submit button

### ISSUE THREAD

**Issue by jkaufman-LogRhythm** [CTFd/CTFd#2165]
**Environment**:

- CTFd Version/Commit: Latest
- Operating System: Centos 7
- Web Browser and Version: Firefox latest

**What happened?**

(Update) Another work around ask is how can I make a plugin modify the notifications api to have additional functionality? It is what I used for the work around in the past but was manually editing the images file prior to running the docker image ***

Problem:
Rendered a custom html page under admin: `admin/association`
Page loads I see the form, I added a submit button to hit the update. I read you need to have this nounce input that is hidden, copied it above the submit.

When I click submit I get a 403 saying forbidden, I was told that to prevent this you add above submit:
`<input type="hidden" value="{{ nonce }}" name="nonce" id="nonce" />`

Actual error message, "Forbidden
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
"

I am attempting for it to do some backend sql work upon submission. I used to inject a custom api in the load of notifications api, but because the docker container is having every file read only I cannot mod that file like I used to.

**What did you expect to happen?**
blueprint.py to his the update POST form which looked like this:

`@plugin_bp.route(plugin_route, methods=["POST"])
def update_config():
	print('submission was hit')`

```
plugin_bp = Blueprint("plugin_name_folder", __name__, template_folder="templates")

I have the html in the templates folder, blueprint.py and controller.py are at root level of plugin
```
**How to reproduce your issue**
Might be easier to hop on a teams call

**Any associated stack traces or error logs**
 "POST /admin/association HTTP/1.1" 403 7109 "http://localhost:8000/admin/association" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"

**Comment by ColdHeat** [comment]
`{{ nonce }}` should probably be `{{ Session.nonce }}` but we should definitely document that better.

**Comment by jkaufman-LogRhythm** [comment]
That was it! I had to remove the POST from the get call that navigated to to the custom html page.

Just encase from blueprint I can also mod standard users notification page plus the registration page? Those are the final peaces, the notification has just an additional jinja that pull from the custom sql table

**Comment by ColdHeat** [comment]
CTFd plugins can override almost any behavior in CTFd. Overriding templates is a supported use case.

**Comment by jkaufman-LogRhythm** [comment]
That is great to hear, final query I know that plugins overrides, would it override literally all functionality? I noticed my plugin will require a db check for when user is logged in for some specific details that Jinja checks for

**Comment by ColdHeat** [comment]
I don't understand what you're refering but CTFd plugins are just Python code so you can use a lot of the code that CTFd itself uses.

**Comment by jkaufman-LogRhythm** [comment]
No worries, so the concern I have at this point is getting the plugin to alter the standard users notifications page `GET /notifications`

so I know the plugin is loading at load, I added this prior to blueprint

```
def load(app):    
    print('loading assets')
    register_plugin_assets_directory(app, base_path=f'/plugins/my_plugin_name/assets/')
    
    # Setup Association Table if not existing & functionality
    check_db(app)
    #check_files()

    # Handle normal notifications page this must be before app.register_blueprint(bp)
    @app.route('/notifications', methods=['GET'])
    def view_notif():
        print('Loading Custom Notification Page for Association')
        return render_template("notifications.html")

    # Load default configuration then register blueprint
    ConfigController.load_default()
    bp = load_bp(CONFIG["route"])
    app.register_blueprint(bp)
```


How can I get it to alter notifications beside manually replacing the file?

**Comment by ColdHeat** [comment]
Isn't this documented in https://docs.ctfd.io/docs/plugins/overview#modifying-existing-routes?

**Comment by jkaufman-LogRhythm** [comment]
yes I did try that too however it is not hitting the function or the blueprint function:

```
    # Handle normal notifications page this must be before app.register_blueprint(bp)
    #@my_plugin_bp.route("/notifications", methods=["GET"])
    #@app.route("/notifications")
    def nu_notifications():
        print('Loading Custom Notification Page for Association')
        return render_template("notifications.html")
        #return render_template("notifications.html", notifications=notifications)

    # add notification blueprint
    app.view_functions['notifications.notifications_view'] = nu_notifications
    app.url_map.add(Rule('/notifications', endpoint='notifications.notifications_view', methods=['GET', 'POST']))

```

**Comment by MilyMilo** [comment]
@jkaufman-LogRhythm 

In your code you're using `notifications.notifications_view` as the endpoint, whereas this route should be `views.notifications` - https://github.com/CTFd/CTFd/blob/master/CTFd/views.py#L298
