### ISSUE TITLE
NO SUPPORT FOR ARCH BASED DISTROS 

### ISSUE THREAD

**Issue by Seew0** [CTFd/CTFd#2180]
**Environment**:

- CTFd Version/Commit:
- Operating System:
- Web Browser and Version:

**What happened?**
i was using the prepare.sh file on my linux machine

**What did you expect to happen?**
i expected it to work but unfortunately its only available for debian based distros
give me access to update the prepare.sh script for arch based distros

**Comment by ColdHeat** [comment]
The primary image will be Debian based. In my experience Alpine has introduced weird issues and didn't benchmark as well as Debian. You are free to run CTFd via Docker or use your own installation script. There won't be an installation script for every distro.
