### ISSUE TITLE
Health check fails on / despite app being online

### ISSUE THREAD

**Issue by userbradley** [CTFd/CTFd#2214]
**Environment**:

- CTFd Version/Commit: Latest Docker
- Operating System: Latest Docker
- Web Browser and Version: N/A

**What happened?**
When running the application in Kubernetes for the first time, the `/` url 302 redirects to `/setup` which causes the Health chek to fail 

**What did you expect to happen?**

Application would return `200` on `/` [KB](https://cloud.google.com/load-balancing/docs/health-check-concepts#criteria-protocol-http:~:text=HTTP%20200%20(OK)%20status.)

**How to reproduce your issue**

Create application in GKE using below health check for `backendConfig`

**Any associated stack traces or error logs**

```text
1. 172.17.2.1 - - [03/Nov/2022:22:14:15 +0000] "GET /setup HTTP/1.1" 200 15200 "-" "kube-probe/1.24"
2. 35.191.12.160 - - [03/Nov/2022:22:14:20 +0000] "GET / HTTP/1.1" 302 219 "-" "GoogleHC/1.0"
3. 35.191.12.162 - - [03/Nov/2022:22:14:20 +0000] "GET / HTTP/1.1" 302 219 "-" "GoogleHC/1.0"
4. 35.191.12.164 - - [03/Nov/2022:22:14:20 +0000] "GET / HTTP/1.1" 302 219 "-" "GoogleHC/1.0"
```

Line 1 shows the k8 health check that follows redirects 

Line 2-4 shows the Google HC that does not, and fails.

** What I would like to see **

A `/health` or `/halthz` page that returns `http status 200` when the application is running and can connect to the DB regardless of if a user has completed the setup 

[KB on /healthz](https://kubernetes.io/docs/reference/using-api/health-checks/)

---

Let me know if you would like some additional details around this, or more details/ better explanation!

**Comment by ColdHeat** [comment]
Thanks for reporting this. If you have the time you could probably solve this by adding "views.healthcheck" to this area here: https://github.com/CTFd/CTFd/blob/a085d0922a6e730c5c479869637a0335fe108bb7/CTFd/utils/initialization/__init__.py#L200.

**Comment by userbradley** [comment]
Thanks @ColdHeat, I've opened a PR with testing attached

https://github.com/CTFd/CTFd/pull/2215

Any issues please let me know!
