### ISSUE TITLE
Multiple types of decay functions

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#2224]
We should implement multiple types of decay functions for dynamic value challenges so that people can choose how to handle the valuation. I now think that the better default to have is linear because people can reason about it easier.

**Comment by frankli0324** [comment]
Is their a possibility that CTFd could make challenge scoring apart from the challenge itself, like what "flags" did?

**Comment by ColdHeat** [comment]
It is possible but I have not put much thought into it. There should be a ticket for it elsewhere. However for this issue I think there could just be a column that lets the admin choose between `logarithmic` and `linear`.
