### ISSUE TITLE
Database URLs not compatible with some deployment methods

### ISSUE THREAD

**Issue by SmylerMC** [CTFd/CTFd#2231]
The way database and Redis settings are passed as a single URL isn't really modular and may cause problems in some cloud deployments.

For example, when deploying on Kubernetes, I might have my database host, port, username and password stored in separate configuration objects shared with other deployments (typically the database deployment). With the current configuration settings, I have to store the same values in different configuration objects because I need to provided them to CTFd as one URL.
It would be simpler if I could map each configuration value to a separate environment variable for CTFd.

Said variables could be
- `DATABASE_PROTOCOL`
- `DATABASE_HOST`
- `DATABASE_PORT`
- `DATABASE_USER`
- `DATABASE_PASSWORD`
- `DATABASE_NAME`

Forward compatibility could be kept by simply falling back to `DATABASE_URL` if the configuration is invalid.

I don't know whether such a change would be acceptable ? If so, I could implement it myself if needed.

**Comment by ColdHeat** [comment]
I believe I have run into this before so it's not unreasonable. I have seen people work around it but I could see us support the idea.

I would accept a PR for this. I would still prioritize the `DATABASE_URL` but if that is omitted it can load  the envvars you are suggesting.
