### ISSUE TITLE
DATABASE_* configuration keys broken in Docker

### ISSUE THREAD

**Issue by SmylerMC** [CTFd/CTFd#2248]
**Environment**:

- CTFd Version/Commit: fe9ba03
- Operating System: Linux / Any
- Web Browser and Version: Irrelevant

**What happened?**
Starting a Docker version of CTFd with a database configured using the new `DATABASE_*` configuration keys, CTFd never starts and is stuck at the output `Waiting for ctfd-test-mysql to be ready `.

**What did you expect to happen?**
CTFd should detect the database and start.

**How to reproduce your issue**
Start a CTFd docker image and a non-sqlite database.

**Reason**
The docker startup script starts by calling `ping.py`, which waits for the database to be available, but does so using only the `DATABASE_URL` configuration option, and does not take into account the new `DATABASE_*` options.

**Comment by SmylerMC** [comment]
That was an error on my part, apologies for the confusion.

**Comment by mortenson** [comment]
@SmylerMC What did you end up changing to fix this?

**Comment by SmylerMC** [comment]
> @SmylerMC What did you end up changing to fix this?

My memory is failing as to what the exact problem was, but I believe it was a configuration mistake on my part (I potentially had both `DATABASE_URL` and other `DATABASE_...` variables setup, and `DATABASE_URL` takes precedence). Sot not an issue with CTFd, which is why the issue was closed.

Troubleshooting database problems in container deployments can be a bit tricky because the init script will hide errors by default, but you can get around that, watch it crash and get the error message by setting `SKIP_DB_PING=true` in your env (see #2342 ).
