### ISSUE TITLE
main page

### ISSUE THREAD

**Issue by rached64** [CTFd/CTFd#2251]
hello , I am trying to personalize CTFd , in the main page i would like to delete this content
![image](https://user-images.githubusercontent.com/52635469/215541251-b5c5da2a-c798-4c00-946c-476c94e5ca26.png)
i don’t find exactly where is it located ?
in **view.py** i find the code of it but When I try to delete or modify it, I don’t see any changes? Is there a way to fix this issue?

**Comment by ColdHeat** [comment]
You can modify this content in the Admin Panel in the Pages section. See https://docs.ctfd.io/tutorials/pages/creating-new-pages#page-editor.
