### ISSUE TITLE
Bump depenencies to more recent versions

### ISSUE THREAD

**Issue by ukaeufe** [CTFd/CTFd#2300]
**Environment**: localhost

- CTFd Version/Commit: latest
- Operating System: Linux / Mac
- Web Browser and Version:

**What happened?**
I want to install a plugin that uses flask-dance. The latest flask dance depends on flask 2.0.3 while CTFd requires flask 1.1.2.
So I get a conflict when installing the plugin.

**What did you expect to happen?**
Upgrade ctfd to a newer flask >= 2.0.3

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
We need to try to upgrade dependencies to latest version if possible for us.
