### ISSUE TITLE
forgot email does not sent

### ISSUE THREAD

**Issue by Gary827** [CTFd/CTFd#2307]
**Environment**:

- CTFd Version/Commit: 3.5.0
- Operating System: Docker Container on Linux
- Web Browser and Version: Chrome 113.0.5672.127

**What happened?**
We set up the Email server(we have used in many production environemnt) in admin panel and we click the forgot password button in the front page, then fill in the registerd email in the field, we got a response said "If that account exists you will receive an email, please check your inbox", after that, we doesn't  get any forgot password email in the mailbox.

**What did you expect to happen?**
Get the forgot password email when we click forgot password in the login page.
**How to reproduce your issue**
fill in a registerd email in the forgot password page.
**Any associated stack traces or error logs**
no error logs

**Comment by ColdHeat** [comment]
Please review your configuration. The email code is tested and heavily used with no other reports of issues.
