### ISSUE TITLE
Delete team member fatal error

### ISSUE THREAD

**Issue by pandatix** [CTFd/CTFd#2311]
**Environment**:

- CTFd Version/Commit: `2474d6000dcaa9bec64d40aebcb8b6818dbe629c`, version `3.5.2`
- Operating System: Linux (6.1.27-1kali1 x86_64)
- Web Browser and Version: `Firefox 102.10.0esr`

**What happened?**

Thanks to a mistake, I emitted the following API call that produced a fatal error.
```bash
curl -X DELETE http://127.0.0.1:4000/api/v1/teams/1/members \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Token 011bd2a24d6cb07895b8328c87dc823f6d1a04e7468c3c32596a2fb1d0fdae22' \
    -d '{"user_id":[1]}'
```

I did not configured the `CTFd/conf.ini` file.

**What did you expect to happen?**

Of course, the sent data model here is invalid as it was not expecting a list, but the stack trace should not be responded.

**How to reproduce your issue**

On any running CTFd, run the previous curl command with a valid API token value. You can  vary the JSON payload as long as it does not comply to the expected data model.

**Any associated stack traces or error logs**

[out.txt](https://github.com/CTFd/CTFd/files/11569811/out.txt)

**Comment by pandatix** [comment]
Targeted code seems to be https://github.com/CTFd/CTFd/blob/master/CTFd/api/v1/teams.py#L472

**Comment by ColdHeat** [comment]
I believe the JSON body thats required here is `{"user_id": 1}`

**Comment by pandatix** [comment]
Yes it is supposed to be such, but isn't there a way to validate the JSON payload before using it ? Currently, it could illustrate CWE-20.
If it happens in production it floods the logs making it harder to circumvent an attack or debug.

**Comment by pandatix** [comment]
In this commit I suggest a way to handle those cases, when `marshmallow` can't do its job due to the plugin system.
I'm a beginner with this technology and CTFd internals, feel free to suggest a way to do it better if any.

The core concept is to check whether the attribute value we try to set is valid or not, by checking whether or not it could be converted before setting it. We could imagine checking other attributes, such as the `type` (currently, we could set to to whatever string we want, producing an Internal Server Error with an uncatched `KeyError`).
In the commit example, if is is a `float` or an `int` you could convert to a `float`, then update the value so the SQL query will work.

I applied it on another endpoint and payload, so you could see this issue is spread around the whole CTFd API.
