### ISSUE TITLE
Does the API for file uploading actually work ?

### ISSUE THREAD

**Issue by adb014** [CTFd/CTFd#2348]
**Environment**:

- CTFd Version/Commit:  Version 3.5.3
- Operating System:  Debian Bullseye
- Web Browser and Version: (Python Requests and Curl)

**What happened?**

Attempted to use the /api/v1/files to upload a file and after a day of trying everthing I can think of no luck. Tested via two differents means. Firstly with curl and the code

```
curl -X POST --header "Authorization: Token deadbeef......." --header "Content-Type: multipart/mixed" -F "{\"type\": \"challenge\", \"challenge_id\": \"1\"}" -T "test.jpg" http://127.0.0.1:8000/api/v1/files
```

and a few variations of the same (multipart/form-data and using a form for the file uploaded). So I then looked at the code from [ctfcli](https://github.com/CTFd/ctfcli/blob/de3dcee5aef90d2b3a02f2625a623e3e6914903d/ctfcli/utils/challenge.py#L278 ) and tested the code

```
from pathlib import Path
import requests

def post_file(file, chall):
        headers = {"Authorization": f"Token deadbeef....."}
        files = []
        file_path = Path(".", file)
        if file_path.exists():
                file_object = ("file", file_path.open(mode="rb"))
                files.append(file_object)
        else:
                raise Exception(f"File {file_path} was not found")

        data = {"challenge_id": chall, "type": "challenge"}
        # Specifically use data= here instead of json= to send multipart/form-data
        r = requests.post("http://127.0.0.1:8000/api/v1/files", headers=headers, files=files, data=data)
        r.raise_for_status()

post_file("test.jpg", 1)
```

In both case I received a redirect to the login page

**What did you expect to happen?**

Well I expected to see the file uploaded.. I inspected directly the database (postgresql) directly and nothing apperared

**How to reproduce your issue**

Use the code above

**Comment by ColdHeat** [comment]
Yes it works, I have no idea what the issue is with your code though sorry.

**Comment by adb014** [comment]
Can you supply a code or curl example that works for you that I can test ?

**Comment by adb014** [comment]
Ok here is why it doesn't work.. The "api/v1/files" POST API doesn't accept the authorization token without a valid session cookie, and a redirect to the login page.. If I first do a "GET" on the page with the authorization token and then store the session cookie and reuse it I can post to "api/v1/files" I can post files. A simple of what finally worked for me is 

```
#! /bin/sh

_cookie=$(curl -v -X GET --header "Authorization: Token deadbeef....." \
  --header "Content-Type: application/json" http://172.19.0.1:8000/api/v1/files 2>&1 \
  | grep "session" | sed -e "s/^.*\(session=[^;]*\).*$/\1/")

curl -v -X POST --header "Content-Type: multipart/form-data" -b "$_cookie" \
  --header "Authorization: Token deadbeef......." \
  -F "type=\"challenge\"" \
  -F "challenge_id= 1" \
  -F "file=@test.jpg" http://172.19.0.1:8000/api/v1/files
```

It seems to me that the session cookie shouldn't be needed here, so to me this remains a bug.. Note that the post seemed to need both the session cookie and the authorization token.
