### ISSUE TITLE
docker-compose: ModuleNotFoundError: No module named 'flask._compat'

### ISSUE THREAD

**Issue by atastycookie** [CTFd/CTFd#2352]
**Environment**:

- CTFd Version/Commit: `c2eca90b05737fabac178a742b96ff49513f0cc2 (HEAD -> master, origin/master, origin/HEAD)`
- Operating System: Ubuntu 22.04
- Web Browser and Version: N/A

**What happened?**

```
ctfd-ctfd-1   | ..................................db is ready
ctfd-ctfd-1   | Traceback (most recent call last):
ctfd-ctfd-1   |   File "/opt/CTFd/manage.py", line 6, in <module>
ctfd-ctfd-1   |     from flask_script import Manager
ctfd-ctfd-1   |   File "/opt/venv/lib/python3.9/site-packages/flask_script/__init__.py", line 15, in <module>
ctfd-ctfd-1   |     from flask._compat import text_type
ctfd-ctfd-1   | ModuleNotFoundError: No module named 'flask._compat'
ctfd-ctfd-1 exited with code 0
```

**How to reproduce your issue**

```
   git clone https://github.com/CTFd/CTFd.git
   cd  CTFd/
   head -c 64 /dev/urandom > .ctfd_secret_key
   docker compose up
```

**Comment by se-fLa** [comment]
I can confirm this issue, replicated.

**Comment by fareedfauzi** [comment]
Yup, happened to me also

**Comment by ColdHeat** [comment]
I am putting up a quick fix for this at https://github.com/CTFd/CTFd/pull/2353. But I would recommend using the 3.5.3 release in the meantime.

**Comment by atastycookie** [comment]
Сonfirmed, reverting to a previous version fixes the bug (`git checlout 3.5.3`)

**Comment by ReKreker** [comment]
It didn't fixed. I am trying to import backup but saw the same error message.

**Comment by ColdHeat** [comment]
@ReKreker This should now be fixed entirely with the latest commit.
