### ISSUE TITLE
ImportError: No module named flask_caching

### ISSUE THREAD

**Issue by int0x80** [CTFd/CTFd#237]
I am trying to run CTFd on an EC2 instance but receiving an error.

```
~/CTFd$ sudo /home/ubuntu/.local/bin/uwsgi -s /tmp/uwsgi.sock -w "CTFd:create_app()" --uid=www-data --chown-socket=www-data:www-data --auto-procname --daemonize2 /var/log/ctf/ctf.log
*** Starting uWSGI 2.0.15 (64bit) on [Wed Apr  5 04:35:35 2017] ***
compiled with version: 5.4.0 20160609 on 05 April 2017 02:30:04
os: Linux-4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017
nodename: ip-172-31-13-130
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/ubuntu/CTFd
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 128640
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
setuid() to 33
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1fdfea0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72760 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./CTFd/__init__.py", line 11, in <module>
    from CTFd.utils import cache, migrate, migrate_upgrade, migrate_stamp
  File "./CTFd/utils.py", line 21, in <module>
    from flask_caching import Cache
ImportError: No module named flask_caching
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** daemonizing uWSGI ***
```

But the `flask_caching` module is installed.

```
~/CTFd$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from CTFd.utils import cache, migrate, migrate_upgrade, migrate_stamp
>>> from flask_caching import Cache
>>>
```

Also via `sudo`.

```
~/CTFd$ sudo python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from CTFd.utils import cache, migrate, migrate_upgrade, migrate_stamp
>>> from flask_caching import Cache
>>>
```

**Comment by ColdHeat** [comment]
Do things run properly with `python serve.py`?

Also can you try gunicorn instead of uwsgi? 

`gunicorn --bind 0.0.0.0:8000 -w 4 "CTFd:create_app()"`

**Comment by ColdHeat** [comment]
```
root@demo:/opt/CTFd# uwsgi -s /tmp/uwsgi.sock -w "CTFd:create_app()" --uid=www-data --chown-socket=www-data:www-data --auto-procname
*** Starting uWSGI 2.0.15 (64bit) on [Wed Apr  5 01:43:19 2017] ***
compiled with version: 4.8.4 on 05 April 2017 01:40:22
os: Linux-3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016
nodename: demo
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/CTFd
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3750
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
setuid() to 33
Python version: 2.7.6 (default, Oct 26 2016, 20:33:43)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x253c930
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x253c930 pid: 23330 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23330, cores: 1)
```

I'm not able to reproduce but this is on DigitalOcean and I changed some switches. Perhaps switching uids influences the python modules loaded?

**Comment by int0x80** [comment]
Thank you for the reply.  

Everything appears to run fine with both `python server.py` and `gunicorn`.  I am interested in running this through nginx as I have setup LetsEncrypt to protect the transmission of flags over the wire.  But I am open to alternatives so long as the transmissions are still encrypted.

In this run, I removed all modules installed from `requirements.txt` and have now installed them via `sudo -H pip install -r requirements.txt`.  I then received the following error:

```
~/CTFd$ sudo -s
~/CTFd# /home/ubuntu/.local/bin/uwsgi -s /tmp/uwsgi.sock -w "CTFd:create_app()" --uid=www-data --chown-socket=www-data:www-data --auto-procname
...
Traceback (most recent call last):
  File "./CTFd/__init__.py", line 89, in create_app
    init_logs(app)
  File "./CTFd/utils.py", line 62, in init_logs
    key_log = logging.handlers.RotatingFileHandler(os.path.join(parent, 'logs', 'keys.log'), maxBytes=10000)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/ubuntu/CTFd/CTFd/logs/keys.log'
```

This occurred for each log so I basically had to do `chmod a+w /home/ubuntu/CTFd/CTFd/logs/*.log`.  I know I'm committing war crimes by making all these adjustments willy-nilly but the CTF is short and the instance will be terminated immediately after.

I'm facing a new issue at this point.

```
  File "/usr/local/lib/python2.7/dist-packages/flask_caching/__init__.py", line 646, in decorated_function
    rv = f(*args, **kwargs)
  File "./CTFd/utils.py", line 144, in ctf_name
    name = get_config('ctf_name')
  File "/usr/local/lib/python2.7/dist-packages/flask_caching/__init__.py", line 646, in decorated_function
    rv = f(*args, **kwargs)
  File "./CTFd/utils.py", line 354, in get_config
    config = Config.query.filter_by(key=key).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2731, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2523, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2852, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in _get_bind_args
    **kw
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2843, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 966, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'INSERT INTO config ("key", value) VALUES (?, ?)'] [parameters: ('ctf_name', None)]
```

In the past, I recall setting `CTF_NAME` in `CTFd/config.py`, though there is not currently an entry there by default.  I added an entry manually but am still receiving the error:

```
~/CTFd$ grep -rnsI CTF_NAME .
./CTFd/config.py:19:    CTF_NAME = 'COOL CTF'
```

Happy to move this to a separate issue and close here if you'd prefer.

**Comment by ColdHeat** [comment]
Nope this issue is fine :) 

I typically use nginx as a reverse proxy for gunicorn. Gunicorn is much easier to work with in my experience. 

`ctf_name` is stored in the database now so it's modifiable from within the application. I think sqlalchemy thinks that the sqlite database is locked for some reason. Do you happen to have another application using the database? 

Worst case you could switch to MySQL but I personally develop on sqlite so it should work. If the database doesnt have data in it yet, perhaps you could delete it and let CTFd recreate it?

**Comment by int0x80** [comment]
Thanks for the suggestion.  I did try removing the original `ctfd.db` and let CTFd create it by running `python server.py`.

No other applications are using the database as best I can tell (`lsof | grep -c 'ctfd.db'` returns 0).  Is there a graceful way to stop the `uwsgi` process?  If I `kill` it, I sometimes continue getting the `sqlalchemy.exc.InvalidRequestError`, but other times that exception does not occur and I get a different error:

```
--- no python application found, check your startup logs for errors ---
[pid: 6857|app: -1|req: -1/7] 70.x.x.x () {44 vars in 696 bytes} [Wed Apr  5 19:40:40 2017] GET / => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6857|app: -1|req: -1/8] 70.x.x.x () {42 vars in 646 bytes} [Wed Apr  5 19:40:40 2017] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6857|app: -1|req: -1/9] 70.x.x.x () {42 vars in 675 bytes} [Wed Apr  5 19:40:46 2017] GET /setup => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
```

With the former, the page returns a 502 Bad Gateway.  With the latter, the page returns a 500 Internal Server Error.  No hits in the nginx `error.log`.

Do you have any configs you would be willing to share for a gunicorn + nginx setup?  I am pretty unfamiliar with nginx and have no experience at all with gunicorn.  I just need the scoreboard to scale to ~125 players; it's running on a decent EC2 instance (8 vcpu, 32gb ram).

**Comment by ColdHeat** [comment]
Honestly I used uwsgi many months ago and it was painful and hasn't been used with CTFd dev since. The speed savings weren't really worth it (gunicorn is slightly more CPU intensive). 

https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-apps-using-gunicorn-http-server-behind-nginx#configuring-nginx

Effectively you just want to run gunicorn on something like 127.0.0.1:8000 and then have nginx proxy through that. 

This section in the DigitalOcean article discusses an nginx config that is applicable. You'd just want to replace app_servers with `127.0.0.1:8000` or wherever CTFd is running internally. 

```
        location / {
            proxy_pass         http://app_servers;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
```

This should be sufficient to get gunicorn + CTFd running:
```
gunicorn --bind 127.0.0.1:8000 -w 8 "CTFd:create_app()"
```
You could also look at the gunicorn docs to daemonize gunicorn but I've never used this:

http://docs.gunicorn.org/en/stable/settings.html#daemon

If you're interested we can set something up on https://ctfd.io which has the capabilities to deploy CTFd automatically.

**Comment by int0x80** [comment]
Wow gunicorn + nginx was way smoother.  Hopefully last question, the page loads over HTTPS just fine but the rendering is all messed up as though the CSS files are not processed.  If I view source, all of the CSS and JS files load correctly; and using the Network view in Chrome's Developer Tools, I see them all get requested and returned with 200.  The requests all show up in `access.log` and I have no hits in `error.log`.

Here is a screenshot:

![screen shot 2017-04-05 at 2 14 53 pm](https://cloud.githubusercontent.com/assets/1061032/24727401/b548c822-1a0a-11e7-9f5a-3c1fe51f74bf.png)

Any ideas?  Thank you again for all of the help.

**Comment by ColdHeat** [comment]
Force reload with `Cmd/Ctrl + Shift + R`? I suspect your browser is using cached data but can't be sure. Everything is served from within CTFd so everything should be loading over HTTPS...

**Comment by int0x80** [comment]
Crazy.  I tried that, even using a different browser, and had no luck.  Reverted the snapshot in my browser VM and now it looks great.  Thank you again for everything!

**Comment by ColdHeat** [comment]
Glad to hear!
