### ISSUE TITLE
Docker build on Digital Ocean droplet errors when attempting to connect to DB

### ISSUE THREAD

**Issue by cynicXer** [CTFd/CTFd#238]
I followed the instructions and attempted to use the Docker image on a Digital Ocean droplet.  I get a lot of the following error message: 

`db_1    | 2017-04-07T16:53:55.318968Z 23 [Note] Aborted connection 23 to db: 'unconnected' user: 'root' host: '172.18.0.2' (Got an error reading communication packets)`

I didn't change anything in the default configuration.  Is there a configuration setting I missed?  Or is the build using the wrong connection string to talk to the DB?

Thank you!

**Comment by ColdHeat** [comment]
If you just used `docker-compose up` you should be fine. I believe those errors appear when CTFd is waiting for the db to spin up. Can you try connecting to CTFd anyway despite the errors?

**Comment by cynicXer** [comment]
It doesn't appear to be listening.

**Comment by cynicXer** [comment]
I changed the IP address in serve.py to use the public IP of the droplet.  This works when I run it outside of Docker, but inside Docker I get the following error:

db_1    | Version: '5.7.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
ctfd_1  | .mysqld is alive
ctfd_1  | Ready
ctfd_1  | Starting CTFd
ctfd_1  | /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:305: SAWarning: Exception attempting to detect unicode returns: OperationalError("(pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')",)
ctfd_1  |   "detect unicode returns: %r" % de)
ctfd_1  | /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:305: SAWarning: Exception attempting to detect unicode returns: OperationalError('(pymysql.err.OperationalError) (2003, "Can\'t connect to MySQL server on \'db\' ([Errno 111] Connection refused)")',)
ctfd_1  |   "detect unicode returns: %r" % de)
ctfd_db_1 exited with code 137
ctfd_1  | Traceback (most recent call last):
ctfd_1  |   File "/usr/local/bin/gunicorn", line 11, in <module>
ctfd_1  |     sys.exit(run())
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
ctfd_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 203, in run
ctfd_1  |     super(Application, self).run()
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
ctfd_1  |     Arbiter(self).run()
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 231, in run
ctfd_1  |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 344, in halt
ctfd_1  |     self.stop()
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
ctfd_1  |     time.sleep(0.1)
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 244, in handle_chld
ctfd_1  |     self.reap_workers()
ctfd_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 524, in reap_workers
ctfd_1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
ctfd_1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by ColdHeat** [comment]
I'm able to reproduce this locally. For some reason CTFd can't find `db` because it's not being resolved to the other container...

**Comment by ColdHeat** [comment]
@cynicXer can you delete your .data folder in the CTFd repository? I think that might be causing your issues.

**Comment by ColdHeat** [comment]
@cynicXer I believe f07a39c343eb9aa680c8a95a5dce5c8c7b72d7da should fix this. Please update to that and try again. 

Also you may need to delete your `.data` folder.

If it doesn't fix it feel free to reopen this issue.

**Comment by cynicXer** [comment]
I blew away the docker images and cloned the repo again; checked out the PR you added with "git fetch origin pull/204/head:pr-204; git checkout pr-204" re-ran "docker-compose up".  Still spits out a handful of DB connection errors but seems to be working now.  Thank you!
