### ISSUE TITLE
Anonymous challenge submission

### ISSUE THREAD

**Issue by pl4nty** [CTFd/CTFd#2397]
We would like students to access CTFd challenges anonymously for practice and ad-hoc cybersecurity exercises. This is partially achievable by setting challenges to public, but the students can't check their flags.

Would an additional configuration be suitable to allow this behaviour and show correct/incorrect messages? It would also be nice to hide "solved" challenges on the frontend, but I can understand if that'd require too much change to the underlying datastores.

Looks like a few lines here might do the trick, noting that this mode could allow bruteforcing:

https://github.com/CTFd/CTFd/blob/d8f0b9e602fca109cabe1895e847d39a46ce7429/CTFd/api/v1/challenges.py#L496-L497

**Comment by ColdHeat** [comment]
We actually achieve this when we need to with a custom plugin. 

I recognize that there's value in this but I do have concerns around bruteforcing as well as with abuse. 

We can likely open source the plugin that we use to do anonymous flag checking. I am less confident about adding the feature directly into CTFd.

**Comment by pl4nty** [comment]
A plugin would be great for my usecase, thanks! A warning about abuse in the plugin README might help, and hopefully the overhead of plugin installation would ensure users understand the risk.

**Comment by pl4nty** [comment]
@ColdHeat is there anything I can do to help with open sourcing the plugin? I've got a few upcoming events that could benefit from it with hosted CTFd

**Comment by ColdHeat** [comment]
I have placed the plugin as an archive at https://github.com/CTFd/public_challenges.
