### ISSUE TITLE
Two identical "id" columns in exported "solves" CSV file

### ISSUE THREAD

**Issue by z-oo-m** [CTFd/CTFd#2403]
**Environment**:
- CTFd Version: 3.6.0
- This issue **was not** present in CTFd 3.5.3

**What happened?**
When exporting the "solves" CSV, the resulting CSV file contains two "id" columns that are identical.
This is the first line (header) in the CSV file: `challenge_id,user_id,team_id,id,ip,provided,type,date,id`

**What did you expect to happen?**
The column "id" should be exported to the CSV file only once. Having two columns with the same name creates various issues when processing these CSV files with third-party tools.

**How to reproduce your issue**
1. Log in to the CTFd Server as an administrator and go to **Config** > **Backup** > **Download CSV**.
2. Select "solves" from the Database Table drop-down menu and click the **Download CSV** button.
3. Inspect the downloaded CSV file.

**Comment by ColdHeat** [comment]
I can reproduce this. I do not know the cause. It's likely to do with the SQLAlchemy version bump. I will investigate when I can but a PR would also be helpful.
