### ISSUE TITLE
No module named 'flask_babel'

### ISSUE THREAD

**Issue by ArtKelly** [CTFd/CTFd#2407]
**Environment**:

- CTFd Version/Commit: 3.6.0
- Operating System: Ubuntu
- Web Browser and Version: n/a
 
**What happened?**
Followed the update guide here: https://docs.ctfd.io/docs/deployment/updating
Upon restarting docker-compose up, the web server is not restarting

**What did you expect to happen?**
The web server to start

**How to reproduce your issue**

**Any associated stack traces or error logs**
Docker-compose logs -> 
ctfd_1     | Traceback (most recent call last):
ctfd_1     |   File "/opt/CTFd/ping.py", line 10, in <module>
ctfd_1     |     from CTFd.config import Config
ctfd_1     |   File "/opt/CTFd/CTFd/__init__.py", line 9, in <module>
ctfd_1     |     from flask_babel import Babel
ctfd_1     | ModuleNotFoundError: No module named 'flask_babel'
ctfd_ctfd_1 exited with code 1

**Comment by catenacyber** [comment]
Getting same issue today

**Comment by catenacyber** [comment]
`docker compose down` `docker compose build` and `docker compose up` seem to have solved it
