### ISSUE TITLE
Dynamic challenges do not show a Next Challenge

### ISSUE THREAD

**Issue by Nils1729** [CTFd/CTFd#2418]
**Environment**:

- CTFd Version/Commit: 3.6.0/8ead306f8b57c059192cd8b137f37ee41a078a41
- Operating System: All
- Web Browser and Version: All

**What happened?**

TLDR: *dynamic* challenges do not serve `next_id` to the frontend.

**How to reproduce your issue**

1. I created two challenges A and B with dynamic scoring.
2. I opened the admin configuration for challenge A.
3. I clicked "Next"
4. I selected challenge B from the dropdown.
5. I clicked the "Save" button.
6. The input field is empty.

**What did you expect to happen?**

The input field shows "Challenge B".

**Any associated stack traces or error logs**

The issue arises from the lack of `next_id` field in API responses for dynamic challenges [here](https://github.com/CTFd/CTFd/blob/8ead306f8b57c059192cd8b137f37ee41a078a41/CTFd/plugins/dynamic_challenges/__init__.py#L60-L89).

**Comment by ColdHeat** [comment]
Great catch thank you!
