### ISSUE TITLE
Specific API Reacting to Authentication Header

### ISSUE THREAD

**Issue by raihalea** [CTFd/CTFd#2428]
**Environment**:

- CTFd Version/Commit: 3.6
- Operating System:Ubuntu 22.04
- Web Browser and Version: Google Chrome 119.0.6045.160 / curl 7.81.0 

**What happened?**
I deployed CTFd on AWS and used CloudFront. I encountered an issue where requests to the CTFd API endpoint (https://<CTFd Domain>/api/v1/notifications?since_id=0) returned an HTTP/1.1 401 UNAUTHORIZED response when processed through CloudFront Functions with Basic Authentication. 
The issue was resolved by removing the Authorization header before it reached CTFd.

**What did you expect to happen?**
I expected the CTFd API to process requests normally, without reacting to the Authorization header, especially since I have not configured any specific authentication settings within CTFd itself. 

**How to reproduce your issue**
Make a request to https://<CTFd Domain>/api/v1/notifications?since_id=0 with an Authorization header.
Observe the 401 UNAUTHORIZED response.

**Any associated stack traces or error logs**

```
curl -I 'http://localhost/api/v1/notifications?since_id=0' \
  -H 'Content-Type: application/json' \
  -H "Authorization:Basic dXNlcjpwYXNz"
  --compressed
HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.24.0
Date: Mon, 27 Nov 2023 14:09:34 GMT
Content-Type: application/json
Content-Length: 236
Connection: keep-alive
```

With Authorization header:
```
$ curl 'http://localhost/api/v1/notifications?since_id=0' \
  -H 'Content-Type: application/json' \
  -H "Authorization:Basic dXNlcjpwYXNz"
{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}
```

Without Authorization header:
```
curl 'http://localhost/api/v1/notifications?since_id=0' \
  -H 'Content-Type: application/json'
{"success": true, "data": []}
```

I'm unsure if this issue is part of normal operation. If it's not a problem, please close this issue.

**Comment by ColdHeat** [comment]
We use the Authorization header for API tokens: https://github.com/CTFd/CTFd/blob/master/CTFd/utils/initialization/__init__.py#L284. 

Can you configure Cloudfront to use another header?

**Comment by raihalea** [comment]
Thank you for your response.

I am using CloudFront Functions for Basic Authentication, so there was no need to pass the Authorization header from CloudFront to CTFd. 
Currently, I am removing the Authorization header through the CloudFront behavior settings, and it seems to be functioning well. However, if the use of the Authorization header is intended in CTFd, then perhaps my approach might be incorrect.

Since I want to implement Basic Authentication, using another header is challenging for me.
