### ISSUE TITLE
Docker MySQL and CTFD images not communicating on Digital Ocean droplet

### ISSUE THREAD

**Issue by cynicXer** [CTFd/CTFd#243]
I blew away the docker images and cloned the repo again; checked out the PR you added with "git fetch origin pull/204/head:pr-204; git checkout pr-204" re-ran "docker-compose up".

gunicorn launched this time, but the DB connection still isn't resolving. I can browse to the page but none of the functionality that depends on the DB works. I'm going to give up on Docker and run it on a VM.

db_1 | MySQL init process done. Ready for start up.
db_1 |
db_1 | 2017-04-10T21:38:14.479368Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1 | 2017-04-10T21:38:14.482413Z 0 [Note] mysqld (mysqld 5.7.17) starting as process 1 ...
db_1 | 2017-04-10T21:38:14.488562Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1 | 2017-04-10T21:38:14.488674Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1 | 2017-04-10T21:38:14.488733Z 0 [Note] InnoDB: Uses event mutexes
db_1 | 2017-04-10T21:38:14.488765Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1 | 2017-04-10T21:38:14.488801Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1 | 2017-04-10T21:38:14.488849Z 0 [Note] InnoDB: Using Linux native AIO
db_1 | 2017-04-10T21:38:14.490159Z 0 [Note] InnoDB: Number of pools: 1
db_1 | 2017-04-10T21:38:14.490687Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1 | 2017-04-10T21:38:14.494252Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1 | 2017-04-10T21:38:14.513406Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1 | 2017-04-10T21:38:14.517721Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1 | 2017-04-10T21:38:14.533825Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1 | 2017-04-10T21:38:14.560193Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1 | 2017-04-10T21:38:14.562618Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1 | 2017-04-10T21:38:14.615933Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1 | 2017-04-10T21:38:14.617926Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1 | 2017-04-10T21:38:14.618000Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1 | 2017-04-10T21:38:14.623778Z 0 [Note] InnoDB: Waiting for purge to start
db_1 | 2017-04-10T21:38:14.674058Z 0 [Note] InnoDB: 5.7.17 started; log sequence number 12131456
db_1 | 2017-04-10T21:38:14.678139Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1 | 2017-04-10T21:38:14.684825Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1 | 2017-04-10T21:38:14.716555Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1 | 2017-04-10T21:38:14.717579Z 0 [Warning] CA certificate ca.pem is self signed.
db_1 | 2017-04-10T21:38:14.720328Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1 | 2017-04-10T21:38:14.721196Z 0 [Note] IPv6 is available.
db_1 | 2017-04-10T21:38:14.721273Z 0 [Note] - '::' resolves to '::';
db_1 | 2017-04-10T21:38:14.721062Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170410 21:38:14
db_1 | 2017-04-10T21:38:14.721424Z 0 [Note] Server socket created on IP: '::'.
db_1 | 2017-04-10T21:38:14.727225Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1 | 2017-04-10T21:38:14.727348Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1 | 2017-04-10T21:38:14.728075Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1 | 2017-04-10T21:38:14.728161Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1 | 2017-04-10T21:38:14.732836Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1 | 2017-04-10T21:38:14.745552Z 0 [Note] Event Scheduler: Loaded 0 events
db_1 | 2017-04-10T21:38:14.746114Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check.
db_1 | 2017-04-10T21:38:14.746179Z 0 [Note] Beginning of list of non-natively partitioned tables
db_1 | 2017-04-10T21:38:14.769718Z 0 [Note] End of list of non-natively partitioned tables
db_1 | 2017-04-10T21:38:14.770342Z 0 [Note] mysqld: ready for connections.
db_1 | Version: '5.7.17' socket: '/var/run/mysqld/mysqld.sock' port: 3306 MySQL Community Server (GPL)
ctfd_1 | ..........mysqld is alive
ctfd_1 | Ready
db_1 | 2017-04-10T21:38:17.338446Z 5 [Note] Aborted connection 5 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
db_1 | 2017-04-10T21:38:17.512450Z 4 [Note] Aborted connection 4 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
ctfd_1 | CONFIGURING SERVER
ctfd_1 | LOADING CHALLENGES
ctfd_1 | LOADING USERS
db_1 | 2017-04-10T21:38:18.231524Z 6 [Note] Aborted connection 6 to db: 'ctfd' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
ctfd_1 | [2017-04-10 21:38:18 +0000] [40] [INFO] Starting gunicorn 19.7.1
ctfd_1 | [2017-04-10 21:38:18 +0000] [40] [INFO] Listening at: http://0.0.0.0:8000 (40)
ctfd_1 | [2017-04-10 21:38:18 +0000] [40] [INFO] Using worker: sync
ctfd_1 | [2017-04-10 21:38:18 +0000] [50] [INFO] Booting worker with pid: 50
ctfd_1 | [2017-04-10 21:38:18 +0000] [51] [INFO] Booting worker with pid: 51
ctfd_1 | [2017-04-10 21:38:18 +0000] [61] [INFO] Booting worker with pid: 61
ctfd_1 | [2017-04-10 21:38:18 +0000] [65] [INFO] Booting worker with pid: 65
db_1 | 2017-04-10T21:41:45.336820Z 13 [Note] Aborted connection 13 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
db_1 | 2017-04-10T21:42:48.645213Z 7 [Note] Aborted connection 7 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
db_1 | 2017-04-10T21:42:48.798646Z 11 [Note] Aborted connection 11 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)
db_1 | 2017-04-10T21:43:15.469273Z 9 [Note] Aborted connection 9 to db: 'unconnected' user: 'root' host: '172.18.0.3' (Got an error reading communication packets)

**Comment by ColdHeat** [comment]
Even the index page requires a database.... Not sure how this is happening.

**Comment by ColdHeat** [comment]
Also I said to check out a commit to master. Which means you should `git pull` instead of switching to that PR.

**Comment by ColdHeat** [comment]
I believe this should be fixed... If it isn't feel free to reopen the issue.
