### ISSUE TITLE
Upload to S3 Failing

### ISSUE THREAD

**Issue by Thomas-McKanna** [CTFd/CTFd#2456]
- CTFd Version/Commit: 3.6.1
- Operating System: Linux (Docker container)
- Web Browser and Version: Chrome

**What happened?**

Upgrading CTFd resulting in S3 file uploads beginning to return 400 (bad request) status codes. I see one of the fixes for 3.6.1 was for S3, so perhaps a new bug was introduced.

Here are some additional facts which may be helpful:

  - The files are successfully making there way into S3, despite the error
  - The timezone I have configured for my server is CST

I can also confirm that my deployment had working file upload before upgrade to version 3.6.1 (file upload was working for 3.6.0).

**What did you expect to happen?**

File upload to continue working.

**How to reproduce your issue**

Deploy CTFd free version using version 3.6.1 with S3 file upload configured.

**Any associated stack traces or error logs**

The browser request returns error (400 status code):

```
{
    "success": false,
    "errors": {
        "location": [
            "I/O operation on closed file."
        ]
    }
}
```

The backend error is:

```
[ERROR] Error handling request
Traceback (most recent call last):
File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 113, in handle_request
resp.write_file(respiter)
File "/opt/venv/lib/python3.9/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
if not self.sendfile(respiter):
File "/opt/venv/lib/python3.9/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
self.sock.sendfile(respiter.filelike, count=nbytes)
File "/opt/venv/lib/python3.9/site-packages/gevent/_socket3.py", line 486, in sendfile
return self._sendfile_use_send(file, offset, count)
File "/opt/venv/lib/python3.9/site-packages/gevent/_socket3.py", line 416, in _sendfile_use_send
self._check_sendfile_params(file, offset, count)
File "/opt/venv/lib/python3.9/site-packages/gevent/_socket3.py", line 461, in _check_sendfile_params
raise ValueError(
ValueError: count must be a positive integer (got 0)
```

**Comment by ColdHeat** [comment]
This could be related to https://github.com/CTFd/CTFd/pull/2432 but I am unsure since I have not seen S3 uploads breaking. Can you perhaps set your timezone to UTC to see if that allows uploads to work? That will help confirm the source of the issue.

**Comment by Thomas-McKanna** [comment]
@ColdHeat I did some digging. It looks like the boto3 `upload_fileobj` function silently closes the file object you give it after upload (see https://github.com/boto/boto3/issues/929).

This unfortuate undocumented behavior, along with the addition of https://github.com/CTFd/CTFd/blob/3536c4c423aab5b0b9c164af73f59fe29a4d7dcf/CTFd/utils/uploads/__init__.py#L50 in the last release it causing the issue, since this line occurs after the called to `upload_fileobj`. This explains why the returned error is `"I/O operation on closed file."`.

I guess this would only be a problem if using S3 to store files for CTFd.

**Comment by ColdHeat** [comment]
Thank you for digging into this and figuring out the issue. This is an issue in a feature for 3.7 which explains why I haven't seen it before. 

You're welcome to PR a fix but I will tackle this as part of 3.7 as well.

**Comment by ColdHeat** [comment]
Likely the simplest fix is to calculate the SHA before uploading because we don't close the file and re-seek to the beginning as well.

**Comment by Thomas-McKanna** [comment]
@ColdHeat I can confirm that moving the hash calculated to before the file upload fixes the issue. I can submit a PR. Any idea when this might be pushed to a new hotfix version (maybe 3.6.2?)? This issue is currently causing me some trouble in preparing for an upcoming event.

**Comment by ColdHeat** [comment]
Thanks for the PR I stepped out before I could put one up. 

I think I would rather wait for 3.7.0. There isn't a significant amount of difference between 3.6.1 and the current commit: https://github.com/CTFd/CTFd/compare/3.6.1...master so if you having issues you could just specifically pin to the 3.6.1 image or to that tag/commit.

**Comment by Thomas-McKanna** [comment]
Ok, I'll make it work somehow. I was having some issues with pinning to a tag/commit because it seemed to throw off the database.

**Comment by ColdHeat** [comment]
I think now that your fix is merged you should be able to run off of that since the shasum change is the only change that modified the database.

**Comment by Thomas-McKanna** [comment]
@ColdHeat Yep that worked. Thank you!
