### ISSUE TITLE
SQLite Issues with Backup Import

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#246]
```StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'INSERT INTO teams (name, email, password, website, affiliation, country, bracket, banned, verified, admin, joined) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)']```

This is some sort of issue with dataset + sqlite. I think there is a way to fix this but Im not immediately sure what it is...

**Comment by ColdHeat** [comment]
This should be fixed with some mildly aggressive DateTime conversions happening during imports if your db backend is sqlite.

**Comment by kylecook80** [comment]
Upon further inspection, the version of CTFd that the data was exported from was version 1.0.2. Do you think the database will upgrade cleanly to the latest version?

**Comment by ColdHeat** [comment]
In theory it should but you should stick to commenting in your own issue not this older one.
