### ISSUE TITLE
Cannot bundle the admin assets

### ISSUE THREAD

**Issue by whirlwind110** [CTFd/CTFd#2463]
I modified `CTFd/themes/admin/assets/js/pages/statistics.js`, then I bundle it through `yarn dev`, but the command throw an Error("callback(): The callback was already called.");

<img width="824" alt="Capture" src="https://github.com/CTFd/CTFd/assets/12848936/c4e12dfb-db83-40d0-a3c9-14d9d5223d98">

The webpack.config.js was created 4 years ago, is it expired?

**Comment by ColdHeat** [comment]
Hello can you please try 3.7.0? https://github.com/CTFd/CTFd/tree/3.7.0-dev. Webpack has been removed there and replaced with Vite.

**Comment by whirlwind110** [comment]
> Hello can you please try 3.7.0? https://github.com/CTFd/CTFd/tree/3.7.0-dev. Webpack has been removed there and replaced with Vite.

@ColdHeat , thank you for your reply.

But it still failed after I changed the branch to 3.7.0-dev.

```
cd \CTFd\themes\admin
npm install
npx vite build
```
![error1](https://github.com/CTFd/CTFd/assets/12848936/5354ae80-0a73-45eb-8e99-f1c3c9c41f77)

Are some packages missed in package.json?

I added some packages like :

    "echarts": "^4.9.0",
    "event-source-polyfill": "^1.0.31",
    "highlight.js": "^11.9.0",
    "markdown-it": "^14.0.0",
    "nunjucks": "^3.2.4",

Then the jquery error occurred,  `Rollup failed to resolve import "jquery" from "../core/assets/js/utils.js".`

![error2](https://github.com/CTFd/CTFd/assets/12848936/027298c8-7624-4ea8-a723-e3036b33400d)

**Comment by whirlwind110** [comment]
Finally, I have added packages and delete the first line in /core/assets/js/utils.js.

CTFd/themes/admin/package.json

    "echarts": "^4.9.0",
    "event-source-polyfill": "^1.0.31",
    "highlight.js": "^11.9.0",
    "jquery": "^3.7.1",
    "markdown-it": "^14.0.0",
    "nunjucks": "^3.2.4",
    "q": "^1.5.1",
    "sass": "^1.70.0",

CTFd/themes/core/assets/js/utils.js
delete the first line `import $ from "jquery";`

**Comment by ColdHeat** [comment]
Try using vite, the admin theme builds for me.

**Comment by whirlwind110** [comment]
> Try using yarn, the admin theme builds for me.

I found the reason.

A part of dependencies are defined in the root `package.json`. So we should execute `yarn install` in the root path firstly, then change the directory to  `\CTFd\CTFd\themes\admin` and execute `yarn install && yarn build`.

Shall we merge the root package.json into admin theme folder?

**Comment by ColdHeat** [comment]
Yes thank you for digging, I just noticed this too. The ideal situation is admin being it's own seperate theme so we need to merge package.json into the admin theme, however we don't want to take everything, just the relevant packages. If you like you can PR that in but I will also take a look when I have the time.

**Comment by ColdHeat** [comment]
Interestingly for some reason in a fresh codespace this does build but I assume it is simply skipping those missing dependencies.

**Comment by ColdHeat** [comment]
Ah I see it actually was my mistake!
