### ISSUE TITLE
Team members

### ISSUE THREAD

**Issue by SynAckPwn23** [CTFd/CTFd#247]
It is possible to show all username that are part of specific team?
It is possible to show who (specific username) resolved a particular challange?

**Comment by ColdHeat** [comment]
In CTFd we don't have a construct of tracking users within a team. Teams are sort of just a username and password but it doesn't require people to join, you just share the username and password to have teammates join. 

CTFd tracks the IP addresses used by a team and which IP address submitted a correct flag.
