### ISSUE TITLE
Users cant solve challenge after changing to user mode

### ISSUE THREAD

**Issue by HaraldMR** [CTFd/CTFd#2522]
**Environment**:

- CTFd Version/Commit: 3.7.0
- Operating System: Ubuntu 22.04.3 LTS
- Web Browser and Version: Bug is occurs in Newest Chrome, Chromium and Firefox. Not tested more.

**What happened?**
Some of our users was not able to submit correct flag to solve the challenge. This occurred for after we swapped to user mode for one of our events, our ctfd instance is usually in Team mode. We narrowed it down to being because the teams still exist, making some users unable to get a solve because they are in a "hidden" team where one of their team members already had solved the challenge. 

**What did you expect to happen?**
Expected to be able to swap to user mode, and be able to have all users solve all challenges, so we dont have to create new teams and users every time we would like to swap mode.

**How to reproduce your issue**
Create a few users in the same team. 
Swap to user mode.
Have one of the users solve a challenge.
Try to solve the same challenge with one of the other users.

**Any associated stack traces or error logs**
n/a

**Comment by ColdHeat** [comment]
Hmm I thought that when switching user mode via the Admin Panel it would remove users from their teams but it appears maybe not. 

How did you switch user mode? Via the Admin Panel?

**Comment by ColdHeat** [comment]
I see that in the original commit this just deleted submissions https://github.com/CTFd/CTFd/pull/1956/files. This would work in moving from users to teams but it doesn't work the other way around. When we switch teams to users we need to remove all users from teams.

**Comment by HaraldMR** [comment]
> How did you switch user mode? Via the Admin Panel?

Switched user mode via the admin panel, yes.

> When we switch teams to users we need to remove all users from teams.

So it is an issue with the way the teams and users are set up in relation to eachother, if im understanding this correctly?
