### ISSUE TITLE
Have anyone get this error when run docker desktop ? Pls tell me

### ISSUE THREAD

**Issue by Luuducloc0926** [CTFd/CTFd#2524]
![Screenshot 2024-04-22 234918](https://github.com/CTFd/CTFd/assets/86753838/97aee4e9-3e3a-4f96-bc39-95170dc1afd7)

**Comment by ColdHeat** [comment]
Try running the ctfd/ctfd image from Dockerhub instead of building locally but not sure what's wrong here since the Docker image should be working fine.
