### ISSUE TITLE
Hints can move the scoreboard after the CTF is over

### ISSUE THREAD

**Issue by nategraf** [CTFd/CTFd#255]
If someone pays to unlock a hint after the CTF is over their dot will move on the scoreboard to reflect it.

1 possible solution. Make hints automatically free after CTF time is done

**Comment by ColdHeat** [comment]
Ah good catch I didn't think of that. Hints for free after the CTF is over makes sense.

**Comment by Colbert337** [comment]
i found that the hints can not be deleted,please help.

Thanks

**Comment by ColdHeat** [comment]
Sounds like things need a good overhaul. In the meantime you can edit it into a useless hint with no value. 

Hopefully I'll work on it over the weekend.

**Comment by ColdHeat** [comment]
@Colbert337 I'm not able to reproduce, do you have some kind of example or stack trace I could see?

**Comment by Colbert337** [comment]
in /admin/chals,I new 2 hints,but after the hints create,it can not be deteted.

where can I see the stack strace?

**Comment by ColdHeat** [comment]
You should be able to see it in the console after you run `python serve.py` and do the same action.

**Comment by ColdHeat** [comment]
Are you using MySQL?

**Comment by Colbert337** [comment]
python serve.py

127.0.0.1 - - [12/Jun/2017 10:30:32] "GET /admin/chals HTTP/1.0" 200 -
127.0.0.1 - - [12/Jun/2017 10:30:32] "POST /admin/chals HTTP/1.0" 200 -
127.0.0.1 - - [12/Jun/2017 10:30:37] "GET /admin/chal/16/hints HTTP/1.0" 200 -
127.0.0.1 - - [12/Jun/2017 10:30:37] "GET /admin/chal/16/keys HTTP/1.0" 200 -
127.0.0.1 - - [12/Jun/2017 10:30:37] "GET /admin/files/16 HTTP/1.0" 200 -
127.0.0.1 - - [12/Jun/2017 10:30:37] "GET /admin/tags/16 HTTP/1.0" 200 -
127.0.0.1 - - [12/Jun/2017 10:30:44] "GET /admin/hints/1 HTTP/1.0" 200 -

The delete button （X）has no response and no network interaction.

I use MySql，can I del  the hints directly  in the  Mysql databases "CTFd"?

**Comment by Colbert337** [comment]
I check the front-end code ：

<i role="button" class="fa fa-times" onclick="javascript:deletehint(1)"></i>

but I can not find the  "deletehint()"

**Comment by ColdHeat** [comment]
@Colbert337 Please `git pull` and if there's still an issue make a separate ticket. No need to hijack an existing ticket.

**Comment by Colbert337** [comment]
@ColdHeat OK，thank you!!!!
