### ISSUE TITLE
[Question] Timing's Impact on CTF Ranking

### ISSUE THREAD

**Issue by mosheDO** [CTFd/CTFd#2550]
It's often observed that when two teams amass equal points, the team which solves challenges later tends to be ranked higher on the scoreboard. 
Why does the timing of challenge solutions become a determining factor in team rankings? 
To shed light on this, consider a scenario where two teams complete all challenges but in different order, resulting in one team being ranked higher due to their later completions. Similarly, in another instance, two teams might be tied in points, yet the team that finishes solving challenges closer to the end of the competition secures a better position

Why not keeping the team that solved first higher in the scoreboard awarding "first blood"?

**Comment by ColdHeat** [comment]
The team that solved the challenge first should have the higher position. Is that not the behavior that you're seeing?
