### ISSUE TITLE
how to fix CommandError: Path doesn't exist: 'migrations'?

### ISSUE THREAD

**Issue by Colbert337** [CTFd/CTFd#257]
I use Apache/2.4.7 (Ubuntu14.04) mod_wsgi/4.1.3 Python/2.7.6 configured，but it failed and the http Status Code is 500 (Internal Server Error)

the Apache2  error_log is :  

[Fri May 05 11:35:21.288751 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337] mod_wsgi (pid=3973): Target WSGI script '/var/www/html/CTFd/wsgi.py' cannot be loaded as Python module.
[Fri May 05 11:35:21.288843 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337] mod_wsgi (pid=3973): Exception occurred processing WSGI script '/var/www/html/CTFd/wsgi.py'.
[Fri May 05 11:35:21.288936 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337] Traceback (most recent call last):
[Fri May 05 11:35:21.289031 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]   File "/var/www/html/CTFd/wsgi.py", line 5, in <module>
[Fri May 05 11:35:21.289167 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]     application = create_app()
[Fri May 05 11:35:21.289252 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]   File "/var/www/html/CTFd/CTFd/__init__.py", line 49, in create_app
[Fri May 05 11:35:21.289341 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]     migrate_upgrade()
[Fri May 05 11:35:21.289436 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]   File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 244, in upgrade
[Fri May 05 11:35:21.289529 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]     command.upgrade(config, revision, sql=sql, tag=tag)
[Fri May 05 11:35:21.289610 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]   File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 234, in upgrade
[Fri May 05 11:35:21.289686 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]     script = ScriptDirectory.from_config(config)
[Fri May 05 11:35:21.289775 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]   File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 132, in from_config
[Fri May 05 11:35:21.289905 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]   **File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 58, in __init__**
[Fri May 05 11:35:21.289972 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337]     **"scripts folder." % dir)**
[Fri May 05 11:35:21.290047 2017] [wsgi:error] [pid 3973:tid 140195138877184] [remote 14.17.22.33:38337] **CommandError: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.**

And the apache2.conf is:

```
#add mod_wsgi
LoadModule wsgi_module modules/mod_wsgi.so

WSGISocketPrefix /var/run/wsgi

<VirtualHost *:80>
    ServerName localhost
    WSGIDaemonProcess CTFd user=ubuntu group=ubuntu threads=5
    WSGIScriptAlias / /var/www/html/CTFd/wsgi.py

    <Directory /var/www/html/CTFd>
        WSGIProcessGroup CTFd
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        AllowOverride All
        #Require all granted
        Allow from all
    </Directory>
</VirtualHost>
```

And the /var/www/html/CTFd/wsgi.py is:

```
import sys
sys.path.insert(0, '/var/www/html/CTFd')

from CTFd import create_app
application = create_app()
```

how to fix this problem?Thank you very much!

**Comment by ColdHeat** [comment]
Sorry this kept slipping away. 

Migrations should come when you clone the repository. You should see it in /var/www/html/CTFd/migrations.

**Comment by Colbert337** [comment]
@ColdHeat thank you ! But it still doesn't work. Then i change to use gunicorn+nginx，it is OK  now.

**Comment by ColdHeat** [comment]
Glad to hear 👍

**Comment by CunninghamPatrick** [comment]
See PR above. I was able to fix this locally on my system, but at work I have limited access to GitHub so I wasn't able to quite get a proper fix to pass the automated tests.

The stamp() call in CTFd/__init__.py is unable to find the migrations directory in a bare bones apache/wsgi setup.
