### ISSUE TITLE
Chinese translation select problem

### ISSUE THREAD

**Issue by eran0926** [CTFd/CTFd#2571]
**Environment**:

- CTFd Version/Commit:[e9660d8](https://github.com/CTFd/CTFd/commit/e9660d877eea520d6c70157b37eab2cde2fbd1f1)
- Operating System: Ubuntu 24.04
- Web Browser and Version:Google Chrome 126.0.6478.127  (64 bit)

**What happened?**
The user page always use zh translation file although user set language to zh_TW(國語) or zh_CN(中文)

**What did you expect to happen?**
The system should use "zh_TW" llanguage file render page when user set language to zh_TW(國語)
The system should use "zh_CN" llanguage file render page when user set language to zh_CN(中文)

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Does #2447 resolve this perhaps? I have not been able to heavily test it.

**Comment by eran0926** [comment]
I thaink it doesn't work.

**Comment by eran0926** [comment]
> I thaink it doesn't work.

I  am sorry ,maybe I edit something when test.It does work.

**Comment by ColdHeat** [comment]
#2447 has been merged which should improve this.

**Comment by eran0926** [comment]
Yes it work

> #2447 has been merged which should improve this.

Yes it works
