### ISSUE TITLE
why the tables-keys can not be show/select?

### ISSUE THREAD

**Issue by Colbert337** [CTFd/CTFd#259]
hello，why the tables-keys can not be show/select?

please help，thx~

mysql> show tables;
+-----------------+
| Tables_in_CTFd  |
+-----------------+
| alembic_version |
| awards          |
| challenges      |
| config          |
| containers      |
| files           |
| hints           |
| keys            |
| pages           |
| solves          |
| tags            |
| teams           |
| tracking        |
| unlocks         |
| wrong_keys      |
+-----------------+
15 rows in set (0.00 sec)

mysql> select * from keys;
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'keys' at line 1`

mysql> show full columns from keys;
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'keys' at line 1`

**Comment by ColdHeat** [comment]
When you select keys you need to put it in backticks as so:

``SELECT * FROM `keys`;``

**Comment by Colbert337** [comment]
thanks！it works！
