### ISSUE TITLE
What is the best practice for theme development

### ISSUE THREAD

**Issue by Dilrevx** [CTFd/CTFd#2607]
Modern SPA frameworks have features similar to `live-server`,  keeping web pages on track on file change.

Does ctfd community have a setup that can do the same thing?

My current setup is  `yarn dev` to compile js + (clear db) +Ctrl^C restart flask

**Comment by ColdHeat** [comment]
yarn dev or yarn build with core-beta (https://github.com/CTFd/core-beta) would be the best recommendation now. 

See https://github.com/CTFd/CTFd/issues/2562

In my usage it seems like vite did not like to rebuild the manifest when it did its rebuilding but I'm not sure. If you come up with a flow that you like feel free to PR it to the core-beta repo.

**Comment by Dilrevx** [comment]
Yeah I'm using the same workaround, and vite generates manifest.json correctly.

The flow works correctly. I was a little bit overwhelmed when first taking over. Now kind of adapted

**Comment by tomerp20** [comment]
Hey everyone,
I’m encountering the same issue and would like to avoid the workflow of running vite build and restarting Flask for every single change.

To improve the development experience, I tried using the Vite dev server to load asset files directly. I introduced an APP_ENV=dev config variable and modified the Assets class like this:

```
if self.dev_mode:
    # In development mode, serve directly from Vite dev server
    entry = f"{self.vite_dev_server}/{asset_key}"
    return markup(f'<script type="module" src="{entry}"></script>')
```
While this works for serving the files, I’ve encountered issues related to pre-bundling with Rollup, which seems to be causing problems when the files are loaded unbundled during development.

Has anyone else tackled this issue successfully? Perhaps someone from the original CTFd development team could shed some light on this? I’d love to know if there’s a better solution before investing more time in this approach.

Thanks in advance for any guidance!
