### ISSUE TITLE
Missing attribution in Challenge API (GET)

### ISSUE THREAD

**Issue by pandatix** [CTFd/CTFd#2625]
**Environment**:

- CTFd Version/Commit: 3.7.4
- Operating System: NA
- Web Browser and Version: NA

**What happened?**

The API call (GET) to `/api/v1/challenges/<id>` does not return the `attribution` field, as stated in #2595.

**What did you expect to happen?**

Return the `attribution` field.

**How to reproduce your issue**

```
curl "http://my.ctf/api/v1/challenges/1"
```

**Any associated stack traces or error logs**

NA

**Comment by ColdHeat** [comment]
<img width="334" alt="image" src="https://github.com/user-attachments/assets/a386d7f1-355a-4d16-aa86-63406f4f6ec7">

Attribution is there, different challenge types might have overridden the response but that's something else than what you're saying.

**Comment by pandatix** [comment]
@ColdHeat ok I see that you reproduced it using a "standard" challenge type. This is my fault as I tested it on a "dynamic" one.
This is reproducable with the "dynamic" challenge type :)
