### ISSUE TITLE
Attribution field is not displayed in core theme

### ISSUE THREAD

**Issue by NicoFgrx** [CTFd/CTFd#2629]
**Environment**: 

- CTFd Version/Commit: 3.7.4
- Operating System: Linux
- Web Browser and Version: Firefox

**What happened?**
The attribution field is not displayed in theme `core` (but it is displayed in `core-beta` )

**What did you expect to happen?**
The attribution field is visible in both theme.

**How to reproduce your issue**
- Create a Standard challenge with an attribution
- In /admin/config > Theme : `core` 
- View the challenge

**Comment by ColdHeat** [comment]
The core theme will not receive any updates. All changes should be directed to core-beta (https://github.com/CTFd/core-beta).

**Comment by NicoFgrx** [comment]
All right .
But quick question, why keep this theme if it is no longer supported?

May the "beta" naming is not appropriate ?

**Comment by ColdHeat** [comment]
The core theme will be removed entirely in 4.0. If you want to get there
faster then it would be best to tackle 4.0 milestone issues.

core-beta is the default in most situations already anyway.

Also keep in mind that even things like Gmail were in beta for 5 years.
