### ISSUE TITLE
Remove "Hint" and scrollbar goes crazy

### ISSUE THREAD

**Issue by Anadema** [CTFd/CTFd#2655]
**Environment**:

- CTFd Version/Commit: 3.7.1 and before
- Operating System: Ubuntu 24 for the server. Windows 11, Ubuntu 24 and android for
- Web Browser and Version: Latest Firefox and Chrome, on both PC and smartphone, across all browsers and environments

**What happened?**

When clicking the "View Hint" button, the hint appears with its own scrollbar, allowing you to read the entire hint. However, when closing the hint by clicking the cross icon, the challenge reappears, but the scrollbar no longer functions for the challenge. Instead, it controls the Flag page in the background, making it impossible to scroll through the challenge content. Additionally, you can’t close the challenge because the cross icon is located at the top, out of reach without a scrollbar for the challenge itself. On a PC, this is a minor inconvenience since you can click in an empty area to the left or right of the challenge. However, on a smartphone, there is no empty area, so the only option is to return to the previous page. If that page is the login page, you’re prompted to re-authenticate (even though you’re logged in) and navigate back to the Flag page, requiring three clicks plus one more to open your challenge again. This happens each time you click on a hint and is purely a scrollbar issue.

**What did you expect to happen?**

A scrollbar that controls the challenge popup after closing the hint popup, allowing the hint to be reread, the challenge to be closed if needed, or the hint to be reopened without any scrollbar issues.

**How to reproduce your issue**

Install CTFd, create one challenge, create one hint and test it with PC and smartphone, I discover this issue since 5 months, now I updated with the last version 3.7.1, it's the same. Maybe another bug report is opened for this issue, but I didn't find something here.

**Any associated stack traces or error logs**

I don't have, there is no log or static visual bug, I could do a short video if you want, just send me a message.

Very surprise that is not yet fix and nobody open a bug for that, it's a major issue for user experience.

**Comment by ColdHeat** [comment]
Sure can you make a video, I have no idea what this is referring to

**Comment by Anadema** [comment]
https://filetransfer.fr/download.php?file=VKQTMI8M3Z


We don't see the mouse, but with the description provided above, you'll be able to reproduce the issue.

On PC, it's almost fine—it's there, but not a major problem. However, on smartphones, it's a blocking issue, and the only way to get out of it is to return to the site’s homepage. I play with teenagers using their smartphones, as it's easier to organize a CTF (Capture The Flag) and they find it more fun. It's more about OSINT (Open Source Intelligence) than pure hacking, of course.

In the video, I demonstrate that the bug also appears in the back office. When creating a hint or uploading an image, if you have too many images at that point, you can't click on the image name to copy the link to your picture. You're stuck. The only workaround is to upload the image, exit the hint panel, return, and then copy the link.

Thanks for your attention.

**Comment by ColdHeat** [comment]
I see this is on the core theme which is soon to be deprecated. Does this still happen on the core-beta theme?

**Comment by ColdHeat** [comment]
Core theme is deprecated and will be removed soon. I would recommend updating to core-beta and using themes based on core-beta. 

If you have design changes you can PR them to the core-beta repo.

**Comment by Anadema** [comment]
Ok thank you for your answer, I will move to the core-beta and maybe rebuild a new theme.
