### ISSUE TITLE
I cannot reduce the scoreboard update time

### ISSUE THREAD

**Issue by Averiah** [CTFd/CTFd#2658]
Hello everyone! 

I am looking to reduce the scoreboard refresh time, to do this I modified line 175 of scoreboard.js like this: 
![Capture d'écran 2024-11-09 171614](https://github.com/user-attachments/assets/68994edc-37b6-4b12-9965-0a529d382859)
By default, this is 300000, i.e. 5 minutes

But it still doesn't work. I tried with several different ones but the refresh time remains "stuck" at 5 minutes. I have already consulted the issues of other members and found one similar to mine : https://github.com/CTFd/CTFd/issues/446 but the solution doen't work.

I don't want to do this with a web extension which refresh the page automatically.

Do you have any idea how I can do this?

Thank you in advance and have a nice day!

**Comment by ColdHeat** [comment]
In core-beta you can control this with a JS global: 

https://github.com/CTFd/core-beta/blob/main/assets/js/scoreboard.js#L10
