### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by chinu8005** [CTFd/CTFd#2673]
**Environment**: Ubuntu 24.04

- CTFd Version/Commit: 3.6.4
- Operating System: Ubuntu
- Web Browser and Version: Firefox 125.0.2

**What happened?**
I had CTF event, which later I created a backup by exporting CTF. Now while importing it back again, it states 'Import Error: Import Failure: Importing not currently supported for SQLite databases. See Github issue #1988.' 

**What did you expect to happen?**
Like previous time I was able to import those backup normally and last backup zip file states the date which is 30th January 2024. 

**How to reproduce your issue**
1. Download CTFd latest and run docker
2. Create temporary account for registering
3. Go to admin > config > Backup > Select .zip  file > Import
4. Error

**Any associated stack traces or error logs**
I don't what and how to resolve, so any help will do a great.

attaching screenshot;
![image_2024-12-01_19-04-39](https://github.com/user-attachments/assets/c18a67ea-6e79-451b-a6f6-d47a51bd663f)

**Comment by NicoFgrx** [comment]
Hello, 
What database are you using? 
If you don't use one explicitly, by default you'll be using SQLite... which doesn't support imports as explained in the error message.

Have you tried using a postgres/maria/mysql database?
