### ISSUE TITLE
[Bug/Question] Changes in views.py not reflected

### ISSUE THREAD

**Issue by EstebanRemond** [CTFd/CTFd#2684]
**Environment**:

- CTFd Version/Commit: Version 3.7.4
- Operating System: Ubuntu and Windows 11
- Web Browser and Version: Mozilla Firefox 133.0 and Opera GX 115.0.5322.124

I've modified the views.py file to add links to my networks. But the changes are not reflected on the homepage, even after restarting the Docker containers and clearing the browser cache.

How can I ensure that the changes are taken into account?

Here's what I've changed l.209 from views.py : 

```html
<div class="col-md-6 offset-md-3">
        <img class="w-100 mx-auto d-block" style="max-width: 500px;padding: 50px;padding-top: 14vh;" src="{default_ctf_banner_location}" />
        <h3 class="text-center">
            <p>A cool CTF platform from <a href="https://ctfd.io">ctfd.io</a></p>
            <p>Follow ctfd on social media:</p>
            <a href="https://twitter.com/ctfdio"><i class="fab fa-twitter fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://facebook.com/ctfdio"><i class="fab fa-facebook fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://github.com/ctfd"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
        </h3>
        <br>
        <h4 class="text-center">
            <p>Esteban social media:</p>
            <a href="https://github.com/EstebanRemond"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
        </h4>
    </div>
```

Thank you in advance for your help.

**Comment by NicoFgrx** [comment]
Hello, 
I don't think CTFd was designed to be modified like this. If you restart your docker it is likely that it will start from version 3.7.4 "vanilla". 

If you want to add links on the home page, use a ‘theme’ in /admin/config, theme, footer. Here's a screenshot of how it looks on the home page :

![image](https://github.com/user-attachments/assets/b2c2e929-664d-4664-98f6-ee1b95ae5f62)

**Comment by ColdHeat** [comment]
If you are changing views.py you will need to rebuild the docker image. Try `docker compose build` or perhaps https://stackoverflow.com/questions/36884991/how-to-rebuild-docker-container-in-docker-compose-yml
