### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#28]
CTFd needs documentation covering:
1. Deployment options
2. Admin panel breakdown
3. Creating challenges

**Comment by ColdHeat** [comment]
https://github.com/isislab/CTFd/wiki/Deployment

**Comment by mschwager** [comment]
When attempting the nginx + uwsgi deployment (`uwsgi --http-socket :80 -s /tmp/uwsgi.sock -w CTFd:create_app`) I'm still getting the traceback mentioned in issue https://github.com/isislab/CTFd/issues/14. Was there ever a fix for that issue?

I have the latest code with `subdomain=""`.

**Comment by twitched** [comment]
I am having the exact same problem as mschwager

    Traceback (most recent call last):
      File "./CTFd/__init__.py", line 17, in create_app
        SQLALCHEMY_DATABASE_URI = 'mysql://'+username+':'+password+'@localhost:3306/' +    subdomain + '_ctfd',
    TypeError: cannot concatenate 'str' and 'builtin_function_or_method' objects

**Comment by ColdHeat** [comment]
This subdomain code will be removed in the coming releases. 

In the meantime you should use

`uwsgi --http-socket :80 -w CTFd:create_app()`

**Comment by aeibrahim** [comment]
I've added some documentation on running gunicorn as a service. Will add some more details on nginx + gunicorn.

**Comment by ColdHeat** [comment]
The CTFd wiki: https://github.com/CTFd/CTFd/wiki works reasonably well for this. Overtime perhaps we will have a real website for docs.
