### ISSUE TITLE
Advice on E-mail Mechanism

### ISSUE THREAD

**Issue by brant-ruan** [CTFd/CTFd#293]
It seems that when E-mail server and E-mail confirmation are enabled, CTFd will send a new E-mail to the E-mail address input by the new user every time he or she logged in without confirmation yet (At least my SMTP server does like that, I will be apologize if it is my own wrong configuration with my own server). I think it will be better that only one E-mail will be sent at the first time new user signs up, and provide a button allowing the unconfirmed user to receive a new confirmation E-mail if needed.

Anyway, Thanks for your excellent project!

**Comment by ColdHeat** [comment]
Hi @brant-ruan I apologize, I let this slip a bit. 

So the way email confirmations work is every time a user is directed to `/confirm`, CTFd will send out the confirmation email. 

I think you have a good point that it should probably be behind a button.

I think it should probably be put under a `POST` to `/confirm` and then the register route will send the confirmation email on its own and the redirect to `/confirm` will be purely cosmetic.

**Comment by brant-ruan** [comment]
@ColdHeat 

Agree with you. Let the register route encapsulate the confirmation logic is a good idea.
