### ISSUE TITLE
Render plugin's config.html with variables

### ISSUE THREAD

**Issue by farisv** [CTFd/CTFd#309]
Currently in `CTFd.admin.admin_plugin_config`, `config.html` for each configurable plugins are rendered with `render_template_string(config)`. It will be nice if we can pass some variables from plugin code to Jinja when rendering config.html. Or, allow plugin interface to render certain own files for `/admin/plugins/<plugin>` route so it can use `render_template(file, var=value)` for rendering.

**Comment by ColdHeat** [comment]
Hmm, I had a feeling `config.html` would evolve into this but can you give me some examples where you feel `config.html` isn't sufficient for your needs? 

Given that templates can call `get_config()` I think `config.html` works for a good amount of plugins but this could be useful.

**Comment by farisv** [comment]
For example, a plugin that create new database and it need to display database content in config page.

**Comment by ColdHeat** [comment]
That makes sense, but I feel like you can also load this data into `config.html` with an AJAX request and another route. 

My concern is that it becomes more difficult to tell which plugins are going to expose a configuration panel.

**Comment by farisv** [comment]
Yes, this is just an alternative for developer.

In my pull request #310 , my approach is to extend `CTFd.admin.admin_plugin_config`. The behavior is still the same like the original implementation, but for any plugin that has `config.html` and `plugin_config_route` method, return `plugin.plugin_config_route(config, request)` instead of `render_template_string(config)`.

If the plugin has `config.html `and has no `plugin_config_route` method, just return `render_template_string(config)` like usual. If it doesn't have `config.html`, return 404 for GET request or set config for any key-value data except for `nonce` for POST request, just like the original implementation.

**Comment by ColdHeat** [comment]
I think https://github.com/CTFd/CTFd/pull/427 closes this as plugins can now control `config.json` which allows devs to control the configuration links.
