### ISSUE TITLE
Where are the 'country' and 'bracket'

### ISSUE THREAD

**Issue by privat** [CTFd/CTFd#313]
At https://ctf.csaw.io/register there is a bracket and country fields, they seem to be present in the database but not used anywhere in the code. Is there a plugin or a branch that use them? I want them to distinguish qualifying and non-qualifying teams.

**Comment by ColdHeat** [comment]
CTFd was developed for CSAW and upon release it was decided that bracket and country were too specific to CSAW to be included in a widespread public release. But their usage is mildly important in some situations so it's not worth it to remove them from the database. 

At the moment there isn't a plugin or branch that use them but you could be the first to write it! It's a reasonably simple plugin to write and if you'd like to do that there is some documentation here: https://github.com/CTFd/CTFd/wiki/Plugins. Also more example plugins will be released soon.
