### ISSUE TITLE
Awards is not accounted in `user.place()`

### ISSUE THREAD

**Issue by rkkautsar** [CTFd/CTFd#318]
[`user.place()`][user_place] is not accounting awards while [`get_standings()`][get_standings] does. This causes different ordering in scoreboard and team profile. Is this by design?

[user_place]: https://github.com/CTFd/CTFd/blob/master/CTFd/models.py#L200
[get_standings]: https://github.com/CTFd/CTFd/blob/master/CTFd/scoreboard.py#L11

**Comment by ColdHeat** [comment]
This isn't intentional and is a known issue for me. I thought I had fixed it in some branch though. Feel free to submit a PR if you write a fix for it.

**Comment by ColdHeat** [comment]
Thanks for the PR @rkkautsar!
