### ISSUE TITLE
Option to have admin-only notes on challenges

### ISSUE THREAD

**Issue by Pips801** [CTFd/CTFd#321]
We use CTFd for a lot of CTFs, and often times the challenges are written by a lot of people with different backgrounds, and not all of us can figure out how to solve the challenges that others create. If there was a hidden admin-only "How to solve" section, it would help everybody. Often times we will have people come up to us during the CTF and ask about specific CTFs, why isn't this working, etc. and most of us don't know how to answer as we did not author the challenge. 

additionally, it would be really cool to have the option to have the "How to solve" section optionally made visible  at the end of the CTF, so participants can see if they solved it the way they were supposed to, or where they got stuck and what they were supposed to do.

**Comment by ShyftXero** [comment]
I literally started working on this yesterday afternoon. 
We're in the process of vetting our challenges and we're using CTFd to keep track of solved/unsolved.

**Comment by ColdHeat** [comment]
I do like this idea, but I'm not sure if this should be in CTFd master versus a plugin. 

There are going to be some changes to the admin challenges view which would make it easier to add elements into the UI for things like this.

**Comment by deckar01** [comment]
I was chatting with @ShyftXero about this today. I suggested adding it to the core since it would need to be used on all challenge types.

I also suggested allowing multiple notes per challenge so that admins could have an asynchronous discussion.

**Comment by ColdHeat** [comment]
![image](https://user-images.githubusercontent.com/166333/90074060-6425f300-dcc8-11ea-8b5d-80ed1d3ae4e6.png)

Here's how I'm creating this functionality. The same component will be applied to allowing for comments for users, teams, and pages.

**Comment by ColdHeat** [comment]
Closed with #1596
