### ISSUE TITLE
Email Error Handling Needed

### ISSUE THREAD

**Issue by SkeyeLlama** [CTFd/CTFd#346]
The platform does not currently handle/provide feedback for the various potential exceptions that can occur during sending of email. 

The manual email function in the teams page of the admin panel hangs without status if email sending fails.
Other areas result in 500 errors.

The application should fail gracefully and provide feedback to the admin on what went wrong.

**Comment by ColdHeat** [comment]
This is improved in the 1.1 branch. If someone thinks they need more error handling, feel free to re-open.
