### ISSUE TITLE
CTFd challenges file limit

### ISSUE THREAD

**Issue by nia2202** [CTFd/CTFd#370]
Hi,

I am trying to upload a 1.7MB zip file. Seems like its taking so long to upload. Is there a file size limit?

**Comment by ColdHeat** [comment]
No there isn't a file limit unless you set one in nginx or some other reverse proxy. Perhaps your computer is slow?

**Comment by fjh1997** [comment]
due to nginx default filesize upload limit, you canot upload file larger than 1M.
