### ISSUE TITLE
Hints can't be unlocked when challenge name has special charactes (SQLite)

### ISSUE THREAD

**Issue by octaroot** [CTFd/CTFd#377]
I've been running a Czech CTF for a couple days now. Users have been complaining about the inability to buy hints. I investigated and found out that the presence of characters like "ž" or "é" in the challenge name does not play nice with SQLite when buying hints. I'm attaching the error message. The challenge name was _Cože? Jaké heslo?_  (means _What password?_). Removing the Czech characters fixed the problem, but it forces me to not use correct Czech.

Instance details:
 - Debian 9 (stretch)
 - CTFd-1.0.3
 - SQLite (libsqlite3-0:amd64 - 3.16.2-5)

```
ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'INSERT INTO awards (teamid, name, description, date, value, category, icon) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: (24, 'Hint for Co\xc5\xbee? Jak\xc3\xa9 heslo?', None, '2017-09-07 09:46:29.728823', -25, None, None)]
```

**Comment by ColdHeat** [comment]
Hmm.... unicode has been fairly well tested in master. Are you using the specific release or using master? 

A new version will be coming out soon.

**Comment by ColdHeat** [comment]
Actually I can reproduce this on master right now. Thanks for reporting this.

**Comment by ColdHeat** [comment]
I just played around with this a bit. I am not sure what the solution is in Python 2 besides switching the text_factory. 

But! With Python 3 you don't run into this issue. If you can, you should try to switch to Python 3.

**Comment by octaroot** [comment]
Oh, right! Thanks for your help :-)

**Comment by ColdHeat** [comment]
I should also say that while testing in Python 3, I needed to clear the
cookies that were saved in the browser from Python 2.

**Comment by octaroot** [comment]
Yes, that completely solved the issue I initially reported.

However - upon switching to Python 3, there are some issues with e-mails (using my own mailserver). I'm attaching what I did to migrate to Python 3 and what happened, when I tried to reset my password via e-mail.

I'm still using the same configuration, I also executed:
```
apt install python3-dev python3-pip
pip uninstall gunicorn
pip3 install gunicorn
pip3 install -r CTFd-1.0.3/requirements.txt
```

The error:
```
[2017-09-08 10:08:03,547] ERROR in app: Exception on /reset_password [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/CTFd-1.0.3/CTFd/auth.py", line 97, in reset_password
    """.format(url_for('auth.reset_password', _external=True), urllib.quote_plus(token.encode('base64')))
AttributeError: module 'urllib' has no attribute 'quote_plus'
```

So I can't really use Python 3 because it seems to break more stuff

**Comment by ColdHeat** [comment]
Yeah master has a variety of Python 3 fixes that you would need to use. The 1.0.3 release is behind and there will be a new release this weekend.

**Comment by ColdHeat** [comment]
Okay @octaroot here is the solution:

In `challenges.py`
Look for this line:
```python
award = Awards(teamid=session['id'], name='Hint for {}'.format(chal.name), value=(-hint.cost))
```

and change it to:

```python
award = Awards(teamid=session['id'], name=unicode('Hint for {}'.format(chal.name)), value=(-hint.cost))
```

There will be a better fix in this in master.
