### ISSUE TITLE
Pause the event

### ISSUE THREAD

**Issue by synpredator** [CTFd/CTFd#392]
Would be a good idea if it is possible to pause/freeze the event where teams cannot enter submissions rather than just freezing the scoreboard, If anyone knows how I could achieve this would be greatly appreciated

**Comment by ColdHeat** [comment]
You can add a new config value and then check for it in the `/chals/<int:id>` endpoint and then disallow the solve.

**Comment by synpredator** [comment]
@ColdHeat Thanks for the response, Any chance you would have a coding example of this? Not great with python, Sorry to be a bother you

**Comment by ColdHeat** [comment]
https://github.com/CTFd/CTFd/blob/master/CTFd/admin/__init__.py#L91-L228
This route deals with setting up configurations. 

https://github.com/CTFd/CTFd/blob/master/CTFd/challenges.py#L277-L349
This route deals with solving Challenges. 

You can see some of the if statements there that dictate behavior. You just need to add a new config, and then check for it in the route.

**Comment by synpredator** [comment]
Ok thanks, Ill give it a bash

**Comment by ShyftXero** [comment]
This has been implemented in our fork if anyone is interested. 

https://github.com/deckar01/CTFd/commit/9229eec9b65c1ddc1bfecb27f5c0fcdc4442e633

**Comment by ColdHeat** [comment]
This is closed in the 1.1 branch
