### ISSUE TITLE
Suggestion: on wrong keys page, add checkboxes to select and delete several keys at once

### ISSUE THREAD

**Issue by doegox** [CTFd/CTFd#395]
I found the /admin/wrong_keys/1 very handy to watch for people having found the right flag but having difficulties to type it exactly as expected, and so I get a chance to adapt a flag regex and/or to reach these users.
This often means many "almost right" attempts in the wrong keys, that, once I fix the issue, I want to delete from the wrong_keys page. But having to do each of them separately, with a confirmation page, is quite painful. It would be much more convenient to be able to select many keys at once, e.g. with a checkbox on each line and delete them with one common confirmation box.
What do you think?

**Comment by ColdHeat** [comment]
This is a good idea and one that I've wanted to do for awhile but I I will be redesigning a large portion of the admin panel to support these ideas. 

But I would like to first have a REST API that admins interact with first.

**Comment by ColdHeat** [comment]
This was actually implemented in CTFd v2.4!

**Comment by doegox** [comment]
Great, thanks !
