### ISSUE TITLE
Chalboard wrong link

### ISSUE THREAD

**Issue by trainrex42** [CTFd/CTFd#400]
When CTFd is running in a subdirectory, the list of teams that have solved a specific challenge (Element id: chal-solves-names) do not link to the subdirectory

**Comment by ColdHeat** [comment]
So it does. I started fixing it up on this branch: https://github.com/CTFd/CTFd/tree/fixing_subdirectory_deployment

**Comment by ColdHeat** [comment]
Should be fixed in master now. Thanks for reporting the issue!
