### ISSUE TITLE
Plugin wiki page has dead links

### ISSUE THREAD

**Issue by nbanmp** [CTFd/CTFd#404]
A few lines on https://github.com/CTFd/CTFd/wiki/Plugins return 404s. They look like:
<challenge_name>-challenge-modal.hbs [(Example)](https://github.com/CTFd/CTFd/blob/master/CTFd/themes/original/static/js/templates/challenges/standard/standard-challenge-modal.hbs)

**Comment by ColdHeat** [comment]
Yup sorry, this was changed super recently so I honestly forgot to update the links. Will do that now.

**Comment by nbanmp** [comment]
I also just noticed that the line of code: `\<challenge_name\>-challenge-update.js` is trying to escape characters that don't need escaping.

**Comment by nbanmp** [comment]
I think it's worth noting that this is issue #404 and it is about pages that returned 404s.

**Comment by ColdHeat** [comment]
This should be fixed, let me know if you see any other documentation discrepancies.
