### ISSUE TITLE
About Attachment upload

### ISSUE THREAD

**Issue by qux-bbb** [CTFd/CTFd#405]
If you upload an attachment， when you download it，you will see a problem.   
The download link is different with the real download link.  
For example:
download link is: http://127.0.0.1:4000/93a406c537b3c0fedc0ad0ad53621d25/hello.jpg  
real download link is:http://127.0.0.1:4000/files/93a406c537b3c0fedc0ad0ad53621d25/hello.jpg

**Comment by ColdHeat** [comment]
What do you mean? 

Is there a point in the application where you're unable to download the file? Or are you saying that the database stores the file locations without the word files in the URL? The latter is intentional, the former is not.

**Comment by qux-bbb** [comment]
When I upload a file successfully as an admin, I find the file link is :http://127.0.0.1:4000/files/93a406c537b3c0fedc0ad0ad53621d25/hello.jpg  
When I download the file as a normal user, the file link is :http://127.0.0.1:4000/93a406c537b3c0fedc0ad0ad53621d25/hello.jpg  
The "files" is missing.

**Comment by ColdHeat** [comment]
I just tried this myself and I can't reproduce, what browser are you using?

**Comment by qux-bbb** [comment]
Google

**Comment by ColdHeat** [comment]
What version/commit of CTFd are you using? How are you deploying it?

**Comment by qux-bbb** [comment]
I use the new newest version.
About deploying, I just run the prepare.sh and run serve.py.

**Comment by ColdHeat** [comment]
I can't replicate your issue off of master. There is a recent change that could cause this but I can't replicate. 

Can you try disabling your cache using Chrome Inspector and then trying to load it again?

**Comment by qux-bbb** [comment]
I will try it.
Btw, in the serve.py, you should modify 127.0.0.1 to 0.0.0.0.

**Comment by ColdHeat** [comment]
If you can record a video of you downloading the file. 

I won't change 127.0.0.1 to 0.0.0.0. Debug servers are not meant to be used in production.

**Comment by qux-bbb** [comment]
How can I  transfer the video to you?

**Comment by ColdHeat** [comment]
You can upload it as an attachment here, upload it to Youtube or something, or email it to the Github listed on my profile.

**Comment by qux-bbb** [comment]
That's my fault, not yours.  
I use another theme, But the theme has some bugs.
I'm sorry.
Thanks for your help!

**Comment by ColdHeat** [comment]
What theme are you using by chance?

**Comment by qux-bbb** [comment]
The theme I used is  wrote by me.

**Comment by ColdHeat** [comment]
If you ever open source it, you can send a PR to https://github.com/CTFd/themes

**Comment by qux-bbb** [comment]
OK.
