### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by Tskito** [CTFd/CTFd#420]
Hello

I did try to change logo in:
/home/cybercube/CTFd/CTFd/themes/original/static/img/logo.png
But doesn't seem to work for me
I use gunicorn --bind 0.0.0.0:8000 -w 1 'CTFd:create_app()' 
on fresh downloaded img changed bu it doesn't work

**Comment by ColdHeat** [comment]
Change the logo using the Media Library and the Pages editor from the admin side. 

Are you using Docker?
