### ISSUE TITLE
Player Groups

### ISSUE THREAD

**Issue by stefan2904** [CTFd/CTFd#421]
**Plugin Idea:**

* Crate data model `group`
* Allow assigning a player/team to a group. (m:n mapping)

_Example 1:_ An admin creates a group, configures it as public, players can assign themselves to a group.
_Example 2:_ Ad admin creates a group, configures it as private, only admins can add players to that group.
_Other:_ Allow joining of group based on ip, email-address regex, with a token, etc.

**Motivation:**

For longer-running CTFs, think training session or other form of events. You could group all teams/players participating in a group and do special stuff just for them (see below).

**Followup ideas:**

* Per-group highscore
* Challenges only accessible for specific groups

**Comment by hprudent** [comment]
Nice Idea, but I'm working on a concept where Teams should be called Users, and the Player Group will be called Teams.

**Comment by stefan2904** [comment]
Hi @hprudent, thanks for your comment.

As far as I understand what you are working on will allow teams to have multiple logins (players) for one team (with one entry in the highscore, a shared score, etc.), right?

If yes, I am not sure if this is related to my suggestion. Still nice to hear what you are on to. :)

**Comment by hprudent** [comment]
@stefan2904, yes, you are right that's the main concept so a group of people can work together.

**Comment by ColdHeat** [comment]
Stumbled on this old issue. I think this is covered by the Users joining Teams functionality correct?
