### ISSUE TITLE
Exported backup fails on import

### ISSUE THREAD

**Issue by bkimminich** [CTFd/CTFd#434]
I was contacted that the data ZIPs created from my https://www.npmjs.com/package/juice-shop-ctf-cli cannot be imported into the latest CTFd version any longer.

I tried to verify the problem by
1. starting a CTFd server locally (from `master` code)
2. creating one challenge with a static flag and no hints 
3. creating another challenge with a static flag and two hints
4. exporting the data via backup
5. deleting both challenges
6. restarting the server
7. importing the backup ZIP

What I get is
![image](https://user-images.githubusercontent.com/3531020/32339932-831969d4-bff9-11e7-8ff7-efbdac48ffd7.png)

and on the console
```
127.0.0.1 - - [02/Nov/2017 18:12:58] "POST /admin/import HTTP/1.1" 500 -
```

Do you have and idea why this is happening?

**Comment by ColdHeat** [comment]
Yes this is related to https://github.com/CTFd/CTFd/issues/245. In CTFd v 1.0.5 a change to the database was introduced that changes the structure the imports as well. 

A fix for you is discussed here: https://github.com/CTFd/CTFd/issues/245#issuecomment-338465360

I thought you were following along on that conversation so I didn't make an issue my apologies.

**Comment by bkimminich** [comment]
Ok, no problem. Glad there was a discussion ongoing already!

**Comment by bkimminich** [comment]
OK, I caught up on your schema changes and now it works again. I agree that this kind of coupling is not great, but given the rarity of schema changes I am fine with playing "catch up" with you for now.
