### ISSUE TITLE
Need more rate limiting

### ISSUE THREAD

**Issue by ctudoudou** [CTFd/CTFd#436]
There may be duplicate requests regarding the issue of password reset email, which will result in a mail bomb.Thanks for your word.

**Comment by ColdHeat** [comment]
Thanks, I'll be exploring [Flask-Limiter](http://flask-limiter.readthedocs.io/en/stable/) or simply writing my own limiter. 

If you're having trouble with this you can use ReCaptcha through this: https://github.com/tamuctf/ctfd-recaptcha-plugin

**Comment by ColdHeat** [comment]
Closed in 1.1 branch
