### ISSUE TITLE
Creating a page route starting with a /

### ISSUE THREAD

**Issue by a-pasquale** [CTFd/CTFd#449]
Creating a page route that begins with a slash causes problems:

1. Content is not saved
2. Page cannot be removed using the /admin/pages interface

Text on /admin/pages?mode=create seems to suggest that the route should start with a slash.

I suggest stripping any initial slashes or adding validation to this field.

**Comment by ColdHeat** [comment]
Thanks @a-pasquale I never realized that this was an issue! Will resolve promptly.
