### ISSUE TITLE
some requests and questions..

### ISSUE THREAD

**Issue by huntingoose** [CTFd/CTFd#473]
Hi I am a noob to coding but would like to use CTFd for 1 of my projects. i have deployed it on Lubuntu 16.04, running on MySQL.

Please kindly advise me on the following below. Thank you in advance.

 Hi, I'd like to know how can i modify CTFd to have:
1. audit trail - this tracks all the user activities, especially users with administrator rights
2. how can i change the "Team name" to be "user name"?
3. how can i set the user hierarchy to be able to handle Teams with multiple users belongs to the particular team.
4. when editing my profile as a normal user, i am not able to edit my affiliates and the fields. currently only administrators is able to edit for the users.

Please advise.
Thank you

**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**

**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by deckar01** [comment]
1. An audit trail would require you to add logging throughout the entire application. You would need to familiarize yourself with the entire code base.
2. You could search the templates and replace references to "team" with "user".
3. You would have to fundamentally alter the core models and templates. Everything would change and become more complex. You would need a deep understanding of the code base and a significant amount of effort.
4. If it looks editable and there is not clear error messaging, then that sounds like a bug. I would suggest opening a separate issue for that with a more detailed report.

**Comment by ColdHeat** [comment]
As was mentioned, this is a pretty significant undertaking. Some of it may come into master but not any time soon. 

Regarding 4, if you're unable to edit your own profile while logged in you should file a separate issue.
