### ISSUE TITLE
Allow users to choose case-insensitivity of flags

### ISSUE THREAD

**Issue by elreydetoda** [CTFd/CTFd#496]
No bug, just wanted to recommend a ui button that allows you to either choose case sensitive or insensitive. Right now I didn't see any choice for it. Can you go to a python script and add the `i` flag for insensitivity?

**Comment by ColdHeat** [comment]
Regex flags are case insensitive by default. This isn't user changeable but that can be fixed.

**Comment by elreydetoda** [comment]
Awesome, thanks for the info! I didn't know that. (just a suggestion as well, you might want to add that to the wiki so other people know as well). Awesome framework by the way!

**Comment by ColdHeat** [comment]
I think this issue is still relevant so I'm re-opening it to get closed at some point.

**Comment by ColdHeat** [comment]
This is implemented in the 1.2.0 branch. Soon to be merged into master. 

https://github.com/CTFd/CTFd/tree/1.2.0
