### ISSUE TITLE
Unable to Open Newly Created Page: Path Route Incorrect

### ISSUE THREAD

**Issue by mrchisel14** [CTFd/CTFd#549]
**Environment**:

- CTFd Version/Commit: 1.1.1/2e2d458f36278d14c26ec455a11ca5775bf8221f
- Operating System: Ubuntu 16.04
- Web Browser and Version: Chrome Version 63.0.3239.108

**What happened?**
If you attempt to create a new page and access it from the navbar the route will be http(s)://your_path. rather than the full URL. Thus you will get "This site cannot be reached" error.
**What did you expect to happen?**
It should display the entire url with the path appended to it.
**How to reproduce your issue**
From the admin panel create a new page. Set the title to Test and the route to Test and publish. Exit admin mode and click on your new navbar link "Test" it will attempt to redirect you to http(s)://Test. You can see in the page source that the following is incorrect:
```
<a class="nav-link" href="//Test">Test</a>
```
**Suggested fix**
Edit [base.html](../tree/master/CTFd/themes/core/templates/base.html) line [51](https://github.com/CTFd/CTFd/blob/01c334056b71ae4bf43ad4c65b31f517b545bdc5/CTFd/themes/core/templates/base.html#L51) to the following:
```
 {% set route = request.script_root + '/' + page.route %}
```

**Comment by ColdHeat** [comment]
Thanks again @mrchisel14. Unfortunately subdirectory deployments aren't used as heavily so they don't see as much test coverage. 

I'll try to improve this in the future. 

Thanks again for reporting this.
