### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#551]
We should have an API that allows users to query certain data about game state.

**Comment by rashid-nhm** [comment]
Can the API have settings to change certain features? We are trying to run a ctf with a 'shop' feature where one team can buy a package to ban another team temporarily. I've been looking through the sql db and was wondering if it would be possible to do it from there. (I know there is a 'banned' column, but wondering if anything will break if I make another script to change it during a ctf)

**Comment by ColdHeat** [comment]
The features of the API are still being thought out so it's possible that can be implemented. Feel free to write out more ideas in this issue.

**Comment by rashid-nhm** [comment]
If there is to be an API implemented, I wondering if any of the features below can be added to it:

Scoring:
     - Getting all scores
     - Getting score of one team
     - Getting CTF start/end times

Teams:
     - Adding teams
     - Editing any team attributes
     - Banning a team (temporary or permanent)
     - Deleting teams

Challenges:
     - Adding/Editing challenges
     - Updating hints, keys etc
     - Hiding a challenge
     - Hiding a challenge FROM A SPECIFIC TEAM (this can be a new feature)

These are some of the things that I'd like on CTFd, I'll add more if I can think of any. I made a mini script that does some of the things listed above by changing the sql db, I don't think that is the best way. If there is a more robust way, let me know, I might be able to contribute code ideas (if you want)

**Comment by ColdHeat** [comment]
As of 2.0.0, the API exists and is operational. Some of the JS calls aren't completely integrated but that will happen soon.
