### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by bugku** [CTFd/CTFd#562]
[root@localhost CTFd]# python serve.py 
 * Loaded module, <module 'CTFd.plugins.challenges' from '/root/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.keys' from '/root/CTFd/CTFd/plugins/keys/__init__.pyc'>
 * Running on http://127.0.0.1:4000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Loaded module, <module 'CTFd.plugins.challenges' from '/root/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.keys' from '/root/CTFd/CTFd/plugins/keys/__init__.pyc'>
 * Debugger is active!
 * Debugger PIN: 262-992-238

**Comment by ColdHeat** [comment]
I don't understand what the issue is here? 

This looks like normal CTFd operation. Can you please clarify what your issue?

**Comment by bugku** [comment]
The new ctfd config.py file how to configure？

**Comment by ColdHeat** [comment]
What issue are you running into with config.py?
