### ISSUE TITLE
The new version of ctfd does not require mysql run, excuse me, where is the data?

### ISSUE THREAD

**Issue by bugku** [CTFd/CTFd#564]
The new version of ctfd does not require mysql run, excuse me, where is the data?

**Comment by ColdHeat** [comment]
I don't understand what question you're asking. CTFd has never required MySQL. If you are running CTFd without MySQL or Postgres it will generate a sqlite database for you to use. 

Also if you opened an issue prior about this topic, even if it is closed, you should stick to that issue.

**Comment by bugku** [comment]
I did not configure any database, so where ctfd default data is stored？

**Comment by ColdHeat** [comment]
A sqlite database is generated automatically for you in `CTFd/ctfd.db`.

**Comment by bugku** [comment]
Thank you, I see.
Will the speed of SQLite be slower? What database do you recommend？

**Comment by ColdHeat** [comment]
This is covered in the [Wiki](https://github.com/CTFd/CTFd/wiki). The only officially supported database is MySQL.

**Comment by bugku** [comment]
ok

**Comment by bugku** [comment]
How to upgrade the new version of the old version? Is there a wiki?
