### ISSUE TITLE
Unify deployment

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#565]
There is a lot of setup/deployment related code that belongs in a separate repository. We should clean out the random setup files here and move them to a new repo. 

This should also come with a single straightforward way to install CTFd. 

serve.py should become a simple debugging & development tool.

**Comment by tghosth** [comment]
Is a separate repository needed? Would it be possible to just have a new folder called "Deployment" and then sub folders for the different deployment options?

Alternatively, is your suggestion for a separate repository where each deployment option clones the original git repository during deployment. So for example, for a docker deploy, the DockerFile would include a step to clone the code from the main github repository?

**Comment by ColdHeat** [comment]
If it makes sense for Ghost and Discourse to separate their deployment related code into separate repos (ghost-cli, discourse_docker), I think it would work here as well. 

As to the exact implementation details I am not sure yet. Very likely it will be docker based and very likely it will do something about cloning the correct repo. 

I'm not sure if it makes sense for deployment steps to be listed here in the codebase. If anything the deployment instructions  in the wiki/readme should be updated to prioritize docker over other deployment mechanisms.

**Comment by tghosth** [comment]
Don't know if this is what you had in mind but I threw this together mostly for my own entertainment: https://github.com/tghosth/CTFd-docker-deploy
It includes a file based on @nategraf 's docker-compose-production.yml file and your original docker-compose.yml and Dockerfile except that instead of copying in the CTFd files it clones them from the master repository.

I will try write up some very basic instructions at some point.

**Comment by tghosth** [comment]
Ok @ColdHeat I added some basic instructions to the repository as well.

**Comment by ColdHeat** [comment]
I'm satisfied with the overall direction this is taking so I'm closing this in #1566. If people want to add improvements to the deployment files (config.ini, config.py, docker-compose.yml) they can do that a little more easily now. And nginx is already provided in the docker-compose.
