### ISSUE TITLE
Buggy!

### ISSUE THREAD

**Issue by dookgit** [CTFd/CTFd#568]
**Environment**:

  - CTFd Version/Commit:   1.1.2
  - Operating System:   Ubuntu 16.0.4.3 LTS (64bit)
  - Web Browser and Version: Chrome (63) & FireFox (57)

- Database is MySQL and i'm running it through nginx as a reverse proxy to the running instance in gunicorn.

**What happened?**
I'm creating challenges, and testing viewing/completing challenges, and either the challenge creation doesn't work, and it switches back to the Admin challenges list.
The page starts loading, and sits there with the "spinny" progress icon, and eventually Chrome complains the page has become unresponsive, but eventually it comes back.
Either in admin or normal user mode, it keeps flicking the page to /setup randomly, then stops again.

**What did you expect to happen?**
Not any of these bugs :)

**How to reproduce your issue**
Not sure

**Any associated stack traces or error logs**
No errors appearing in ctfd_log and can see all page requests in ctfd_access.log
Is there a way i can enable debug logging to try and get more info?

Yeah just after some advise as to how i can capture these weird things i'm seeing happen.

Cheers

**Comment by ColdHeat** [comment]
Sounds like your database is having difficulties or CTFd is unable to cache data. Try setting up redis.

**Comment by dookgit** [comment]
Cheers Kevin.

I'll enable some MySQL logging, and also setup redis for the cache, see if it makes a difference.

**Comment by ColdHeat** [comment]
Actually, I thought about it a bit. How many workers are you using in gunicorn? 

This might be because each worker created its own cache causing disparity between the workers.

**Comment by dookgit** [comment]
4.  My gunicorn instance config is

CONFIG = {
  'mode': 'wsgi',
  'working_dir': '/opt/cc5_ctfd',
  'python': '/usr/bin/python',
  'user': 'daemon',
  'group': 'daemon',
  'args': (
    '--bind=127.0.0.1:8080',
    '--workers=4',
    '--umask=0027',
    '--log-level=info',
    '--access-logfile=/var/log/gunicorn/ctfd_access.log',
    'CTFd:create_app()',
  ),
}

**Comment by ColdHeat** [comment]
Try updating you config to use only one worker. Or you can setup redis.

**Comment by dookgit** [comment]
Will do, thanks

**Comment by dookgit** [comment]
OK, changed worker to 1, and just from some initial testing....fixed.  Nothing lagging, nothing glitching.
Cheers dude.
