### ISSUE TITLE
Wrong behaviour of scoreboard with a draw and 0-points tasks

### ISSUE THREAD

**Issue by krzys-h** [CTFd/CTFd#577]
We are currently participating in a CTF where the organizers wanted to add additional tasks worth 0 points to not influence the scoreboard. As we are currently the 1st team, I wanted to double check if that wouldn't cause any problems and it turns out it actually does.

Normally when there is a draw, the order in the scoreboard is determined by who solved the challenges first. Unfortunately, if you have any 0-point tasks, it can mess up the scoreboard ordering because it seems to always order teams based on the date of last solved challenge. You can actually go down in the scoreboard because you solved a 0-point challenge.

Follow these steps to reproduce:
* Do some challenge solves to have some scoreboard to work with. Assume it looks like follows (team1 finished first):
1. team1 - 100
2. team2 - 100
* Now, add a challenge worth 0 points
* team1 solves the challenge
* I would expect the scoreboard not to change at this point, but it does as the last solved challenge date of team2 is now earlier than team1's. The scoreboard has changed to:
1. team2 - 100
2. team1 - 100

A simple fix seems to be to just exclude all tasks with points==0 from scoreboard calculations.

**Comment by ColdHeat** [comment]
Hmm interesting... 

I'll need to do some analysis to figure out whats going on because the scoreboard calculation is hairy code. If you have a suggested fix, a PR and a test for the behavior would be super welcome.

**Comment by krzys-h** [comment]
Here is a modification to the scoreboard logic test that shows the issue:

```diff
diff --git a/tests/user/test_user_facing.py b/tests/user/test_user_facing.py
index c3b1ec0..6dbe628 100644
--- a/tests/user/test_user_facing.py
+++ b/tests/user/test_user_facing.py
@@ -339,6 +339,11 @@ def test_scoring_logic():
         flag2 = gen_flag(app.db, chal=chal2.id, flag='flag')
         chal2_id = chal2.id
 
+        # A 0-points challenge that shouldn't influence the scoreboard (see #577)
+        chal0 = gen_challenge(app.db, value=0)
+        flag0 = gen_flag(app.db, chal=chal0.id, flag='flag')
+        chal0_id = chal0.id
+
         # user1 solves chal1
         with freeze_time("2017-10-3 03:21:34"):
             with client1.session_transaction() as sess:
@@ -384,6 +389,19 @@ def test_scoring_logic():
         # user2 should still be on top because they solved chal2 first
         scores = get_scores(admin)
         assert scores[0]['team'] == 'user2'
+
+        # user2 solves a 0-points challenge
+        with freeze_time("2017-10-5 03:55:34"):
+            with client2.session_transaction() as sess:
+                data = {
+                    "key": 'flag',
+                    "nonce": sess.get('nonce')
+                }
+                r = client2.post('/chal/{}'.format(chal0_id), data=data)
+
+        # user2 should still be on top because the 0-points challenge doesn't matter (and he was first anyway) - see issue #577
+        scores = get_scores(admin)
+        assert scores[0]['team'] == 'user2'
     destroy_ctfd(app)
 
 
```

The test currently fails. I will try to provide a fix later.
