### ISSUE TITLE
403-An authorization error has occured-Please try again

### ISSUE THREAD

**Issue by Colbert337** [CTFd/CTFd#586]
**Environment**:

  - CTFd Version/Commit:1.12
  - Operating System:Ubuntu16.04
  - Web Browser and Version:QQBrowser

nginx + docker(gunicorn+mariadb)

**What happened?**
when I setup CTFd and login, the resp is 
403-An authorization error has occured-Please try again

**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
You should clear your cookies and try again. This issue is usually because your CSRF nonce is for a different user or something similar.

**Comment by Colbert337** [comment]
OK.thanks a lot!
