### ISSUE TITLE
Docker startup getting stuck on mysqladmin ping

### ISSUE THREAD

**Issue by ZetaTwo** [CTFd/CTFd#587]
**Environment**:

  - CTFd Version/Commit: ctfd/ctfd:latest from Docker hub (17 days old)
  - Operating System: Amazon Linux AMI 2017.09.j x86_64 ECS HVM GP2
  - Web Browser and Version: N/A

**What happened?**

Trying to setup CTFd with AWS ECS and RDS Aurora.
If I don't set the DATABASE_URL env variable, it works fine and starts.
If I do set the DATABASE_URL to mysql+pymysql://ctfd:<MYPASSWORD>@ctfd.<resource-id>i.eu-west-1.rds.amazonaws.com/ctfd I get stuck on docker-entrypoint.sh:7 `while ! mysqladmin ping -h db --silent; do`

**What did you expect to happen?**

That the ping should succeed and startup continue

**How to reproduce your issue**

Create an ECS task with ctfd/ctfd as image source, set env variable SECRET_KEY and DATABASE_URL. Start container.

I have made sure the container can access the database by running `docker exec container-id mysql -h ctfd.<resource-id>.eu-west-1.rds.amazonaws.com -p<SECRET PASSWORD>` which works.

**Any associated stack traces or error logs**

Just stuck on "Waiting on MySQL"

My question is basically: am I doing something wrong and should somehow make that "db" resolve to the database or is the script incorrect and should take the value of DATABASE_URL into account?

**Comment by ColdHeat** [comment]
Sorry I missed this issue. Within docker-compose each of the containers (including the db) get a hostname related to the service. 

I think we should be taking into account the DATABASE_URL value. 

If you have the time a PR would be great!
