### ISSUE TITLE
127.0.0.1 confirmation

### ISSUE THREAD

**Issue by mike-bailey** [CTFd/CTFd#588]
**Environment**:

  - CTFd Version/Commit: Not latest, I can get the commit if I'm not missing something
  - Operating System: Ubuntu, Docker-compose
  - Web Browser and Version: Chrome, multiple reports

**What happened?**

People signing up and getting the confirm email

**What did you expect to happen?**

Confirm email is providing 127.0.0.1:8000 rather than our actual domain

**How to reproduce your issue**

Probably just set it up? I'm probably missing a config or env var somewhere which is why I'm not taking this report too seriously

Thanks.

**Comment by ColdHeat** [comment]
Hmm not sure here. 

https://github.com/CTFd/CTFd/blob/master/CTFd/utils.py#L650-L658

This is the code that deals with sending email confirmations. 

https://stackoverflow.com/questions/12162634/where-do-i-define-the-domain-to-be-used-by-url-for-in-flask

I believe this is necessary? I'm not 100% sure here but please let me know if this fixes it for you.

**Comment by mike-bailey** [comment]
set it in config.py and no dice I'm afraid. I'll set it in urls.py manually I guess.

**Comment by ColdHeat** [comment]
Just a hypothesis. Perhaps running inside of Docker is causing CTFd to be unable to detect its domain properly?

**Comment by mike-bailey** [comment]
It's reached internally as 127.0.0.1:8000 in Docker for sure, but moving out of Docker isn't an option I'm afraid. utils.py also no dice unless I'm missing something cached which is entirely possible.

**Comment by mike-bailey** [comment]
Doe it take app.config['SERVER_NAME'] from config.py by default?

**Comment by mike-bailey** [comment]
Confirmed a caching issue so it'll be a sec then I can sort it.

**Comment by mike-bailey** [comment]
I may have found it - https://stackoverflow.com/questions/22315887/flask-404-when-using-server-name

Sorry for filing issues that aren't issues :P

**Comment by mike-bailey** [comment]
(Confirmed resolved)

**Comment by nadrojisk** [comment]
@mike-bailey could you say how exactly you solved this? I am running into this issue as well
