### ISSUE TITLE
Email whitelisting

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#603]
How do we add the ability to whitelist emails such that we can only allow certain email addresses? 

Perhaps this should be implemented as a regular expression on the email address?

**Comment by stefan2904** [comment]
Related to #441

**Comment by ColdHeat** [comment]
Functionality for this exists in the 2.0.0 branch but is missing a way to configure the whitelisted domains at the moment.

**Comment by ColdHeat** [comment]
This is now implemented in 2.0.0.
