### ISSUE TITLE
About the Dockefile

### ISSUE THREAD

**Issue by CoolDUp** [CTFd/CTFd#621]
Docker will rebuild all package on CTFd files change, when network is bad is a bad experience.
about step of requirements installtion  need to change.

**Comment by ColdHeat** [comment]
You can simply use the docker-compose.yml file which mounts the host directory read only which lets you avoid rebuilding.

**Comment by CoolDUp** [comment]
You have use 
[
volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro               ## but = 0
]
