### ISSUE TITLE
Admin challenges sorting

### ISSUE THREAD

**Issue by nierardi** [CTFd/CTFd#650]
Right now the challenges are sorted in the admin panel are sorted by ID (essentially, by creation time) and are not easy to navigate through.

It would be nice to sort these by category -> name, or interactive sorting by clicking the headers.

I am trying to implement this myself, but can't seem to find the code that renders the admin challenges page.

**Comment by ColdHeat** [comment]
Hi @nierardi, the code should be handled by Jinja here: https://github.com/CTFd/CTFd/blob/master/CTFd/themes/admin/templates/challenges.html#L52

I think this is a matter of adding in a JS library that allows for the sorting of tables.

**Comment by wayneaswilliams** [comment]
The StormCTF template uses the following script to sort the ['teams' page](https://github.com/stormctf/CTFd-Theme-StormCTF/blob/master/stormctf/templates/teams.html#L12).

This allows JavaScript based sorting, but it does not save its order if that's what's desired. Hope this helps.

`<script>
function sortTable(n) {
    var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
    table = document.getElementById("teams");
    switching = true;
    dir = "asc";
    while (switching) {
        switching = false;
        rows = table.rows;
        for (i = 1; i < (rows.length - 1); i++) {
            shouldSwitch = false;
            x = rows[i].getElementsByTagName("TD")[n];
            y = rows[i + 1].getElementsByTagName("TD")[n];
            if (dir == "asc") {
                if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                    shouldSwitch = true;
                    break;
                }
            } else if (dir == "desc") {
                if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                    shouldSwitch = true;
                    break;
                }
            }
        }
        if (shouldSwitch) {
            rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
            switching = true;
            switchcount++;
        } else {
            if (switchcount == 0 && dir == "asc") {
                dir = "desc";
                switching = true;
            }
        }
    }
}
</script>`

**Comment by ColdHeat** [comment]
This was implemented in CTFd v2.4
