### ISSUE TITLE
Teams improvement

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#654]
Teams should be made up of users. A user can create a team and then other users will join based off of a secret token value or invite or something similar. 

This improves submission tracking, banning, and anything team related. 

One potential problem is that this increases friction for registering to play in CTFs. The current one account flow is very easy and simple. Should this perhaps be optional?

**Comment by wayneaswilliams** [comment]
I believe this should be an optional switch. Some events we host require single user competition only, while others request teams work together.

**Comment by ColdHeat** [comment]
This is implemented in the 2.0.0 branch. Closing to clear it from the milestone.
