### ISSUE TITLE
Not selecting "Static" or "Regex" when adding new challenge returns HTTP 400

### ISSUE THREAD

**Issue by jaredthecoder** [CTFd/CTFd#67]
The title explains it all.

Possibly handle this better by indicating in the UI that the field is required and if it doesn't validate then ask the user to fill it in again.

**Comment by aeibrahim** [comment]
Encountered the same issue. Agree with @jaredmichaelsmith, it should not let you proceed without selecting on or the other.

**Comment by ColdHeat** [comment]
Sorry I will resolve this today
