### ISSUE TITLE
Challenges with Images Included are difficult to view in mobile environments.

### ISSUE THREAD

**Issue by hjeonee** [CTFd/CTFd#671]
**Environment**:

  - CTFd Version/Commit: 1.2.0 Release 
  - Operating System: Docker on Ubuntu 16.04 
  - Web Browser and Version: Chrome on Android

**What happened?**

If you upload a challenge with an image included(using the html <img= > tag), it is really difficult to view the image on a mobile environment.

In CTFd, when you click on a challenge, a vary narrow pop-up comes up, showing the problem. However, if you upload a relatively large image, the image shifts to the right side, looking like a ㅏ shape. 
This not only looks bad on desktop/laptop environments, but also makes it impossible to drag the image on mobile environments. 

**What did you expect to happen?**

I hoped the image would align center, making a nice look on desktop env, and dragging available on mobile env.

**How to reproduce your issue**

Just try making a challenge with an image included, and try it yourself.

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Can you provide a screenshot? It makes it much easier to establish a baseline of what the issue is even though I do understand what you are saying. 

You should be able to scroll the image though no?

**Comment by hjeonee** [comment]
![image_aligning_to_right](https://user-images.githubusercontent.com/41981925/45086379-f79a3500-b13d-11e8-987b-bb5c0e533a58.png)

@ColdHeat 

Like the screenshot atached, if you upload an image file to a challenge that is way too big for the pop-up width, it goes out of the boarder, making not only the user experience bad, but also unavailable to the user to view the image properly.

I suggest 1) resizing the image automatically when the admin uploads one to the appropriate width, 2) aligning it at the center . Additionally, I hope the white boarders of the pop-up matches with the image.

Secondly, as you mentioned, scrolling up and down is available on mobile, but scrolling left and write is impossible. Sometimes, if you find the exact spot(I assume it's the middle of the uploaded image), but most times, scrolling left and right is just impossible, so users have to download the image and view it externally.

Even if I resize the image to about 450x300, it is just "perfect" to view in a desktop environment, but the right side is unable to view on a mobile environment.

![450x300_computer](https://user-images.githubusercontent.com/41981925/45087004-852a5480-b13f-11e8-9575-d5b0851ae82e.png)
![450x300_mobile](https://user-images.githubusercontent.com/41981925/45087093-c15db500-b13f-11e8-9023-1cf795929042.png)

**Comment by ColdHeat** [comment]
Okay I understand. As a temporary fix, you should be able to do something like `<img class="img-fluid" src="image">` since challenge windows support HTML markup.

**Comment by ColdHeat** [comment]
c467931c518bbd734f318491bf8ab363cea831b9 should make this a little better.
