### ISSUE TITLE
Hidden challanges not completely hidden

### ISSUE THREAD

**Issue by brendsimons** [CTFd/CTFd#680]
**Environment**:

  - CTFd Version/Commit: 1.2.0
  - Operating System: Debian 9

**What happened?**
A non-admin user can view the content of hidden challenges by navigating to the "/chals/<int:chal_id>" route and users can easily guess the id of a hidden challange.
Hidden challanges are not visible at "/chals/solves" and it is also not possible to submit an answer for a hidden challange.
But being able to view the hidden challanges in advance is unfair.

**What did you expect to happen?**
The server should give a 403 or 404 error message. 

**How to reproduce your issue**
Just create a new challange and hide it using the "Hidden" checkbox.
Log in as a normal user and navigate to "/chals/<int:chal_id>", with the id replaced by the id of the challange.

**Comment by anthraxx** [comment]
41933cc367ad3c09ff7d3d0d6c224365c790125f is the fix for this, but its not applied to the 2.0.0 branch yet

**Comment by ColdHeat** [comment]
As of 72ac6c846edf467751c47d6e7a2afa4da59d4579 this is resolved in 2.0.0 and tested for in the API.
