### ISSUE TITLE
CTFd admin page does not expire cookies.

### ISSUE THREAD

**Issue by jfransua** [CTFd/CTFd#683]
**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**

CTFd Admin UI does not expire cookies.  Someone was able to get admin access and keep their browser open.  When we tried to change the password and lock them out, they were able to continue to make changes even after application restart by keep ing the browser open after a password change.

**What did you expect to happen?**

Browser cookies would expire after a password of an admin was changed so that someone that was able to get admin access would be locked out if they were able to get in.

**How to reproduce your issue**

Login as admin user.  Change password or change password of another user.  Their cookie should expire and then they would no longer get access.   This could be triggered by at least a restart of the application or a timeout of the cookie(s).

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
This is an unfortunate side effect of how Flask handles authentication. At the moment there's not enough to solve this in 1.2.0 but by 2.0.0 this should be fixed.

**Comment by ColdHeat** [comment]
This is basically #658

**Comment by ColdHeat** [comment]
Closing in favor of #658

**Comment by ColdHeat** [comment]
While Flask sessions inherently make this difficult, it doesn't really make much sense that a user was magically able to gain admin access.
