### ISSUE TITLE
The session correlation in config.py is set to be invalid.

### ISSUE THREAD

**Issue by c0ny1** [CTFd/CTFd#701]
Hello, first of all, I'd like to thank CTFd for its great convenience. Recently, I was building a CTFd environment. I found a bug when implementing the session of caching CTFd with redis. Project/CTFd/config. PHP: 56-66

```
'''
I just don't have time to change my routine.
http://pythonhosted.org/Flask-Session/#configuration
'''
SESSION_TYPE = "filesystem"
'''
SESSION_FILE_DIR is a configuration value used for Flask-Session.
http://pythonhosted.org/Flask-Session/#configuration
'''
SESSION_FILE_DIR = "/tmp/flask_session"
```

But I run the CTFd, found no CTFd write session files in the `/tmp/flask_session` directory. Then search the all code, found that the project does not introduce `flask_session` module. But according to the code comments, the two Settings that do should be used to set the `Flask-Session`.
So I tried to introduce the flask_session module in /CTFd/__init__.py:

```
from flask_session import Session
```

In create_app function `app. Config. From_object (config)` this line of code, add the following line of code:

```
Session (app)
```

Finally, the session file was successfully written to the/tmp/flask_session destination. This method also implements redis to store CTFd session.
I don't know if this is a bug, I'm looking forward to the author's reply.

**Comment by ColdHeat** [comment]
In the original config.py, it's stated that these variables aren't used. https://github.com/CTFd/CTFd/blob/master/CTFd/config.py#L57

They're not used so Flask uses the default of having sessions being inside of the cookie. We will not be using redis to store sessions until 2.0.0. 

See #658

**Comment by ColdHeat** [comment]
I'm also not sure why your config.py is so different. Are you running from a fork?

**Comment by c0ny1** [comment]
Sorry, I didn't notice your comment. I am the code from the official project.

**Comment by ColdHeat** [comment]
You'll have to wait for 2.0.0 to use redis backed sessions. So hopefully you are using the official version because it will be easier to upgrade :)

**Comment by c0ny1** [comment]
OK, look forward to the new version. At present, we first use the code that we have changed. Thank you.
