### ISSUE TITLE
docker-entrypoint.sh should 'exec' gunicorn

### ISSUE THREAD

**Issue by GrahamDumpleton** [CTFd/CTFd#713]
**Environment**:

  - CTFd Version/Commit:

master (https://github.com/CTFd/CTFd/commit/41933cc367ad3c09ff7d3d0d6c224365c790125f)

  - Operating System:

Docker container.

  - Web Browser and Version:

N/A

**What happened?**

The gunicorn process doesn't run as process ID 1 in a docker container. This means it will not receive signals sent to the container, thus allowing it to shutdown correctly. This is because the ``docker-entrypoint.sh`` shell script process runs as process ID 1, but a shell process will not propagate signals to the sub process.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     1 1000220+  20   0   13292   1536   1304 S   0.0  0.0   0:00.02 docker-entrypoi
    22 1000220+  20   0  123808  20744   5080 S   0.0  0.0   0:00.22 gunicorn
    25 1000220+  20   0  280516  54076   5508 S   0.0  0.1   0:00.62 gunicorn
```

Best practice when running in a container is that any top level script would use ``exec`` to run the actual web application server as then it inherits process ID 1 and it will receive signals correctly.

That this isn't done means that in a system like Kubernetes, a pod/container may not shutdown promptly when told to and Kubernetes fallbacks on a failsafe timer and force kills after that, thus not allowing the web server to shutdown gracefully. In the case of a ``Recreate`` deployment strategy in Kubernetes, this means the application can be offline for the whole period of the delay up to when Kubernetes has to force kill the pod/container.

**What did you expect to happen?**

Expect ``gunicorn`` to be process ID 1.

The code in ``docker-entrypoint.sh`` should be:

```
# Start CTFd
echo "Starting CTFd"
exec gunicorn 'CTFd:create_app()' \
    --bind '0.0.0.0:8000' \
    --workers $WORKERS \
    --worker-class 'gevent' \
    --access-logfile "${LOG_FOLDER:-/opt/CTFd/CTFd/logs}/access.log" \
    --error-logfile "${LOG_FOLDER:-/opt/CTFd/CTFd/logs}/error.log"
```

Note that this doesn't present any issues around reaping of zombie processes as is expected of process ID 1 in a container, as ``gunicorn`` handles that. If changing later to another WSGI server such as ``waitress``, which isn't multi process, then you would need to introduce a dumb init process as ``waitress`` doesn't reap child processes correctly.

**How to reproduce your issue**

Run docker image.

**Any associated stack traces or error logs**

N/A

**Comment by ColdHeat** [comment]
Thanks @GrahamDumpleton! This is very informative. If you're interested I would I accept a PR to the 2.0.0 branch. If not I'll resolve this soon. 

I assume you were trying to deploy CTFd on Kubernetes and ran into this?

**Comment by GrahamDumpleton** [comment]
I am looking at CTFd for someone else who would be running it on OpenShift variant of Kubernetes for an event next year. There are a number of other changes in both ``Dockerfile`` and ``docker-entrypoint.sh``as well which could be made to align with best docker practices. I can provide a PR for changes, but creating this issue was just to see what sort of response I would get first.

I don't know what base version of CTFd they will want to use, so I may start by creating issues for things as I work off stable version in a fork. We can then discuss changes and where you may want to merge them. Can then create separate PR as necessary against appropriate branch.

**Comment by ColdHeat** [comment]
@GrahamDumpleton I'm not sure how far your fork has gotten but I would strongly suggest working against the 2.0.0 branch because it is due for release pretty soon and should have a number of improvements. 

We do use the Dockerfile and docker-entrypoint.sh in other areas but I don't see any downsides from your proposed changes so PR away.

**Comment by ColdHeat** [comment]
I've made the proposed change in the 2.0.0 branch and will remove from the milestone and close the issue when merged to master.
