### ISSUE TITLE
Add S2I build script so image can be built in OpenShift.

### ISSUE THREAD

**Issue by GrahamDumpleton** [CTFd/CTFd#722]
When deploying to OpenShift, you can deploy an existing image stored on external image registry, or you can build from source code in OpenShift and deploy it.

In the latter, you can do either a docker build using the existing ``Dockerfile``, or you can use a S2I (Source-to-Image) build. Supporting the latter is beneficial as docker builds are often disabled in OpenShift clusters because a docker build needs to run stuff as root. Ability to do either source build in OpenShift can be useful during development.

The only change to existing files will be to allow the listener port for gunicorn to be overridden through an environment variable (as S2I images default to port 8080).

```
# Start CTFd
echo "Starting CTFd"
exec gunicorn 'CTFd:create_app()' \
    --bind "0.0.0.0:${PORT:-8000}" \
    --workers $WORKERS \
    --worker-class 'gevent' \
    --access-logfile "$ACCESS_LOG" \
    --error-logfile "$ERROR_LOG"
```

On top of that, will be a new ``.s2i/bin`` subdirectory with wrapper scripts to help with build and run phase.

I will supply PR for this. I will also supply as part of PR, templates for deploying CTFd in OpenShift from external image, or from build done in OpenShift, using either docker or S2I build.

**Comment by ColdHeat** [comment]
This seems very specific to your use cases. I'm not really convinced this belongs upstream. 

Accepting very specific deployment files in the hopes they'd help others hasn't been a great strategy in the past and I'd rather not repeat that mistake.

**Comment by ColdHeat** [comment]
I think a case could be made for Kubernetes. As for Openshift I don't know. I don't know of anyone running it or running CTFd with it. 

Assuming the other issues you've reported get resolved, why can't the generated Docker images be used in k8s or Openshift?

**Comment by GrahamDumpleton** [comment]
I was setting up way of doing builds because of uncertainty at this point at least of being able to access pre-built image which followed the 2.0.0 branch.

A template is also still useful if want to deploy Redis/MySQL at the same time and avoid needing to run a lot of manual steps. The template allows it to be done in one command.

The intent was to have one template be able to use an image of a remote registry such as Docker Hub, but wasn't aware that there was any image out there yet that could use that with, so not done that one yet.

**Comment by GrahamDumpleton** [comment]
I have had a think about what to do about this. I will back out the S2I and template additions related to OpenShift. I will not go forward with including any Kubernetes example configuration. The only thing I will leave in which was related to this was the ability to override the port used by ``gunicorn`` using the ``PORT`` environment variable as that does have some use in plain docker context.

If you can though indicate whether you feel any other changes are not what you want that would be helpful now, as can then decide whether should instead just maintain build and run scripts for container based deployments with improvements needed, as a separate repository and ignore the existing ``Dockerfile`` and ``docker-entrypoint.sh``. Thanks for at least looking at the changes.
