### ISSUE TITLE
Does kombu package need to be in requirements.txt file?

### ISSUE THREAD

**Issue by GrahamDumpleton** [CTFd/CTFd#724]
**Environment**:

  - CTFd Version/Commit:

2.0.0 branch

  - Operating System:

MacOS X, but using docker, so doesn't matter.

  - Web Browser and Version:

N/A

**What happened?**

Enabled ``REDIS_URL`` but when container starts up get the error:

```
Traceback (most recent call last):
--
  | File "manage.py", line 8, in <module>
  | app = create_app()
  | File "/opt/app-root/src/CTFd/__init__.py", line 139, in create_app
  | message_queue=app.config.get('CACHE_REDIS_URL')
  | File "/opt/app-root/lib/python3.6/site-packages/flask_socketio/__init__.py", line 187, in init_app
  | write_only=write_only)
  | File "/opt/app-root/lib/python3.6/site-packages/socketio/kombu_manager.py", line 43, in __init__
  | raise RuntimeError('Kombu package is not installed '
  | RuntimeError: Kombu package is not installed (Run "pip install kombu" in your virtualenv).
```

**What did you expect to happen?**

No error.

**How to reproduce your issue**

In my case container image was built using Source-to-Image (S2I) build in OpenShift using Python 3.6. Not sure if that combination has something to do with it, or whether ``kombu`` needs to be added to ``requirements.txt`` for 2.0.0 branch.

Adding:

```
kombu==4.2.1
```

to ``requirements.txt`` does fix the issue, but does that have other implications.

**Any associated stack traces or error logs**

See above.

**Comment by ColdHeat** [comment]
No there shouldn't be a need to have Kombu in CTFd. We don't use celery at this time. 

Tests are running for 2.0.0 as of now which might help: https://travis-ci.org/CTFd/CTFd/branches

**Comment by GrahamDumpleton** [comment]
Think I resolved what the issue was. I had the value in ``REDIS_URL`` wrongly formatted. Even though ``celery`` wasn't mentioned in the URI, the wrong format made something think that must have been using Celery and so expected ``kombu`` to be available. Adding ``kombu`` got past that problem. Was only after that could see that ``REDIS_URL`` was in fact wrongly formatted.
