### ISSUE TITLE
Use sqlalchemy Python script to test availability of database.

### ISSUE THREAD

**Issue by GrahamDumpleton** [CTFd/CTFd#725]
**Environment**:

  - CTFd Version/Commit:

2.0.0 branch

  - Operating System:

MacOS X, but building/deploying container images.

  - Web Browser and Version:

N/A

**What happened?**

The check using ``mysqladmin`` in ``docker-entrypoint.sh`` will fail if the target system only has MySQL libs package and doesn't have MySQL clients package.

Further, the wiki says:

> My personal suggestion is MySQL or MariaDB, but PostgreSQL will work just fine.

The ``docker-entrypoint.sh`` script is hard wired to MySQL and expects MySQL clients package to be installed. Would be nice that if also want to use PostgreSQL and only provide alternate ``Dockerfile`` and not change anything else, that this would work and didn't have to rewrite it. Similarly, if use alternate build system like S2I for OpenShift, that can reuse existing scripts unchanged.

**What did you expect to happen?**

Would hope database check is database agnostic and work with only database libs available.

**How to reproduce your issue**

In my case hit it as building from source using S2I (Source-to-Image) builder in OpenShift. The Python base images do not include MySQL clients package.

**Any associated stack traces or error logs**

```
Waiting for ctfd-mariadb to be ready
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
 ...
```

**Solution**

Suggest database agnostic check be used which uses small Python script and ``sqlalchemy``.

```
import os
from sqlalchemy import create_engine
database = create_engine(os.getenv('DATABASE_URL'))
database.execute('select 1')
```

This has added benefit that also checks that required Python packages installed correctly and work before starting up the application.

It should also technically work for SQLite if someone wanted to override ``DATABASE_URL`` and use SQLite with file system path, to directory in a mounted persistent volume, rather than have database created in default location of source code directories where not possible to mounted a persistent volume. Although in SQLite case the database file would technically need to exist first.

**Comment by ColdHeat** [comment]
This is vaguely reasonable but in the wiki (which needs MAJOR rewriting): 

> Note: Due to development constraints the officially supported database is MySQL/MariaDB although development efforts will focus on feature parity between SQLite, MySQL/MariaDB, and Postgres.

Also SQLAlchemy-Utils has a built in helper function for this: https://sqlalchemy-utils.readthedocs.io/en/latest/database_helpers.html?highlight=database_exists#database-exists

**Comment by GrahamDumpleton** [comment]
Then can use:

```
function database_ready() {
    python -c "import os, sys
from sqlalchemy_utils.functions import database_exists
database_exists(os.getenv('DATABASE_URL')) or sys.exit(1)" > /dev/null 2>&1
}
```

The docs for ``database_exists()`` leave a bit to be desired because it isn't a simple case of returning ``True`` or ``False``. It can still raise an exception such as in the case of not being able to route to the database. So still have to throw away output to avoid the exception tracebacks filling the logs.

**Comment by tmarlok88** [comment]
Hi @GrahamDumpleton 
Would you please create a PR from your fix?
I have the same problem and started to fix it, but discovered that you already wrote one...

**Comment by ColdHeat** [comment]
@tmarlok88 @GrahamDumpleton if either of you wants to PR this I can merge it in.

**Comment by ColdHeat** [comment]
Neither of the proposed scripts actually replicate the original purpose of `mysqladmin ping`. Both of these functions only work if the database inside of the database exists.

**Comment by ColdHeat** [comment]
I don't see a great way to solve this problem and while I do occasionally need to

**Comment by ColdHeat** [comment]
I don't see a great way to solve this and we don't officially support Postgres. If someone wants to figure this out I'm happy to merge in the fix but it should actually work.

**Comment by GrahamDumpleton** [comment]
When deploying images for databases in docker containers, you would usually tell it the name of the database to create, eg., using ``MYSQL_DATABASE`` environment variable. You don't want a manual step to create it yourself as then you can't have an out of the box deploy and things would be more difficult to setup. So don't understand why "only work if the database inside of the database exists" would be an issue.

**Comment by ColdHeat** [comment]
CTFd manually concerns itself with the creation of the database because it prefers to set things properly if it doesn't already exist. Not everyone deploys everything using Docker containers. 

We only need to see if the database server is available, CTFd takes care of the rest. If the script doesn't work beforehand then you get scenarios where it just never works when it would have before.

**Comment by frankli0324** [comment]
let me bring this ancient issue back alive. I couldn't stand the `default-mysql-client` package standing in the way between me and the "totally-no-package-installed image"

```python
import sqlalchemy
from CTFd.config import Config

sqlalchemy.create_engine(Config.DATABASE_URL).raw_connection().ping()
```

I think this does the trick.

btw, I think the `docker-entrypoint.sh` should also read configs from `config.ini`.
