### ISSUE TITLE
Challenge 

### ISSUE THREAD

**Issue by showipintbri** [CTFd/CTFd#727]
I'm using CTFd for the first time. I have my challenges setup and they are working, but they are in order of point value rather than name. How can I adjust the sorting order for the challenges and flags?

**Comment by ColdHeat** [comment]
Hi @showipintbri, as we discussed in Slack, you would need to create your own custom theme or modify the `chalboard.js` file in the core theme.

**Comment by showipintbri** [comment]
Thanks Kevin. I wasn't sure where I'd get a response so I posted in Slack and GitHub. Thanks for steering me in the right direction.
