### ISSUE TITLE
Exported backup fails on import

### ISSUE THREAD

**Issue by sebastian0x00** [CTFd/CTFd#728]
Hello! 
I want to make a backup of the Challenges, teams and configuration (backup--> export) but when I try to do it, after a minute, I have the following error:

"504 Gateway Time-out"

My configuration:

Nginx 1.10.3
Ubuntu 16.04.5 LTS
Both Firefox and Google Chrome

Any idea how to fix it? or export the backup?

Thanks!

**Comment by ColdHeat** [comment]
There are known issues with exports and imports. You can try importing using the command line importer `import.py`.

The related issue is #567 which will be resolved in the next CTFd release.
