### ISSUE TITLE
Challenge deletion

### ISSUE THREAD

**Issue by OctaveSec** [CTFd/CTFd#733]
**Environment**:

  - CTFd Version/Commit: 2.0.0
  - Operating System: Ubuntu 18.04
  - Web Browser and Version: Chrome 69.0.3497.100/Firefox 60.3.0esr

**What happened?**

Missing delete option for challenges in the Admin panel.

**Comment by ColdHeat** [comment]
As of 7bc231afbfc3ceb49718f20ccfb1edf27b7ce307 this should be implemented.
