### ISSUE TITLE
Challenge update button firefox issue

### ISSUE THREAD

**Issue by OctaveSec** [CTFd/CTFd#734]
**Environment**:

  - CTFd Version/Commit: 2.0.0
  - Operating System: Ubuntu 18.04
  - Web Browser and Version: Firefox 60.3.0esr

**What happened?**

Admin Challenge update button non-functional in Firefox. 

Chrome functions correctly.

**Comment by ColdHeat** [comment]
As of c979997c4c8e49145f7bcca92bfb7029f898cbb6 this should be fixed. Thanks for reporting this issue!
