### ISSUE TITLE
Import function broken

### ISSUE THREAD

**Issue by OctaveSec** [CTFd/CTFd#735]
**Environment**:

  - CTFd Version/Commit: 2.0.0
  - Operating System: Ubuntu 18.04
  - Web Browser and Version: Chrome Version 69.0.3497.100 & Firefox 60.3.0esr 

**What happened?**

This was v2.0.0 -> v2.0.0 

Trying to Import DB from another instance of CTFd 2.0.0 fails (clicking the yellow import button does nothing) in both Chrome and Firefox

**Comment by OctaveSec** [comment]
[CTF2-2.2018-11-14.zip](https://github.com/CTFd/CTFd/files/2582468/CTF2-2.2018-11-14.zip)

**Comment by ColdHeat** [comment]
Thanks for reporting this. This should be fixed now.
