### ISSUE TITLE
Adding Prerequisite does not show options

### ISSUE THREAD

**Issue by OctaveSec** [CTFd/CTFd#738]
**Environment**:

  - CTFd Version/Commit: 2.0.0
  - Operating System: Ubuntu 18.04
  - Web Browser and Version: Chrome 69.0.3497.100 / Firefox 60.3.0esr

**What happened?**

Trying to add a prerequisite to a challenge does not give you any options in the drop down. But, if you add a blank prerequisite the drop down menu will populate after. 

**How to reproduce your issue**

Admin->Challenges-> (challenge)#requirements

With a blank requirement click Add Prerequisite, then click the box. You will now see options to add.

**Comment by ColdHeat** [comment]
Should be closed with 93f7911. Thanks for reporting and testing!
