### ISSUE TITLE
Prerequisite delay 

### ISSUE THREAD

**Issue by OctaveSec** [CTFd/CTFd#739]
**Environment**:

  - CTFd Version/Commit: 2.0.0
  - Operating System: Ubuntu 18.04
  - Web Browser and Version: Chrome 69.0.3497.100 / Firefox 60.3.0esr

**What happened?**

Once the challenge was solved I had to manually refresh the page for the second challenge to show up

**What did you expect to happen?**

Not have to manually refresh page once the prereq was completed.

**Comment by ColdHeat** [comment]
Should be closed with 93f7911. Thanks for reporting and testing!
