### ISSUE TITLE
Sphinx Documentation

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#742]
CTFds documentation is lacking and we need a system for it.

**Comment by Helithumper** [comment]
Hello there. I was thinking we might want to get a "Documentation" or "Needs Doc" tag for issues. I'm totally up for adding docs, but it would be easier to tag them.

**Comment by ColdHeat** [comment]
Sure that makes sense. I created the `documentation` tag.

**Comment by ColdHeat** [comment]
I'm going to create the docs folder and start looking at getting the basic documentation flow started.
