### ISSUE TITLE
serializeJSON is not a function

### ISSUE THREAD

**Issue by Iansus** [CTFd/CTFd#743]
**Environment**:

  - CTFd Version/Commit: c8031b38c27926b8166174af331bc2b4ab614c1b
  - Operating System: Debian 9
  - Web Browser and Version: Opera

**What happened?**
When trying to save CSS in admin "Appearance":
`$(...).serializeJSON is not a function`

**What did you expect to happen?**
Expected it to save the config, nothing happened.

**How to reproduce your issue**
Clone and use

**Any associated stack traces or error logs**
None

**Proposed solution**
Add https://github.com/marioizquierdo/jquery.serializeJSON/raw/master/jquery.serializejson.min.js to the static js directory and use it in admin view.

**Comment by ColdHeat** [comment]
Hi @Iansus, I had someone try this out and they weren't able to reproduce. Can you try clearing your cache or using incognito mode to see if the problem goes away? 

Also we use a custom serializeJSON defined here: https://github.com/CTFd/CTFd/blob/master/CTFd/themes/admin/static/js/utils.js#L19

**Comment by ColdHeat** [comment]
I was able to set CSS on Opera Version:56.0.3051.104 on Ubuntu 18.04. If you can still reproduce this error please re-open this issue.

**Comment by UserB1ank** [comment]
I met this error too, how to fix it? I tried solutions above ,but failed
