### ISSUE TITLE
Mail Plugin does not work - UnboundLocalError: local variable 'auth' referenced before assignment

### ISSUE THREAD

**Issue by patrickhener** [CTFd/CTFd#779]
**Environment**:

  - CTFd Version/Commit: master
  - Operating System: Debian
  - Web Browser and Version: Chrome and Firefox current

**What happened?**

Setting up an E-Mail server and afterwards registering to the ctfd will result in no Mails beeing sent as well as an error.

**What did you expect to happen?**

Getting E-Mails from ctfd

**How to reproduce your issue**

Pull current master. Start by serve.py. Configure local smtp server (noauth, port 25, no tls). Register as a user.

**Any associated stack traces or error logs**

Dec 04 14:18:41 cat-dmz-1-web bash[21619]: 192.168.2.1 - - [04/Dec/2018 14:18:41] "GET /socket.io/?EIO=3&transport=polling&t=1543929521041-0 HTTP/1.1" 200 -
Dec 04 14:18:49 cat-dmz-1-web bash[21619]: [2018-12-04 14:18:49,443] ERROR in app: Exception on /register [POST]
Dec 04 14:18:49 cat-dmz-1-web bash[21619]: Traceback (most recent call last):
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     response = self.full_dispatch_request()
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     rv = self.handle_user_exception(e)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/.local/lib/python2.7/site-packages/flask_restplus/api.py", line 583, in error_router
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     return original_handler(e)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     reraise(exc_type, exc_value, tb)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     rv = self.dispatch_request()
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/ctfd/CTFd/utils/decorators/visibility.py", line 81, in _check_registration_visibility
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     return f(*args, **kwargs)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/ctfd/CTFd/utils/decorators/__init__.py", line 143, in ratelimit_function
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     return f(*args, **kwargs)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/ctfd/CTFd/auth.py", line 198, in register
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     email.verify_email_address(user.email)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/ctfd/CTFd/utils/email/__init__.py", line 39, in verify_email_address
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     sendmail(addr, text)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/ctfd/CTFd/utils/email/__init__.py", line 15, in sendmail
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     return smtp.sendmail(addr, text)
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:   File "/home/ctfd/ctfd/CTFd/utils/email/smtp.py", line 43, in sendmail
Dec 04 14:18:49 cat-dmz-1-web bash[21619]:     if auth:
Dec 04 14:18:49 cat-dmz-1-web bash[21619]: UnboundLocalError: local variable 'auth' referenced before assignment
Dec 04 14:18:49 cat-dmz-1-web bash[21619]: 192.168.2.1 - - [04/Dec/2018 14:18:49] "POST /register HTTP/1.1" 500 -
Dec 04 14:18:49 cat-dmz-1-web bash[21619]: 192.168.2.1 - - [04/Dec/2018 14:18:49] "GET /static/user.css HTTP/1.1" 200 -

**Comment by ColdHeat** [comment]
This should be fixed as of 473acdbdc3457f4fd778fbd692ae353c531804ba. If you run into the problem again please feel free to re-open.

**Comment by ColdHeat** [comment]
Hmm you'll need to provide more information because if CTFd says a message
is sent it's been passed off to the server for processing and is out of its
hands.

**Comment by patrickhener** [comment]
What information would we need to debug further. I might paste the "from hand" method here showing you what commands I issue (all but auth login).

And is there any logs I could include or is there a debug flag or such?

> Hmm you'll need to provide more information because if CTFd says a message is sent it's been passed off to the server for processing and is out of its hands.
> […](#)

**Comment by patrickhener** [comment]
Hi there, so I got some input here

```
ctfd@cat-dmz-1-web:~$ openssl s_client -connect smtp.strato.de:465
CONNECTED(00000003)
depth=2 C = DE, O = Deutsche Telekom AG, OU = T-TeleSec Trust Center, CN = Deutsche Telekom Root CA 2
verify return:1
depth=1 C = DE, O = T-Systems International GmbH, OU = T-Systems Trust Center, ST = Nordrhein Westfalen, postalCode = 57250, L = Netphen, street = Untere Industriestr. 20, CN = TeleSec ServerPass DE-2
verify return:1
depth=0 C = DE, O = Strato AG, OU = Rechenzentrum, ST = Berlin, L = Berlin, CN = smtp.strato.de
verify return:1
---
Certificate chain
 0 s:/C=DE/O=Strato AG/OU=Rechenzentrum/ST=Berlin/L=Berlin/CN=smtp.strato.de
   i:/C=DE/O=T-Systems International GmbH/OU=T-Systems Trust Center/ST=Nordrhein Westfalen/postalCode=57250/L=Netphen/street=Untere Industriestr. 20/CN=TeleSec ServerPass DE-2
 1 s:/C=DE/O=T-Systems International GmbH/OU=T-Systems Trust Center/ST=Nordrhein Westfalen/postalCode=57250/L=Netphen/street=Untere Industriestr. 20/CN=TeleSec ServerPass DE-2
   i:/C=DE/O=Deutsche Telekom AG/OU=T-TeleSec Trust Center/CN=Deutsche Telekom Root CA 2
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIILTCCBxWgAwIBAgIQLfeY8QVR4JonWKp9+Lg5OzANBgkqhkiG9w0BAQsFADCB
2TELMAkGA1UEBhMCREUxJTAjBgNVBAoTHFQtU3lzdGVtcyBJbnRlcm5hdGlvbmFs
IEdtYkgxHzAdBgNVBAsTFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxHDAaBgNVBAgT
E05vcmRyaGVpbiBXZXN0ZmFsZW4xDjAMBgNVBBETBTU3MjUwMRAwDgYDVQQHEwdO
ZXRwaGVuMSAwHgYDVQQJExdVbnRlcmUgSW5kdXN0cmllc3RyLiAyMDEgMB4GA1UE
AxMXVGVsZVNlYyBTZXJ2ZXJQYXNzIERFLTIwHhcNMTgwNDA1MDUxMzExWhcNMTkw
NDEwMjM1OTU5WjB0MQswCQYDVQQGEwJERTESMBAGA1UEChMJU3RyYXRvIEFHMRYw
FAYDVQQLEw1SZWNoZW56ZW50cnVtMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAcT
BkJlcmxpbjEXMBUGA1UEAxMOc210cC5zdHJhdG8uZGUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQC5jlESeuzi3FUIxeza6DDzFRODk59xqfJ+3rLzJn4Y
wwgfng9H31X31BhqH5b4MpHkfQZzkAqJ9vN/9von6d7VZZ5Npexgyyhv3kQoSquM
suymlu5hSGIDx9r1xX/Sm6N+WZ6+ZWw5k6wi9hoZNHqBJckTA7CWQaXGlvLP5LIL
7v+XTqEPGkI3R98F7Xt8xpvyBCggMU3Za/tK+ApsNY9jy/uL1OAo4Y304s2/DOnm
n0wAw278zvJpjbT6RyTNrN2qarUatW5OtQmoHNn9glJQJehLYJGbFZzLWwSjSp2i
xU7x1GbY9+sKlvXPSLEyaOK/kc9kXKej7jsFxXOtsAp3AgMBAAGjggRTMIIETzAf
BgNVHSMEGDAWgBRUBClvopPGkDFFwD3eK+IKaYCSXzAOBgNVHQ8BAf8EBAMCBaAw
HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMB0GA1UdDgQWBBQ7Qp1lgjnY
yNZbnTmC1q+xXedAvDBZBgNVHSAEUjBQMEQGCSsGAQQBvUcNAjA3MDUGCCsGAQUF
BwIBFilodHRwOi8vd3d3LnRlbGVzZWMuZGUvc2VydmVycGFzcy9jcHMuaHRtbDAI
BgZngQwBAgIwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDovL2NybC5zZXJ2ZXJwYXNz
LnRlbGVzZWMuZGUvcmwvVGVsZVNlY19TZXJ2ZXJQYXNzX0RFLTIuY3JsMIGTBggr
BgEFBQcBAQSBhjCBgzAzBggrBgEFBQcwAYYnaHR0cDovL29jc3Auc2VydmVycGFz
cy50ZWxlc2VjLmRlL29jc3ByMEwGCCsGAQUFBzAChkBodHRwOi8vY3JsLnNlcnZl
cnBhc3MudGVsZXNlYy5kZS9jcnQvVGVsZVNlY19TZXJ2ZXJQYXNzX0RFLTIuY2Vy
MAwGA1UdEwEB/wQCMAAwGQYDVR0RBBIwEIIOc210cC5zdHJhdG8uZGUwggJwBgor
BgEEAdZ5AgQCBIICYASCAlwCWgB2AG9Tdqwx8DEZ2JkApFEV/3cVHBHZAsEAKQaN
sgiaN9kTAAABYpQ5FwkAAAQDAEcwRQIhAP/4vUiYcYDTbu/hfBNDdWX3rTOfZSlP
xvk60QFjOOItAiBOZn1zWv5fCnMzeCYzr0jWJfAjE2p3lRjrIiQDI2igMgB2AO5L
vbd1zmC64UJpH6vhnmajD35fsHLYgwDEe4l6qP3LAAABYpQ5FtMAAAQDAEcwRQIh
AOmCGpLwOj59hOaGWBnfZZJftTNWI0A0iNAO5LBNiBnOAiBj/cwtuwmxc7FTKblF
EQq++yWuNNGJB28loTwkXj+4hQB3AFWB1MIWkDYBSuoLm1c8U/DA5Dh4cCUIFy+j
qh0HE9MMAAABYpQ5GBcAAAQDAEgwRgIhAI9GoEDhrrY3hJyJigqNB+2ZJwE6Ma13
ciGN/AWG+AciAiEA+r2qPS9LhuMGy2+DpQRtpIB41jLCVj+JwXOE1u22iOUAdgC7
2d+8H4pxtZOUI5eqkntHOFeVCqtS6BqQlmQ2jh7RhQAAAWKUORklAAAEAwBHMEUC
IDSVJnSdqNDUtvDz+xmW8EiD5ivvlIQFxHLF7Yho7jN7AiEA95RNGcGIZrpdXIj8
1a/PU1WxtIAuDGq4BkI/inNDQi0AdwCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jj
d80OyA3cEAAAAWKUORk9AAAEAwBIMEYCIQDgcGbtDOdOm+DoKopKJeWMBGYRoOhi
nTxlsymYtwH7ogIhAOSPS6ieqJ89/mocwGwK6w71W9Skv4OMgfn1U0gDq8LZMA0G
CSqGSIb3DQEBCwUAA4IBAQA3PZ++MsXaeabEu+AQVws1jgJP6IZSj0OEVUl2jJrz
KjPfY8OUbQCcARZ2OJj33UOkNur1ScS/RjIYwYKjfuG8yB24knlElmiK7fd3SYa/
tmGU01j5XqgUzoKHYsAd6bJUmPnwIe8hZzfPDQkeNzmgsSfXwi9CSqLbejvaivjp
6zziXyZ1ISZqNkH+kTUGEl0qsPZljdkcAR2XPDRjJv7BEJF4iqEBIma/eeZXtb1g
nUa7D1cBTOWuKRYw/7vSk1v7LWMPgulGZIALwbE+ThmnLV6EENTGRBRXc35po4p7
KLoMAJXHBLUMiAMBRaLreqxt5aK5gK/ytB+wpvIy5eGM
-----END CERTIFICATE-----
subject=/C=DE/O=Strato AG/OU=Rechenzentrum/ST=Berlin/L=Berlin/CN=smtp.strato.de
issuer=/C=DE/O=T-Systems International GmbH/OU=T-Systems Trust Center/ST=Nordrhein Westfalen/postalCode=57250/L=Netphen/street=Untere Industriestr. 20/CN=TeleSec ServerPass DE-2
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-521, 521 bits
---
SSL handshake has read 4355 bytes and written 370 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: D4FFE3E1985A9B45C08F3702610E4DCDC3D6424C75452EE864EBF2D29CF3E3A52ED3DE065F94AA0D4C6B4D36531352D6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1544038439
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
220 smtp.strato.de ESMTP RZmta (P10 -)
ehlo ctf.de
250-smtp.strato.de greets 84.187.42.118
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-DELIVERBY
250-SIZE 104857600
250-AUTH DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
250-REQUIRETLS
250-BURL imap
250-CHUNKING
250 HELP
auth login
334 VXNlcm5hbWU6
base64 username goes here
334 UGFzc3dvcmQ6
base64 password goes here
235 2.7.0 OK Authenticated
MAIL FROM:<ctf@henerthebox.de>
250 2.1.0 Sender ok
rcpt to:<patrickhener@gmx.de>
250 2.1.5 Recipient ok
data
354 3.0.0 Enter data for mail with id 0094b4uB5JYRmBu
Subject: Testnachricht

Das ist ein Test.

.
250 2.0.0 queued as 0094b4uB5JYRmBu
```
That are the commands I issued. And the mail got delivered.

As can be seen here: [image-email](https://imgur.com/jkYKBdb)

And those are the settings in my ctfd server:

[image-ctfd-settings](https://imgur.com/KsbE9RN)

Username and password are the same i tried on the command line.

So why does it say it sends the mail but it will not be received?

**Comment by patrickhener** [comment]
You know what, nevermind. I am dump. It landed in spam folder. Just ignore the whole thing.
