### ISSUE TITLE
Not possible to download files as anonymous user

### ISSUE THREAD

**Issue by stefan2904** [CTFd/CTFd#789]
**Environment**:

  - CTFd Version/Commit: 2.0.0 from master
  - Operating System: Debian Stretch, Ubuntu 18.04, ...
  - Web Browser and Version: Firefox 63

**What happened?**

* In admin, set visibility of challenges to public
* Logout
* Open challenge view (`/challenges`)
* Click on a challenge with a file
* Try to download the file (`/files/c378d661d2c9e103c4409cd4c92d801f/alice_bob.py`
* => Error 403

**What did you expect to happen?**

* ...
* Click on a challenge with a file
* Try to download the file
* File downloads

**How to reproduce your issue**

_see above_

**Any associated stack traces or error logs**

_none_

**Comment by stefan2904** [comment]
I think the reason is this `if` (or rather the corresponding `else`): https://github.com/CTFd/CTFd/blob/master/CTFd/views.py#L191

We fixed this in our fork by removing this `else` and adding a `@check_challenge_visibility` decorator to the function instead.

**Comment by stefan2904** [comment]
I just realized that there is a test for this: https://github.com/CTFd/CTFd/blob/master/tests/users/test_views.py#L178

So it appears this is intended behavior.  But I am not sure why. If i enable a public challenge list, I also want user's to be able to download files.

I propose to declare this a bug in the "specification" then.

An alternative is to create a separate config switch for that.

**Comment by stefan2904** [comment]
Tests for the way I understood that functionality: 

```python
            set_config('challenge_visibility', 'public')
            # Unauthed user should return 200
            with app.test_client() as client:
                r = client.get(url)

                assert r.status_code == 200
                assert r.get_data(as_text=True) == 'testing file load'

            set_config('challenge_visibility', 'private')
            # Unauthed user should return 403
            with app.test_client() as client:
                r = client.get(url)

                assert r.status_code == 403
                assert r.get_data(as_text=True) != 'testing file load'

```

**Comment by ColdHeat** [comment]
I think this is an oversight. Thanks for pointing out the issue!

**Comment by ColdHeat** [comment]
By the way I don't think wrapping the files handler in check_challenge_visibility is the best solution because that handler also deals with file downloads for regular non-challenge files.

**Comment by stefan2904** [comment]
Good point. 

So it probably makes more sense to include `get_config('challenge_visibility')` somewhere in the check (for challenge files).

**Comment by ColdHeat** [comment]
@stefan2904 this should fix your issue. Would be great if you could confirm. Thanks for reporting!

**Comment by stefan2904** [comment]
It works, thank you!
