### ISSUE TITLE
Import configuration, but still required to go to setup page

### ISSUE THREAD

**Issue by Dummy51** [CTFd/CTFd#791]
In the case of automation and importing a complete configuration, there is no need to go to setup page enter the CTF Name.
IN the case where the configuration is imported with the admin credential, the setup steps must be bypassed.

Any idea on to skip it. I look at utils.py but not successful.

THanks,

**Comment by ColdHeat** [comment]
CTFd has no guarantees after import that the CTF is fully setup however I do believe that if you specify setup is True in the config.json of the import you shouldn't be asked to setup. Is that not the case?

**Comment by Dummy51** [comment]
> CTFd has no guarantees after import that the CTF is fully setup however I do believe that if you specify setup is True in the config.json of the import you shouldn't be asked to setup. Is that not the case?

Yes, thanks. In the config.json, <setup> need to be set to "false" to skip setup.
