### ISSUE TITLE
Hide flag-submit-box for anonymous users

### ISSUE THREAD

**Issue by stefan2904** [CTFd/CTFd#797]
**Environment**:

  - CTFd Version/Commit: 2.0.1 from master
  - Operating System: Debian Stretch, Ubuntu 18.04, ...
  - Web Browser and Version: Firefox 63

**What happened?**

* In admin, set visibility of challenges to public
* Logout
* Open challenge view (`/challenges`)
* Click on a challenge
* Box to submit flag is displayed, but not possible to submit flag

![selection_615](https://user-images.githubusercontent.com/527767/49752426-a6578f80-fcb0-11e8-9d8b-52f2d9bcdb8d.png)

**What did you expect to happen?**

* ...
* Open challenge view (`/challenges`)
* Click on a challenge
* **NO** Box to submit flag is displayed

![selection_616](https://user-images.githubusercontent.com/527767/49752417-a192db80-fcb0-11e8-93a5-d6910300a11b.png)

**How to reproduce your issue**

_see above_

**Any associated stack traces or error logs**

_none_

**Comment by stefan2904** [comment]
**Suggested fix**

I think it would be enough to hide [this lines](https://github.com/LosFuzzys/CTFd/blob/losctf/CTFd/plugins/challenges/assets/view.html#L69-L79 ),

e.g. via `{% if id is defined %}` - but since this is a client-side template this not not work that way.

**Comment by ColdHeat** [comment]
CTFd should be automatically redirecting the user to a login page. This is likely another regression.

**Comment by ColdHeat** [comment]
So just to be clear, instead of not showing the submission box the way that we handle submissions for unauthed users is that they should be able to submit and then upon submission they get redirected to the login page. 

I should have a fix for this soon.

**Comment by stefan2904** [comment]
Ok, thanks for the clarification. That's indeed not the way I understood that feature.

**Comment by ColdHeat** [comment]
Being able to submit encourages a sign up I think 😄

**Comment by ColdHeat** [comment]
Hey @stefan2904, could you confirm that this is fixed? Users should be allowed to submit but after submission they should be redirected to login.

**Comment by stefan2904** [comment]
Seems to work for us (https://fuzzy.land/) - thanks!
