### ISSUE TITLE
Deploying CTFd latest version

### ISSUE THREAD

**Issue by ArkAngels** [CTFd/CTFd#808]
Hello, I'm currently trying to deploy my CTFd. But I'm having 500 Internal server Error.
My error log:

> [Sun Dec 16 23:59:03.531415 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487] mod_wsgi (pid=27063): Target WSGI script '/var/www/[my-domain]/launcher.wsgi' cannot be loaded as Python module.
> [Sun Dec 16 23:59:03.531598 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487] mod_wsgi (pid=27063): SystemExit exception raised by WSGI script '/var/www/[my-domain]/launcher.wsgi' ignored.
> [Sun Dec 16 23:59:03.531630 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487] Traceback (most recent call last):
> [Sun Dec 16 23:59:03.531660 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487]   File "/var/www/[my-domain]/launcher.wsgi", line 8, in <module>
> [Sun Dec 16 23:59:03.531829 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487]     application = create_app()
> [Sun Dec 16 23:59:03.531841 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487]   File "/var/www/[my-domain]/CTFd/__init__.py", line 117, in create_app
> [Sun Dec 16 23:59:03.531907 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487]     stamp()
> [Sun Dec 16 23:59:03.531916 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487]   File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 98, in wrapped
> [Sun Dec 16 23:59:03.532056 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487]     sys.exit(1)
> [Sun Dec 16 23:59:03.532083 2018] [wsgi:error] [pid 27063] [remote 103.80.236.252:50487] SystemExit: 1
> 

My launcher.wsgi file:

> #!/usr/bin/python
> import sys
> 
> sys.path.insert(0, '/var/www/[my-CTFd-dir]')
> sys.path.insert(1, '/var/www')
> 
> from CTFd import create_app
> application = create_app()

And I did give my .ctfd_secret_key file read permission
Also my config for apache is:

> <VirtualHost *:443>
> 	ServerName [my-domain]
> 	ServerAlias www.[my-domain]
> 	SSLEngine on
> 	Include /etc/letsencrypt/options-ssl-apache.conf
> 	WSGIDaemonProcess CTFd user=www-data group=www-data threads=20
> 	WSGIScriptAlias / /var/www/[my-CTFd-dir]/launcher.wsgi
> 
> 	<Directory /var/www/[my-CTFd-dir]>
> 		WSGIProcessGroup CTFd
> 		WSGIApplicationGroup {GLOBAL}
> 		Require all granted
> 	</Directory>
>      SSLCertificateFile /etc/letsencrypt/live/[my-domain]/fullchain.pem
> 	SSLCertificateKeyFile /etc/letsencrypt/live/[my-domain]/privkey.pem

Any idea why it still give me 500? Thank you before.

**Comment by ColdHeat** [comment]
Perhaps `launcher.wsgi` isn't executable? 

> Target WSGI script '/var/www/[my-domain]/launcher.wsgi' cannot be loaded as Python module. 

This line looks suspicious. I don't think this is an issue within CTFd though.
