### ISSUE TITLE
Registering as new user on https://ctfd.io/

### ISSUE THREAD

**Issue by hmm14e** [CTFd/CTFd#809]
**Environment**:
  - Web Browser: https://ctfd.io/

**What happened?**
 - When you register as a new user, it sends an email confirmation. When you get the email and click on the confirmation link, it asks you to login. Once you login, it just resends the confirmation email. 

**What did you expect to happen?**
 - I expected to be able to login. 

**How to reproduce your issue**
 - Register as new user on https://ctfd.io/
 - Go to email to confirm
 - Click on confirmation link
 - Try logging in

**Comment by ColdHeat** [comment]
@hmm14e Can you forward the confirmation email that you received to support@ctfd.io?
