### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by MaartenPentinga** [CTFd/CTFd#810]
**Environment**:

  - CTFd Version/Commit: latest
  - Operating System: ubuntu 18.04
  - Web Browser and Version: chrome:latest
**What happened?**
I put '<script>alert(1)</script>' in notification message. Pops as '1'. Inteded it as a joke. But when you see the content its empty. Also when reloading notifications you get the pop-up again. 

**What did you expect to happen?**

Nothing ;) Tried to make some funny joke to contestents but then this happend. 

**How to reproduce your issue**

Login as admin; go to notifications and insert:

<script>alert(1)</script>

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
This is intentional. Admins are allowed to send HTML and JS to contestants in notifications and challenge descriptions for better styling and functionality.  Unless there's a way for a user to gain higher privilege this isn't considered a bug.
