### ISSUE TITLE
python requirements cause a build error

### ISSUE THREAD

**Issue by racterub** [CTFd/CTFd#816]
**Environment**:

  - CTFd Version/Commit: 324f885
  - Operating System: Ubuntu 16.04 x64
  - Web Browser and Version: N/A

**What happened?**
When Build CTFd via docker-compose, pip installation goes wrong.
pyICU does not installed properly (as error log at the end of this issue)

**What did you expect to happen?**
Everything works perfectly

**How to reproduce your issue**
Pull the repo from the github and do `docker-compose up`

**A solution to fix this**
I've got a way to fix this.
After my research, pyICU does have this kind of issue in 2018 (ovalhub/pyICU#70).
pyICU is required to install in dataset library.(dataset -> normality -> pyICU)
https://github.com/CTFd/CTFd/blob/324f8859a1ac3e3e7cdd7cd10df79b6d1da365b0/requirements.txt#L16
~~After adding `pyicu==1.9.3` everything works fine~~

**Any associated stack traces or error logs**
```
Collecting pyicu>=1.9.3 (from normality>=0.5.1->dataset==1.1.0->-r requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/c2/15/0af20b540c828943b6ffea5677c86e908dcac108813b522adebb75c827c1/PyICU-2.2.tar.gz (211kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2i066i/pyicu/setup.py", line 53, in <module>
        ''')
    RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2i066i/pyicu/
ERROR: Service 'ctfd' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by racterub** [comment]
** Update **
Just install normality with version 0.6.1 will fix this problem.
Version 0.6.1 does fit all the version requirements, and pyicu does not included in the installation.

**Comment by ColdHeat** [comment]
Hi @racterub, thanks for reporting this I'll take a look.

**Comment by Gamn69** [comment]
This also is happening to me

**Comment by ColdHeat** [comment]
This should already be resolved in the latest release.

**Comment by Gamn69** [comment]
Where is the latest release?

**Comment by ColdHeat** [comment]
You can pull from master or go to https://github.com/CTFd/CTFd/releases.

**Comment by Abemarkar23** [comment]
I tried the same thing, its not working for me either

**Comment by ColdHeat** [comment]
Are you both properly rebuilding your images or just running `docker-compose up`?

**Comment by ColdHeat** [comment]
I just ran `docker-compose build --no-cache` off of master (which is currently 2.0.2) and it built successfully.

**Comment by ColdHeat** [comment]
I also just ran `docker-compose up` after that build and it ran successfully. You might need to clear out the `.data` folder as well if there's stale data from previous invocations of docker-compose.

**Comment by racterub** [comment]
@Abemarkar23 , @Gamn69 Can you guys upload your docker-compose logs? It will be very helpful :)

Issue here is that you on check on normallity's repo, [commit](https://github.com/pudo/normality/commit/6889018efa85a4846a914e9fb5f93ae617267103), which requires pyICU to install.
