### ISSUE TITLE
Rest API documentation

### ISSUE THREAD

**Issue by bitskri3g** [CTFd/CTFd#821]
We use ctfd internally pretty heavily, and to this point we've been hand-jamming instances for every class, which works, but is time consuming.  The Rest API is a great add, but the docs are lacking (e.g. /api/v1 API browser doesn't have the params listed, etc.)

We've been internally 'figuring out' the various parameters of the Rest APIs internally and would like to assist in documenting this feature with examples (cURL) if the project is interested.

As an example, here is one of the first example scripts we wrote that demonstrates basic functionality:

```
#!/bin/bash

## Initial setup.  Make admin user and write cookie for follow-on API calls
nonce=$(curl -s http://127.0.0.1:8000/setup -c cookie | grep 'name="nonce"' | awk '{ print $4 }' | cut -d'"' -f2)
curl "http://127.0.0.1:8000/setup" \
-H "Content-Type: application/x-www-form-urlencoded" \
-b cookie \
--data "nonce=$nonce&ctf_name=test&name=admin&email=test"%"40test&password=foobar&user_mode=users"

## Get current user
curl -X GET "http://127.0.0.1:8000/api/v1/users/me" -H  "accept: application/json" -b cookie

## Make a new user
curl -X POST "http://127.0.0.1:8000/api/v1/users" -H "content-type: application/json" -b cookie -d \
'{"name":"foobar",
"email":"foo@bar.com",
"password":"123",
"type":"user",
"verified":"false",
"hidden":"false",
"banned":"false"}'

## make a new challenge
curl -X POST "http://127.0.0.1:8000/api/v1/challenges" -H "content-type: application/json" -b cookie -d \
'{"name":"somechal",
"category":"hacks",
"state":"hidden",
"value":"9001",
"type":"standard",
"description":"sample challenge"}'

## add a flag to a challnge
curl -X POST "http://127.0.0.1:8000/api/v1/flags" -H "content-type: application/json" -b cookie -d \
'{"challenge":"1",
"content":"eleventy",
"type":"static"}'

## Upload a file to a challenge.  You need to use a nonce from the admin page of the challenge you're editing.
nonce=$(curl -s http://127.0.0.1:8000/admin/challenges/1 -b cookie | grep nonce | cut -d'"' -f2)
curl -X POST "http://127.0.0.1:8000/api/v1/files" -b cookie  \
-F "file=@some-local-file.png" \
-F "nonce=$nonce" \
-F "challenge=1" \
-F "type=challenge"
```

Our goal is to fully automate ctfd deployments and allow them to be dynamically generated by sourcing challenge definitions from version control (probably in yaml), and this is the first step in that process.

**Comment by ColdHeat** [comment]
Hi @bitskri3g, glad to hear you're using CTFd in your classroom!

So this would definitely be a great help. I think the best approach would be to take a look at the built in Flask-RestPlus Swagger features: https://flask-restplus.readthedocs.io/en/stable/swagger.html. Perhaps you can PR in the code necessary to get that working. 

Also what would be useful would be to see how we can get a documentation system in place: #742. 

At the moment there's not a great place to put any of these requests. 

Second point is that I wouldn't consider the API really meant for consumption this way just yet. I think you'd be better off creating a script that interacts with the CTFd app directly: 

```
from CTFd import create_app()
app = create_app()
with app.app_context():
    # Do stuff here
    pass
```

A second option would be to use a CTFd import/export to share data between CTFd instances and be able to reload quickly. I would recommend this because it requires the least programming and should be built-in.

**Comment by ColdHeat** [comment]
In terms of the yaml challenge specification I believe there is a plugin that aims to solve that problem (you can check out the plugins repo for it). It's not something on our roadmap but it should be easily accomplished by a secondary script, webhook, or plugin.

**Comment by Helithumper** [comment]
I do agree that some sort of documentation-creating comments as you have mentioned with Flask-RestPlus Swagger would be incredibly handy. That way documentation can be auto-generated instead of manually edited, eliminating stale documentation.

**Comment by ColdHeat** [comment]
Once there's a good swagger JSON in place we can use https://github.com/Redocly/redoc to make a pretty website for it. The current swagger JSON doesn't provide enough info to make this worthwhile just yet though.

**Comment by ColdHeat** [comment]
I have a basic working idea of how to leverage the existing schemas to power documentation #1480. I don't expect that the documentation will be perfect but it should cover most of the cases. 

It would be great if the community could try the approach out and document endpoints.

**Comment by MillsapCyber** [comment]
@ColdHeat I see you've added the "completed" label to this issue, does this mean that the swagger UI is operational? I pulled & built the 3.0.0-dev branch but it doesn't seem like /api/v1/swagger_ui exists. It also seems like the initial setup commands @bitskri3g posted are no longer functional. I've been working on automating a ctfd deployment and unfortunately I've had to resort to using selenium to set up the scoreboard, create users, and retrieve api keys. Once you have the bearer token it's relatively simple to figure out the endpoints, such as creating challenges, adding flags, and attempting to score, but there doesn't seem to be a clear way of either creating users or api tokens for said users via the api. It's doable via selenium, however this approach is much slower and not the most reliable long term solution.

**Comment by ColdHeat** [comment]
Swagger UI has always worked, it just needs to be enabled from config.py. If you're trying to automate a CTFd deployment a described by OP, I would recommend using https://github.com/CTFd/ctfcli to do it.

**Comment by ColdHeat** [comment]
Swagger UI is now integrated into https://docs.ctfd.io/docs/api/.

**Comment by ColdHeat** [comment]
I'm closing this since there is now an online interface to view the existing endpoints. Missing areas should be documented by the community over time. 

@MillsapCyber https://ctfd.readthedocs.io/en/latest/configuration.html#swagger-ui
