### ISSUE TITLE
get_standings sorted by sumscore->max(solves.id,awards.id)

### ISSUE THREAD

**Issue by misads** [CTFd/CTFd#833]
Right now the standings are sorted by (sumscore,id). 
As can found in `CTFd/utils/scores/__init__.py:get_standings`
```python
standings_query = db.session.query(
            Model.id.label('account_id'),
            Model.oauth_id.label('oauth_id'),
            Model.name.label('name'),
            sumscores.columns.score
        ) \
            .join(sumscores, Model.id == sumscores.columns.account_id) \
            .filter(Model.banned == False, Model.hidden == False) \
.order_by(sumscores.columns.score.desc(), sumscores.columns.id)
#(the sumscores.columns.id is a union of solves.id and awards.id)
```
When two users get the same sumscore,  their standings depend on max(max(Solves.id),max(Awards.id)).

I think it would be better to sorted by (sumscore,date) because solves.id and awards.id are not the same thing, if more than one user gets the same score with both solves and awards, who reaches the score first should rank ahead.

**Comment by ColdHeat** [comment]
I'm not entirely sure what you're referring to. Can you provide a test that CTFd would fail? 

If two teams reach the same score, the person who reaches the score first is considered the person on top. An award should not change that logic.

**Comment by misads** [comment]
For example,

| time | user | type | scores | id |
| ------ | ------ | ------ | ----- | ----- |
| 1 | user1 | solve | 100 | solveid:1 |
| 2 | user2 | solve | 200 | solveid:2 |
| 3 | user1 | award | 100 | awardid:1| 

User 2 reaches 200 points first, but user1 is on top becase user1 has less max(solveid,awardid)
Here is the screenshot:

![screenshot from 2018-11-15 14-49-51](https://user-images.githubusercontent.com/31540650/51305851-ee6b8e00-1a76-11e9-8727-320bdd8c009e.jpeg)

**Comment by ColdHeat** [comment]
Okay I see your point. Would you be willing to PR the fix for this?
