### ISSUE TITLE
Notifications can be accessible when Visibility private

### ISSUE THREAD

**Issue by tnmch** [CTFd/CTFd#838]
Users can access the notification tab without authentication when settings for (score,challenge,users) on mode private 
![config](https://user-images.githubusercontent.com/7364615/51400928-e4668f80-1b49-11e9-8def-bb1a90ac053e.png)

**Comment by ColdHeat** [comment]
This is intentional. I'm not even sure why you would draw the conclusion that Notifications are private if there isn't a setting that says Notifications would be private.

**Comment by tnmch** [comment]
Since notifications will also include information about running CTF, if someone just want to hide details,maybe also need to add visibility to notifications?

**Comment by ColdHeat** [comment]
Notifications could also contain global information not pertinent to the CTF. The current implementation uses global notifications and later on will be more specific about what users are targeted.
