### ISSUE TITLE
init_logs not called, no handlers installed

### ISSUE THREAD

**Issue by tecknicaltom** [CTFd/CTFd#839]
**Environment**:

  - CTFd Version/Commit: 6e8c7aaa50857fde0be87f694c134ce714e11221
  - Operating System: Linux (deployed via Docker)
  - Web Browser and Version: Firefox

**What happened?**
Since the 2.0 commit, it appears that `CTFd.utils.logging.init_logs` isn't called. As a result, `log()` calls aren't logged to the log files

**What did you expect to happen?**
Calls to `log()` should result in log files

**How to reproduce your issue**
from a console:
```
import logging
print(logging.getLogger('logins').handlers)
from CTFd.utils.logging import init_logs
init_logs(app)
print(logging.getLogger('logins').handlers)
```

**Any associated stack traces or error logs**
N/A

**Comment by ColdHeat** [comment]
Thanks for reporting this, complete oversight. If you have any extra time it would be great to come up with a test that verifies that we're writing logs. 

Closed with f8607c3d5c21fe523aa1e1f421300c5b606147ce
