### ISSUE TITLE
Custom database port in DATABASE_URL breaks docker-entrypoint.sh

### ISSUE THREAD

**Issue by arush15june** [CTFd/CTFd#846]
**Environment**:

  - CTFd Version/Commit:  [92e7be224bf9340ee671bd7ae9933feadab1b4d9](https://github.com/CTFd/CTFd/commit/92e7be224bf9340ee671bd7ae9933feadab1b4d9)
  - Operating System: Kali Linux 
  - Web Browser and Version: Chrome

**What happened?**
Passing the DATABASE_URL in SQLAlchemy's format with the port (ex. `mysql+pymysql://root:<PASSWORD>@<IP>:<PORT>/ctfd`) breaks mysqladmin pinging the database before launching gunicorn in [docker-enrypoint.sh](https://github.com/CTFd/CTFd/blob/92e7be224bf9340ee671bd7ae9933feadab1b4d9/docker-entrypoint.sh). mysqladmin expects the IP without the port and the current docker-entrypoint.sh extracts the whole IP with the port.

**What did you expect to happen?**
Only pass the database's IP to `mysqladmin ping`, change
[docker-entrypoint.sh#L21](https://github.com/CTFd/CTFd/blob/92e7be224bf9340ee671bd7ae9933feadab1b4d9/docker-entrypoint.sh#L21)
from ``database=`echo $DATABASE_URL | awk -F[@//] '{print $4}'` ``
to ``database=`echo $DATABASE_URL | awk -F[@//:] '{print $6}'` ``

**How to reproduce your issue**
set `DATABASE_URL` to `mysql+pymysql://root:ctfd@db:3306/ctfd` in [docker-compose.yml](https://github.com/CTFd/CTFd/blob/92e7be224bf9340ee671bd7ae9933feadab1b4d9/docker-compose.yml)

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
If you're running on port 3306 then you could just remove the port right? There could be other issues here when using a non-standard port though. 

Your proposed fix does work but it doesn't really help out in a more generic sense. Could you PR a fix that would let arbitrary ports work?
