### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#854]
We should have a notification sound to let people know a notification has come in. This should be a public domain sound because it will be under the MIT license. Not sure about how compatibility works between CC and MIT.

**Comment by KyleMiles** [comment]
Made by Terrence Martin (and shared with his permission):
drive.google.com/file/d/0B7Zgol7O8Nb9dGhQX2M4WVo3YW8/view

**Comment by ColdHeat** [comment]
We will need a wrapper around web audio. https://github.com/goldfire/howler.js seems like a strong choice.

**Comment by ColdHeat** [comment]
@KyleMiles does Terrence have a website/soundcloud/twitter that he wants linked in the Credits section?

**Comment by ColdHeat** [comment]
Closing issue to clear this out of the milestone.

**Comment by KyleMiles** [comment]
Yeah, thanks... You can leave a credit link [here](https://soundcloud.com/tj-martin-composer).
