### ISSUE TITLE
Team scores go down

### ISSUE THREAD

**Issue by Gamn69** [CTFd/CTFd#858]
**Environment**:

  - CTFd Version/Commit: 2.0.3
  - Operating System: Ubuntu 16.04
  - Web Browser and Version: Chrome

**What happened?**
Team scores went down when the points for the challenge got decreased because of the amount of solves.

**What did you expect to happen?**
I expected the challenge point value to go down depending on the amount of solves and the earlier on you solve the more points you get.

**Comment by ColdHeat** [comment]
This is how dynamic solves works. You can read more about it here: https://github.com/CTFd/DynamicValueChallenge#dynamic-value-challenges-for-ctfd
