### ISSUE TITLE
Develop "Dynamic Templates"

### ISSUE THREAD

**Issue by grant-h** [CTFd/CTFd#865]
During SwampCTF we had 28 challenges, all dynamically scored. This means we had to input 4 distinct numbers in the right order for all challenges and keep them in sync. Any changes to the decay limit, minimum, or maximum scores had to be changed on all changes.

This was time consuming and error prone. I propose that this plugin offer a choice for admins to create _dynamic templates_. These templates would be created once in a separate UI and then be able to be selected during challenge creation via a drop down menu. This drop down menu could contain things like

- Standard Challenge
- Easy Challenge
- Medium Challenge
- Hard Challenge
- Custom

Having a centralized template creation menu would greatly simplify changes to the scoring after testing or during production.

**Comment by frankli0324** [comment]
I think it would be better to provide a way to customize how a challenge would be scored, parallel to "challenges" and "flags"
