### ISSUE TITLE
Realtime feed CTFtime for v2?

### ISSUE THREAD

**Issue by mehulmpt** [CTFd/CTFd#872]
**What happened?**

What is the endpoint for realtime scoreboard feed implementation in v2 of CTFd? I could not find it. The closest I got was `/api/v1/scoreboard` but it uses incorrect format for CTFtime

**Comment by michaelasper** [comment]
Agreed, /scores no longer does it

**Comment by ColdHeat** [comment]
From my perspective, the CTFTime format is restrictive. I'll consider bringing it back but until then a pretty simple to write plugin can easily achieve this behavior.

**Comment by kjcolley7** [comment]
https://github.com/HackUCF/CTFd-scores-ctftime

**Comment by ColdHeat** [comment]
This is now supported via an MLC integration and documented at https://docs.ctfd.io/en/latest/scoring.html#ctftime.

**Comment by aryan-02** [comment]
Okay, now somehow CTFtime no longer accepts the MLH scoreboard feed (even with fomat=legacy).
![image](https://user-images.githubusercontent.com/29256761/91293313-6fdbe400-e7b5-11ea-8f81-e5c7900463e3.png)

**Comment by ColdHeat** [comment]
I will try to communicate with the CTFTime organizers about this and hope that we can find a resolution but I can't make any guarantees.
