### ISSUE TITLE
Changes are not reflecting.

### ISSUE THREAD

**Issue by PraveenKumarSoni** [CTFd/CTFd#873]
**Environment**:

  - CTFd Version/Commit:
  - Ubuntu16:
  - Mozila Firefox :

**Changes are not reflecting of views.py. I'm trying to change the content of front of CTFd. After changes in file /CTFd/Views.py**

**After changes in views.py content of the front page should be change but didn't**

**Comment by ColdHeat** [comment]
The content of the main index page is controlled by the index page in the Admin Panel.

**Comment by PraveenKumarSoni** [comment]
Done.
