### ISSUE TITLE
Changing Point Value of Challenges Changes All Solves

### ISSUE THREAD

**Issue by jpreese** [CTFd/CTFd#882]
**Environment**:

* CTFd Version/Commit: 2.0.3
* Operating System: Ubuntu 16.04
* Web Browser and Version: Chrome

**What happened?**
I published a challenge and had multiple users solve it.
I then released another challenge and reduced the point value of the previous solution (because I gave the answer before releasing the next one).
I then noticed the points were retroactively applied. Meaning, when I changed the point value, everyones scores went down.

**What did you expect to happen?**
Everyones scores to stay the same. If you solve the challenge from that point forward, you get the latest value.

**How to reproduce your issue**
Create a challenge with 100 points.
Solve the challenge (be granted 100 points).
Change the point value to 50.
This reduces your 100pts down to 50.

Is this intended behavior?

**Comment by ColdHeat** [comment]
Yes that's intentional behavior and inline with how CTFs are generally run. In CTFd it is difficult to represent a concept where one user receives a different value for a challenge than another but you could do that by providing awards for people. 

Also was this a standard challenge or a dynamic challenge?

**Comment by ColdHeat** [comment]
I think a good follow up question for me would be why would you want the challenge to be worth different points to different people? I think having rewards for first to solve or similar are nice and already possible but a 50 point difference could be pretty significant in the overall game. Did you have some kind of game mechanic in mind?

**Comment by jpreese** [comment]
I'm doing a Weekly CTF where I release one problem per week. After the week is over, I post a blog writeup on how to solve the problem in case you couldnt solve it and/or to start a discussion around it.

When the answer is given, I want the future solves to be worth less. So if you solve the challenge in the week its released, you get full points. Otherwise you get less. Is that possible somehow?

**Comment by ColdHeat** [comment]
The only way to implement this would be to write a custom challenge type plugin. It's not very easy to support the same challenge having different values for different people but you could implement it with a custom challenge type and using awards but it could be a little tricky.
