### ISSUE TITLE
File Upload Doesnt Work

### ISSUE THREAD

**Issue by asdfilelala** [CTFd/CTFd#883]
**Environment**:

  - CTFd Version/Commit: 2.0.4
  - Operating System: Windows Server 2012R2
  - Web Browser and Version: Chrome 70.x

**What happened?**

I uploaded a file to a specific challenge and when I click to download it the url returns 404 not found
Or to be exact: 404 Whoops, looks like we can't find that. Sorry about that.

**What did you expect to happen?**

The file to be downloaded..

**How to reproduce your issue**

Upload a file and try to download it.

**Any associated stack traces or error logs**

N/A

**Comment by ColdHeat** [comment]
File uploads are working but it's tough to debug this specific issue. My suspicion would be that maybe there's a permissions error on the folder that you upload to?

**Comment by ColdHeat** [comment]
I'm closing this because I have a suspicion this is related to your specific deployment situation versus an issue in CTFd. If you have any other information that can help narrow down the issue let me know.

**Comment by TowelDude** [comment]
It is not related to permissions.


in `utils/uploads/uploaders.py` replacing `safe_join` with `os.path.join` solves this issue


it now allows for path traversal, but this might help figuring out the source of the issue.

**Comment by ColdHeat** [comment]
@TowelDude what are the values being joined? Perhaps there's an issue with how safe_join handles Windows directories?

**Comment by TowelDude** [comment]
The values are 
`base_path` and a joined string of the random md5 (challenge id?) and the filename itself.

looks like:
```25dfe71940ttezsee\\file.txt```

im guessing that `safe_join` is having issues with the directory present in the 2nd argument.
