### ISSUE TITLE
Stored XSS 

### ISSUE THREAD

**Issue by Unknow101** [CTFd/CTFd#888]
**Environment**:

  - CTFd Version/Commit: 1f768dbfaf171a95e7da1d32174af6fc1aee9f24 (Last one)
  - Operating System: Ubuntu 
  - Web Browser and Version: Firefox , last on

**What happened?**

XSS stored in Category and challenge name

**What did you expect to happen?**

I expected that the XSS will work, that work.

**How to reproduce your issue**

Create a new challenge > Name : <script>alert(1);</script>, Categorie : <script>alert(1);</script>
Enjoy two pop-up

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
In the future please send any potential security vulnerabilities to support@ctfd.io. 

Secondly, CTFd doesn't consider admin to admin XSS a vulnerability. You are not achieving any form of privilege escalation. Admin to user XSS is also not a vulnerability. 

To consider XSS a vulnerability you need to demonstrate user to admin privilege escalation.
