### ISSUE TITLE
Challenges with large IDs cannot be displayed.

### ISSUE THREAD

**Issue by SolalPirelli** [CTFd/CTFd#890]
**Environment**:

  - CTFd Version/Commit: `latest` tag on Docker
  - Operating System: Ubuntu 18.04 for the server
  - Web Browser and Version: Edge (but it shouldn't matter

**What happened?** Challenges with large IDs cannot be displayed (e.g. 2053355150134128054).

**What did you expect to happen?** Any challenge should be displayed.

**How to reproduce your issue**: Create a challenge with an ID above what JavaScript can represent in a number (> 2^53). The number gets truncated when parsed from JSON, since JavaScript represents all numbers as floating-point.

I guess the solution is to transmit IDs as strings instead...

**Comment by ColdHeat** [comment]
What's the expected use case here? This seems like something where the fix would be more trouble than its worth...

**Comment by SolalPirelli** [comment]
I expect to be able to insert any data in the DB that fulfills the schema, and have the website handle the data correctly.

**Comment by ColdHeat** [comment]
This sounds like a won't fix honestly but I recognize that it is an issue. If someone wants to tackle this and PR a fix perhaps we can target it for a major release.
