### ISSUE TITLE
Create edit team view

### ISSUE THREAD

**Issue by grant-h** [CTFd/CTFd#893]
Since the switch to MLC and the separation between users and teams in the 2.0 version, only the user's profile can be edited from CTFd. Create a view to also edit the team information just like in 1.0. Also there are some error messages in register that are inconsistent with the front-end (e.g., "Team name exists" when in user mode only).

**Comment by ColdHeat** [comment]
https://github.com/CTFd/CTFd/tree/893-edit-team-improvements

- Edit team members from the admin panel
- Edit team properties from the user facing side. 
    - Who has the permission to change team properties? Only the creator? All team members?

**Comment by ColdHeat** [comment]
This has been implemented in #949. It'd be great if you could give any feedback on this feature.
