### ISSUE TITLE
Cannot unset country field

### ISSUE THREAD

**Issue by grant-h** [CTFd/CTFd#894]
**Environment**:

  - CTFd Version/Commit: tag 2.0.4
  - Operating System: Ubuntu 16.04
  - Web Browser and Version: Chrome latest

**What happened?**
I changed my country to "Blank" (`<option></option>`) in settings, hit update, it said success, but refresh showed old country.

**What did you expect to happen?**
My country to be blank upon reload.

**How to reproduce your issue**
Set your country to anything (except blank). Try to change back to blank.

**Any associated stack traces or error logs**
N/A

**Comment by ColdHeat** [comment]
Thanks for reporting, somehow I missed this. 

This is vaguely related to front end testing though. If we had some automated browser tests we could probably catch things like this. Probably a ways off from that though.
