### ISSUE TITLE
Taiwai is part of Chine 

### ISSUE THREAD

**Issue by hubu-wangpei** [CTFd/CTFd#910]
Taiwai is part of Chine ,Can you make it right?

**Comment by ColdHeat** [comment]
I did not personally generate the list of countries used in CTFd. It comes from other online sources. 

https://en.wikipedia.org/wiki/ISO_3166-1
https://github.com/umpirsky/country-list/blob/master/data/en_US/country.csv#L223

Also related: https://github.com/umpirsky/country-list/issues/89
