### ISSUE TITLE
Flag-less challenge detection

### ISSUE THREAD

**Issue by Helithumper** [CTFd/CTFd#926]
When setting up the last two CTFs, we have noticed that we could accidentally not add flags to challenges. There aren't any warnings / systems to ensure that you have at least one flag set. Perhaps adding a column next to the "State" column in the admin console to show missing fields would be useful.

**Comment by ColdHeat** [comment]
This is a good point and I've noticed it myself. I think there's a better approach of prompting the user for a flag right after creation which should help the problem.

**Comment by ColdHeat** [comment]
Closed in #1147

![image](https://user-images.githubusercontent.com/166333/67172636-0f586b00-f38a-11e9-9b7c-b13dd99dc7f6.png)
