### ISSUE TITLE
Document base system requirements for CTFd's database

### ISSUE THREAD

**Issue by karatyman** [CTFd/CTFd#947]
**Environment**: AWS

  - CTFd Version/Commit: Latest
  - Operating System: Amazon Linux 2
  - Web Browser and Version:

**What happened?** 
Trying to connect to an amazon RDS hosted mysql DB but getting an issue with sql syntax

**What did you expect to happen?**

CTFD to make the basic table structure

**How to reproduce your issue**

attempt to connect to an rds mysql instance using the advanced configuration guide
(note I set the RDS instance to open and created a security group to allow traffic so I verified its not a connectivity issue)

**Any associated stack traces or error logs**

sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON, \n\tPRIMARY KEY (id)\n)' at line 10") [SQL: u'\nCREATE TABLE challenges (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(80), \n\tdescription TEXT, \n\tmax_attempts INTEGER, \n\tvalue INTEGER, \n\tcategory VARCHAR(80), \n\ttype VARCHAR(80), \n\tstate VARCHAR(80) NOT NULL, \n\trequirements JSON, \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by ColdHeat** [comment]
Can you try manually creating the tables by using `python manage.py db upgrade`? What is your MySQL version?

**Comment by karatyman** [comment]
@ColdHeat  So I tried the upgrade and got this error:
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON, \n\tPRIMARY KEY (id)\n)' at line 10") [SQL: u'\nCREATE TABLE challenges (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(80), \n\tdescription TEXT, \n\tmax_attempts INTEGER, \n\tvalue INTEGER, \n\tcategory VARCHAR(80), \n\ttype VARCHAR(80), \n\tstate VARCHAR(80) NOT NULL, \n\trequirements JSON, \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405

I've tried it on mysql 4.7 and 4.6.4(default for rds) is there a reccomended version?

**Comment by ColdHeat** [comment]
Pretty sure any MySQL below 5.7 isn't going to work. Try something around there?

**Comment by vmmorris** [comment]
Sorry, the second test I ran was on 5.7.4 not 4.7.4*

**Comment by karatyman** [comment]
Sorry, the second test I ran was on 5.7.4 not 4.7.4*

**Comment by ColdHeat** [comment]
Try version >= 5.7.8? CTFd now requires support of the JSON data type so I believe that's where your issues are coming from.
