### ISSUE TITLE
Need More Rate Limiting for Login Request

### ISSUE THREAD

**Issue by Merikanto** [CTFd/CTFd#951]
**Environment**:

  - CTFd Version/Commit: Newest Version
  - Operating System: LInux
  - Web Browser and Version: Firefox 

**What happened?**

https://2019.sunshinectf.org/login

I used Burpsuite's intruder to brute force the name & password combinations from the login page (trying my account of course), and I injected thousands of POST requests using the same nonce (and only received a couple of 429 warnings scattering among the results).

**What did you expect to happen?**

I would receive HTTP 429 warning continuously after a few dozens of requests. 

**How to reproduce your issue**

Turn on interception. Then type some trash in the name & password fields. Then send the HTTP raw request to intruder. Use cluster bomb and select only these 2 positions: name & password . Then use any wordlists in payload sets. Start attack.

**Any associated stack traces or error logs**
![3](https://user-images.githubusercontent.com/45705788/56095264-d1453080-5ea8-11e9-97e7-ac70bf579580.png)

**Comment by Merikanto** [comment]
Same with:  https://recruit.osiris.cyber.nyu.edu/login

This is even worse (in terms of rate limiting).

**Comment by ColdHeat** [comment]
This behavior is tested, do you have better defaults to use for the rate limiting decorator? 

https://github.com/CTFd/CTFd/blob/c8031b38c27926b8166174af331bc2b4ab614c1b/tests/utils/test_ratelimit.py

You have to keep in mind that ratelimiting unauthed users is risky because many people might be NAT'ed behind a single university IP. 

The nonce used here is a CSRF nonce which does not strictly need to be unique per request.

**Comment by Merikanto** [comment]
http://flask.pocoo.org/snippets/3/

Is it possible to add a CSRF token for protection?

**Comment by ColdHeat** [comment]
As I said earlier "The nonce used here is a CSRF nonce which does not strictly need to be unique per request."

**Comment by Merikanto** [comment]
OK, thanks! I'll close this one.

**Comment by Merikanto** [comment]
My only issue was that someone might utilise to brute force other teams/ passwords, since the username is known. And many teams do have weak passwords.

**Comment by ColdHeat** [comment]
Do you have a better suggestion for a fix for better ratelimiting? I'm not sure you're making a great case for your issue.

**Comment by Merikanto** [comment]
I was meant to say it's the CSRF token for the cookies, but not for a nonce. 

https://blog.miguelgrinberg.com/post/cookie-security-for-flask-applications

Anyways, if this doesn't fix the issue, I wouldn't know a better fix.
