### ISSUE TITLE
Adding second admin accounts

### ISSUE THREAD

**Issue by november781** [CTFd/CTFd#969]
This is a feature request!

It would be really helpful if there was a way to add another admin account from the admin panel.
I am working on a team that is setting up a competition, as we have multiple members on our admin team, it would be great to be able to set them all up with separate accounts with separate passwords.

If there is a way to do this currently, please let me know.

**Comment by ColdHeat** [comment]
This is already possible. You can add a new account or upgrade a user to an admin.
