### ISSUE TITLE
file 404 error

### ISSUE THREAD

**Issue by zeromovie** [CTFd/CTFd#971]
**Environment**:

  - CTFd Version/Commit:lastest version
  - Operating System:win10
  - Web Browser and Version:newest chrome , firefox

**What happened?**
i could upload a file to websitefolder(CTFd/upload/xxxxxxxxxxxxx/xxx.txt) but can't download them to my pc, it says 404
**What did you expect to happen?**
make it working
**How to reproduce your issue**
just simply install reqs and run sserver.py , use buildin sqlite
**Any associated stack traces or error logs**
127.0.0.1 - - [28/Apr/2019 14:56:38] "GET /files/114270be6f7de95c25f61f67f2303c64%5Clogo.png HTTP/1.1" 404 -

**Comment by zeromovie** [comment]
anyway thanks your awesome hardword, if idoing someting wrong please correct me

**Comment by ColdHeat** [comment]
This likely means that there is either a permissions issue or some other underlying issue preventing the web server from saving the file. You can use s3 based file uploads or try to identify the underlying issue here.

**Comment by zeromovie** [comment]
ok, thank you, and I notice that even the demo of ctfd has the bug of file upload, i will try to fix and point it out here

**Comment by ColdHeat** [comment]
I believe the demo website is file upload restricted so you likely won't be able to upload any files there. If you reproduce this you'll need to reproduce it locally and share whatever configurations or changes you've made.

**Comment by zeromovie** [comment]
the file stroed as this: 
![图片](https://user-images.githubusercontent.com/20042454/56885991-8595a800-6aa0-11e9-948a-95f02747ff22.png)

but i got this instead: 
![图片](https://user-images.githubusercontent.com/20042454/56886158-e2915e00-6aa0-11e9-8fa7-ddc209df01ab.png)

i just upload this "red.jpg" as the ctf logo, and i even see it in uploads folder, but can't get it from browser

**Comment by zeromovie** [comment]
maybe becauser of the "%5C"?

**Comment by zeromovie** [comment]
![图片](https://user-images.githubusercontent.com/20042454/56886535-ca6e0e80-6aa1-11e9-9a7e-f9c1f48a37ef.png)

**Comment by zeromovie** [comment]
![图片](https://user-images.githubusercontent.com/20042454/56917591-763d4b80-6aee-11e9-9f6d-989512393ed6.png)
in the demo it looks like no '%5c' appears. but manualy change it to '/' still doesn't work, althougt it has been really uploaded in my uploads folder

**Comment by ColdHeat** [comment]
You should try to reproduce the issue on a local development instance not using the demo. If you're able to reproduce you can share the sqlite database to help reproduce.

**Comment by zeromovie** [comment]
I found the issue "os.path" in win10 is "//” so i just replace it into '/' and i use '/' to joint the filename and it works!
