### ISSUE TITLE
CTFd doesn't handle URL protocol properly (mixing HTTP with HTTPS)

### ISSUE THREAD

**Issue by adiov** [CTFd/CTFd#987]
**Environment**:

  - CTFd Version/Commit: b7a19f7
  - Operating System: Alpine 3.9.3
  - Running CTFd with [tghosth/CTFd-docker-deploy](https://github.com/tghosth/CTFd-docker-deploy) behind a TLS-terminating Nginx.
  - Reverse proxy properly returns the host, original IP, and the requested protocol via `X-Forwarded-Proto`.
  - Web Browser and Version: Chrome 73

**What happened?**
While running under HTTPS, several areas in CTFd return and redirect to `http://` when they should be `https://`. I encountered this behaviour in the following areas:

- All redirects caused by accessing an area that requires authentication without being authenticated. (e.g. `https://ctfdomain.example/user` -> `http://ctfdomain.example/login`)
- All redirects resulting from actions processed by the server. (e.g. the redirect that happens after importing a backup)
- All redirects performed in a custom plugin I'm writing using Flask Dance (it's for Okta authentication). I realise this will be difficult to reproduce, so I'm listing here it at last. Hopefully this shares the same root cause as the other two as it's my biggest pain point.

**What did you expect to happen?**
Everything should be HTTPS.

**How to reproduce your issue**

**A. Backup import:**
1. Import a backup.
2. Wait until a redirect to HTTP happens.

I reproduced it on CTFd's own `demo.ctfd.io`

![image](https://user-images.githubusercontent.com/7467822/57473523-acba5980-7298-11e9-9276-96cfc2fdbec1.png)

**B. Auth redirect:**
1. `curl -I https://ctfdomain.example/user`
2. Notice the returned `Location:` header pointing to `http://`.

`demo.ctfd.io` is authed all the time, so I can't repro there, but this screenshot is from a publicly available CTF found in the first page of Googling for "Powered by CTFd".

![image](https://user-images.githubusercontent.com/7467822/57473833-6f0a0080-7299-11e9-9176-8dce830b2dd1.png)

**Comment by ColdHeat** [comment]
I appreciate the detailed response. Have you properly configured the `REVERSE_PROXY` configuration value in `config.py`?

The demo site might be out of date or misconfigured but I couldn't reproduce this on a hosted CTFd instance. 

```
❯ curl -I https://******.ctfd.io/user
HTTP/2 302
content-type: text/html; charset=utf-8
date: Thu, 09 May 2019 21:57:18 GMT
location: https://*******.ctfd.io/login?next=%2Fuser%3F
```

**Comment by adiov** [comment]
`REVERSE_PROXY` is already set to `true` in the `environment` section in  `docker-compose.yaml`. I also confirmed it's the case by doing a `print(environ["REVERSE_PROXY"])` in my plugin which printed `true` in my stdout logs.

**Comment by ColdHeat** [comment]
I know that ProxyFix was moved around a bit in Werkzeug 0.15.2 but I also know that another CTFd instance I've seen setup did not run into this problem. 

Can you minify your test case to make it easier to reproduce?

**Comment by ColdHeat** [comment]
```
export REVERSE_PROXY=true
python serve.py
```

```
~
❯ curl -H "X-Forwarded-Proto: https" -I http://localhost:4000/user
HTTP/1.0 302 FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 251
Location: https://localhost:4000/login?next=%2Fuser%3F
Set-Cookie: session=9338ee0e-511d-4f2f-b45b-aaeada9fcefd; HttpOnly; Path=/; SameSite=Lax
Server: Werkzeug/0.15.2 Python/2.7.15
Date: Fri, 10 May 2019 06:03:21 GMT
```

**Comment by adiov** [comment]
While trying to isolate the issue to make more portable reproduction steps, I have noticed that I had `wsgi.url_scheme=http` set because a month ago I was having the opposite problem during testing. I have now set it to `https` and everything is working as expected. Thanks for the help, Kevin :)
