### ISSUE TITLE
Users cannot see their own solves after freeze

### ISSUE THREAD

**Issue by zozs** [CTFd/CTFd#988]
**Environment**:

  - CTFd Version/Commit: 2.1.1
  - Operating System: Arch Linux / docker-compose from CTFd
  - Web Browser and Version: Firefox 66

**What happened?**

After the freeze time of a CTF, users cannot easily see if they have solved a challenge or not. Challenges solved _after_ the freeze time are not marked as "green" (in the default theme). Challenges solved _before_ the freeze are marked as green when they are solved, as expected.

This causes some confusion among users, since they are not sure if their solves are counted or not. (They are, and if they submit the flag again they get an "You have already solved this challenge message). However, the challenge is not marked as green/solved in the UI.

**What did you expect to happen?**

The users themselves should see that they have solved the challenge, just as before the freeze. No other users should see that they solved the challenge (since the scoreboard is frozen).

**How to reproduce your issue**

Setup a CTF with a start time, end time, and freeze time. After the freeze (but before the end), solve some challenge as a user. It will not be "green" in the UI during the freeze, even though it is solved.

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
Thanks for reporting these issues! Do you think you can try the changes in #989 to make sure they resolve the issues you pointed out?

**Comment by zozs** [comment]
I have tested the merged-in changes in master and they resolve both issues. Thanks!
