### ISSUE TITLE
Cant import legacy CTFD challenges

### ISSUE THREAD

**Issue by karatyman** [CTFd/CTFd#990]
**Environment**:

  - CTFd Version/Commit: Latest
  - Operating System: Amazon Linux 2
  - Web Browser and Version: Chrome

**What happened?**

We attempted to import a previous export we made on an older version of CTFD of just our challenges and were unable to to get the challenges into the latest version of CTFD. This was the error we saw the error below in the console:

**What did you expect to happen?**
Our legacy ctfd challenges in the latest ctfd instance

**How to reproduce your issue**

I could provide the old ctfd version 

**Any associated stack traces or error logs**

[root@ip-172-31-85-239 CTFd]# python import.py Hack4Troops.2019-05-11.zip 
 * Loaded module, <module 'CTFd.plugins.challenges' from '/home/www-ctfd/CTFd/CTFd/plugins/challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.dynamic_challenges' from '/home/www-ctfd/CTFd/CTFd/plugins/dynamic_challenges/__init__.pyc'>
 * Loaded module, <module 'CTFd.plugins.flags' from '/home/www-ctfd/CTFd/CTFd/plugins/flags/__init__.pyc'>
Traceback (most recent call last):
  File "import.py", line 11, in <module>
    import_ctf(sys.argv[1])
  File "/home/www-ctfd/CTFd/CTFd/utils/exports/__init__.py", line 177, in import_ctf
    alembic_version = json.loads(backup.open('db/alembic_version.json').read())["results"][0]["version_num"]
  File "/usr/lib64/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib64/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'db/alembic_version.json' in the archive"

**Comment by ColdHeat** [comment]
Legacy imports aren't supported in the same way that a modern import is. For a legacy export file you want to import at the version of CTFd that the export was taken at and then upgrade CTFd. From there you'll have a more modern export which has the proper database version stored. 

To upgrade an older CTFd instance you should follow the instructions in the changelog for version 2.0.0.
