### ISSUE TITLE
wiki: update plugins section with CSRF

### ISSUE THREAD

**Issue by eyJhb** [CTFd/CTFd#998]
I have taken the liberty of updating some information in the plugins section on the wiki, as I used way to much time on this.

I have included my patch here, just apply it using `git apply wiki-plugins.txt` :)

[wiki-plugins.txt](https://github.com/CTFd/CTFd/files/3192909/wiki-plugins.txt)

**Comment by ColdHeat** [comment]
You can issue a PR against the docs branch where documentation is being written.
